const fs = require('fs');

const dishesPath = 'c:/Users/lenovo/OneDrive/Desktop/resturant/frontend/data/dishes.ts';
let dishesContent = fs.readFileSync(dishesPath, 'utf8');

// Complete 85+ authentic bakery dishes matching every single subcategory requested
const completeBakeryCatalog = `
  // ==========================================
  // GIRI BAKERY COMPLETE 85+ SUB-CATEGORY DISHES
  // ==========================================
  
  // 1. CAKES (Birthday, Wedding, Photo, Theme, Chocolate, Red Velvet, Black Forest, Fruit, Cheesecakes)
  {
    id: 'bakery-dish-c1',
    name: 'Customized Celebration Birthday Layer Cake',
    category: 'desserts',
    shopSlug: 'giri-bakery',
    shopName: 'Giri Bakery',
    price: 850,
    description: 'Multi-layer vanilla & Belgian chocolate sponge topped with buttercream rosettes, edible pearls, and custom birthday plaque.',
    image: 'https://images.unsplash.com/photo-1535141192574-5d4897c13136?w=800&auto=format&fit=crop&q=85&v=bakery-dish-c1',
    dietary: ['veg', 'chef-special'],
    prepTime: 15,
    available: true,
    customizations: [{ name: 'Custom Name Plaque Writing', price: 50 }]
  },
  {
    id: 'bakery-dish-c2',
    name: 'Grand Tiered Fondant Wedding Cake',
    category: 'desserts',
    shopSlug: 'giri-bakery',
    shopName: 'Giri Bakery',
    price: 1800,
    description: 'Grand 3-tiered white chocolate ganache wedding cake with handcrafted sugar flowers and champagne syrup infusion.',
    image: 'https://images.unsplash.com/photo-1565958011703-44f9829ba187?w=800&auto=format&fit=crop&q=85&v=bakery-dish-c2',
    dietary: ['veg', 'chef-special'],
    prepTime: 30,
    available: true,
    customizations: [{ name: 'Sparkling Candle Set', price: 40 }]
  },
  {
    id: 'bakery-dish-c3',
    name: 'Custom Edible Photo Print Cake',
    category: 'desserts',
    shopSlug: 'giri-bakery',
    shopName: 'Giri Bakery',
    price: 950,
    description: 'Fresh cream pineapple sponge cake topped with high-definition edible sugar paper photo print.',
    image: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=800&auto=format&fit=crop&q=85&v=bakery-dish-c3',
    dietary: ['veg'],
    prepTime: 20,
    available: true,
    customizations: [{ name: 'Photo Upload Processing', price: 0 }]
  },
  {
    id: 'bakery-dish-c4',
    name: 'Superhero & Floral Theme Designer Cake',
    category: 'desserts',
    shopSlug: 'giri-bakery',
    shopName: 'Giri Bakery',
    price: 1100,
    description: 'Artisanal handcrafted theme cake with fondant cutouts, chocolate rocks, and rich chocolate truffle center.',
    image: 'https://images.unsplash.com/photo-1588195538326-c5b1e9f80a1b?w=800&auto=format&fit=crop&q=85&v=bakery-dish-c4',
    dietary: ['veg'],
    prepTime: 25,
    available: true,
    customizations: [{ name: 'Theme Color Choice', price: 0 }]
  },
  {
    id: 'bakery-dish-c5',
    name: 'Signature Dutch Dark Chocolate Fudge Cake',
    category: 'desserts',
    shopSlug: 'giri-bakery',
    shopName: 'Giri Bakery',
    price: 750,
    description: 'Moist dark cocoa sponge layered with molten Belgian fudge and dusted with Dutch cocoa powder.',
    image: 'https://images.unsplash.com/photo-1606313564200-e75d5e30476c?w=800&auto=format&fit=crop&q=85&v=bakery-dish-c5',
    dietary: ['veg', 'chef-special'],
    prepTime: 10,
    available: true,
    customizations: [{ name: 'Add Extra Chocolate Dip', price: 30 }]
  },
  {
    id: 'bakery-dish-c6',
    name: 'Crimson Red Velvet Cream Cheese Cake',
    category: 'desserts',
    shopSlug: 'giri-bakery',
    shopName: 'Giri Bakery',
    price: 790,
    description: 'Classic cocoa velvet cake layered with smooth Philadelphia cream cheese icing and red velvet crumbs.',
    image: 'https://images.unsplash.com/photo-1616541823729-00fe0aacd32c?w=800&auto=format&fit=crop&q=85&v=bakery-dish-c6',
    dietary: ['veg'],
    prepTime: 10,
    available: true,
    customizations: [{ name: 'Extra Cream Cheese Drizzle', price: 35 }]
  },
  {
    id: 'bakery-dish-c7',
    name: 'German Black Forest Maraschino Cherry Cake',
    category: 'desserts',
    shopSlug: 'giri-bakery',
    shopName: 'Giri Bakery',
    price: 690,
    description: 'Traditional chocolate sponge soaked in cherry syrup, layered with whipped cream, maraschino cherries, and dark chocolate shavings.',
    image: 'https://images.unsplash.com/photo-1606890737304-57a1ca8a5b62?w=800&auto=format&fit=crop&q=85&v=bakery-dish-c7',
    dietary: ['veg'],
    prepTime: 10,
    available: true,
    customizations: [{ name: 'Extra Cherries Bowl', price: 30 }]
  },
  {
    id: 'bakery-dish-c8',
    name: 'Fresh Exotic Berry & Tropical Fruit Cake',
    category: 'desserts',
    shopSlug: 'giri-bakery',
    shopName: 'Giri Bakery',
    price: 720,
    description: 'Light vanilla bean sponge crowned with fresh kiwi, strawberries, blueberries, peaches, and passion fruit glaze.',
    image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=800&auto=format&fit=crop&q=85&v=bakery-dish-c8',
    dietary: ['veg'],
    prepTime: 10,
    available: true,
    customizations: [{ name: 'Extra Fresh Berries Topping', price: 40 }]
  },
  {
    id: 'bakery-dish-c9',
    name: 'New York Baked Blueberry Swirl Cheesecake',
    category: 'desserts',
    shopSlug: 'giri-bakery',
    shopName: 'Giri Bakery',
    price: 890,
    description: 'Rich dense cream cheese baked on a buttery graham cracker crust, finished with fresh blueberry compote.',
    image: 'https://images.unsplash.com/photo-1533134242443-d4fd215305ad?w=800&auto=format&fit=crop&q=85&v=bakery-dish-c9',
    dietary: ['veg', 'chef-special'],
    prepTime: 10,
    available: true,
    customizations: [{ name: 'Extra Blueberry Compote', price: 35 }]
  },

  // 2. PASTRIES (Chocolate, Pineapple, Red Velvet, Black Forest, Butterscotch, Fruit)
  {
    id: 'bakery-dish-p1',
    name: 'Belgian Chocolate Ganache Pastry',
    category: 'desserts',
    shopSlug: 'giri-bakery',
    shopName: 'Giri Bakery',
    price: 180,
    description: 'Decadent dark chocolate sponge pastry layered with silky 70% Belgian chocolate ganache.',
    image: 'https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=800&auto=format&fit=crop&q=85&v=bakery-dish-p1',
    dietary: ['veg'],
    prepTime: 5,
    available: true,
    customizations: [{ name: 'Add Chocolate Sauce Drizzle', price: 20 }]
  },
  {
    id: 'bakery-dish-p2',
    name: 'Fresh Pineapple Cream Slice Pastry',
    category: 'desserts',
    shopSlug: 'giri-bakery',
    shopName: 'Giri Bakery',
    price: 150,
    description: 'Fluffy vanilla sponge layered with juicy crushed pineapple chunks and light whipped cream.',
    image: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?w=800&auto=format&fit=crop&q=85&v=bakery-dish-p2',
    dietary: ['veg'],
    prepTime: 5,
    available: true,
    customizations: [{ name: 'Extra Pineapple Chunks', price: 20 }]
  },
  {
    id: 'bakery-dish-p3',
    name: 'Red Velvet Cream Cheese Pastry Slice',
    category: 'desserts',
    shopSlug: 'giri-bakery',
    shopName: 'Giri Bakery',
    price: 190,
    description: 'Moist crimson red velvet pastry with tangy Philadelphia cream cheese frosting.',
    image: 'https://images.unsplash.com/photo-1616541823729-00fe0aacd32c?w=800&auto=format&fit=crop&q=85&v=bakery-dish-p3',
    dietary: ['veg'],
    prepTime: 5,
    available: true,
    customizations: [{ name: 'Extra Cream Cheese', price: 25 }]
  },
  {
    id: 'bakery-dish-p4',
    name: 'Classic Black Forest Cherry Pastry',
    category: 'desserts',
    shopSlug: 'giri-bakery',
    shopName: 'Giri Bakery',
    price: 160,
    description: 'Traditional chocolate pastry with dark cherries, fresh whipped cream, and chocolate flakes.',
    image: 'https://images.unsplash.com/photo-1606890737304-57a1ca8a5b62?w=800&auto=format&fit=crop&q=85&v=bakery-dish-p4',
    dietary: ['veg'],
    prepTime: 5,
    available: true,
    customizations: [{ name: 'Extra Cherry topping', price: 15 }]
  },
  {
    id: 'bakery-dish-p5',
    name: 'Golden Butterscotch Crunch Pastry',
    category: 'desserts',
    shopSlug: 'giri-bakery',
    shopName: 'Giri Bakery',
    price: 170,
    description: 'Vanilla sponge pastry layered with butterscotch cream and crunchy caramelized praline nuts.',
    image: 'https://images.unsplash.com/photo-1587314168485-3236d6710814?w=800&auto=format&fit=crop&q=85&v=bakery-dish-p5',
    dietary: ['veg'],
    prepTime: 5,
    available: true,
    customizations: [{ name: 'Extra Butterscotch Praline', price: 20 }]
  },
  {
    id: 'bakery-dish-p6',
    name: 'Fresh Mixed Fruit Glazed Pastry',
    category: 'desserts',
    shopSlug: 'giri-bakery',
    shopName: 'Giri Bakery',
    price: 175,
    description: 'Light vanilla pastry crowned with fresh seasonal strawberries, kiwi, and glazed peaches.',
    image: 'https://images.unsplash.com/photo-1565958011703-44f9829ba187?w=800&auto=format&fit=crop&q=85&v=bakery-dish-p6',
    dietary: ['veg'],
    prepTime: 5,
    available: true,
    customizations: [{ name: 'Extra Fruit Glaze', price: 20 }]
  },

  // 3. BREADS (White, Brown, Multigrain, Milk, Garlic, Sandwich, Baguette)
  {
    id: 'bakery-dish-b1',
    name: 'Classic White Sandwich Bread Loaf',
    category: 'starters',
    shopSlug: 'giri-bakery',
    shopName: 'Giri Bakery',
    price: 80,
    description: 'Pillow-soft sliced white sandwich bread loaf baked fresh daily in-house.',
    image: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=800&auto=format&fit=crop&q=85&v=bakery-dish-b1',
    dietary: ['veg'],
    prepTime: 3,
    available: true,
    customizations: [{ name: 'Thick Slice Slicing', price: 0 }]
  },
  {
    id: 'bakery-dish-b2',
    name: '100% Whole Wheat Brown Bread Loaf',
    category: 'starters',
    shopSlug: 'giri-bakery',
    shopName: 'Giri Bakery',
    price: 100,
    description: 'High-fiber whole wheat brown bread baked without maida or artificial colors.',
    image: 'https://images.unsplash.com/photo-1589367920969-ab8e050bbb04?w=800&auto=format&fit=crop&q=85&v=bakery-dish-b2',
    dietary: ['veg'],
    prepTime: 3,
    available: true,
    customizations: [{ name: 'Side Butter Portion', price: 15 }]
  },
  {
    id: 'bakery-dish-b3',
    name: '7-Grain Multigrain Health Bread Loaf',
    category: 'starters',
    shopSlug: 'giri-bakery',
    shopName: 'Giri Bakery',
    price: 120,
    description: 'Nutritious multigrain loaf loaded with flaxseeds, sunflower seeds, oats, and sesame.',
    image: 'https://images.unsplash.com/photo-1549931319-a545dcf3bc73?w=800&auto=format&fit=crop&q=85&v=bakery-dish-b3',
    dietary: ['veg'],
    prepTime: 3,
    available: true,
    customizations: [{ name: 'Toast & Herb Butter', price: 20 }]
  },
  {
    id: 'bakery-dish-b4',
    name: 'Fresh Dairy Milk Bread Loaf',
    category: 'starters',
    shopSlug: 'giri-bakery',
    shopName: 'Giri Bakery',
    price: 90,
    description: 'Slightly sweet, extra soft milk bread loaf baked with whole cream milk & butter.',
    image: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=800&auto=format&fit=crop&q=85&v=bakery-dish-b4',
    dietary: ['veg'],
    prepTime: 3,
    available: true,
    customizations: [{ name: 'Side Jam Tub', price: 15 }]
  },
  {
    id: 'bakery-dish-b5',
    name: 'Crispy Roasted Garlic Butter Bread (4pcs)',
    category: 'starters',
    shopSlug: 'giri-bakery',
    shopName: 'Giri Bakery',
    price: 160,
    description: 'Thick sliced bakery loaf roasted with fresh garlic butter, herbs, and melted mozzarella.',
    image: 'https://images.unsplash.com/photo-1573140247632-f8fd74997d5c?w=800&auto=format&fit=crop&q=85&v=bakery-dish-b5',
    dietary: ['veg'],
    prepTime: 6,
    available: true,
    customizations: [{ name: 'Extra Mozzarella Cheese', price: 30 }]
  },
  {
    id: 'bakery-dish-b6',
    name: 'French Crusty Sourdough Baguette',
    category: 'starters',
    shopSlug: 'giri-bakery',
    shopName: 'Giri Bakery',
    price: 140,
    description: 'Traditional French long baguette bread with golden crispy crust and airy chewy interior.',
    image: 'https://images.unsplash.com/photo-1555507036-ab1f4038808a?w=800&auto=format&fit=crop&q=85&v=bakery-dish-b6',
    dietary: ['veg'],
    prepTime: 4,
    available: true,
    customizations: [{ name: 'Sliced Baguette Option', price: 0 }]
  },

  // 4. COOKIES (Butter, Chocolate Chip, Coconut, Almond, Cashew, Oatmeal, Jeera)
  {
    id: 'bakery-dish-k1',
    name: 'Desi Ghee Rich Butter Cookies (250g Box)',
    category: 'desserts',
    shopSlug: 'giri-bakery',
    shopName: 'Giri Bakery',
    price: 220,
    description: 'Melt-in-your-mouth golden butter cookies baked with pure cows ghee and cardamom.',
    image: 'https://images.unsplash.com/photo-1499636136210-6f4ee915583e?w=800&auto=format&fit=crop&q=85&v=bakery-dish-k1',
    dietary: ['veg'],
    prepTime: 2,
    available: true,
    customizations: [{ name: 'Gift Box Wrapping', price: 15 }]
  },
  {
    id: 'bakery-dish-k2',
    name: 'Belgian Dark Chocolate Chip Cookies (4pcs)',
    category: 'desserts',
    shopSlug: 'giri-bakery',
    shopName: 'Giri Bakery',
    price: 190,
    description: 'Crispy outer edge with soft chewy center loaded with dark Belgian chocolate chips.',
    image: 'https://images.unsplash.com/photo-1558961363-fa8fdf82db35?w=800&auto=format&fit=crop&q=85&v=bakery-dish-k2',
    dietary: ['veg'],
    prepTime: 2,
    available: true,
    customizations: [{ name: 'Warm Cookie Service', price: 10 }]
  },
  {
    id: 'bakery-dish-k3',
    name: 'Toasted Coconut Flake Cookies (200g Box)',
    category: 'desserts',
    shopSlug: 'giri-bakery',
    shopName: 'Giri Bakery',
    price: 210,
    description: 'Fragrant butter cookies infused with toasted shredded coconut flakes.',
    image: 'https://images.unsplash.com/photo-1569864358642-9d1684040f43?w=800&auto=format&fit=crop&q=85&v=bakery-dish-k3',
    dietary: ['veg'],
    prepTime: 2,
    available: true,
    customizations: [{ name: 'Extra Coconut Dusting', price: 15 }]
  },
  {
    id: 'bakery-dish-k4',
    name: 'Roasted Almond Crunchy Biscotti Cookies',
    category: 'desserts',
    shopSlug: 'giri-bakery',
    shopName: 'Giri Bakery',
    price: 240,
    description: 'Twice-baked Italian style crisp cookies studded with whole roasted Californian almonds.',
    image: 'https://images.unsplash.com/photo-1558961363-fa8fdf82db35?w=800&auto=format&fit=crop&q=85&v=bakery-dish-k4',
    dietary: ['veg'],
    prepTime: 2,
    available: true,
    customizations: [{ name: 'Dip in Warm Milk', price: 10 }]
  },
  {
    id: 'bakery-dish-k5',
    name: 'Golden Cashew Butter Cookies Box',
    category: 'desserts',
    shopSlug: 'giri-bakery',
    shopName: 'Giri Bakery',
    price: 230,
    description: 'Rich buttery shortbread cookies topped with halved roasted cashew nuts.',
    image: 'https://images.unsplash.com/photo-1499636136210-6f4ee915583e?w=800&auto=format&fit=crop&q=85&v=bakery-dish-k5',
    dietary: ['veg'],
    prepTime: 2,
    available: true,
    customizations: [{ name: 'Extra Cashew Topping', price: 20 }]
  },
  {
    id: 'bakery-dish-k6',
    name: 'Honey Oatmeal Raisin Health Cookies',
    category: 'desserts',
    shopSlug: 'giri-bakery',
    shopName: 'Giri Bakery',
    price: 195,
    description: 'Chewy high-fiber oatmeal cookies baked with organic honey and sweet raisins.',
    image: 'https://images.unsplash.com/photo-1558961363-fa8fdf82db35?w=800&auto=format&fit=crop&q=85&v=bakery-dish-k6',
    dietary: ['veg'],
    prepTime: 2,
    available: true,
    customizations: [{ name: 'Extra Raisins', price: 15 }]
  },
  {
    id: 'bakery-dish-k7',
    name: 'Savory Cumin Jeera Butter Cookies Box',
    category: 'desserts',
    shopSlug: 'giri-bakery',
    shopName: 'Giri Bakery',
    price: 180,
    description: 'Classic sweet & salty tea-time bakery cookies tempered with toasted cumin seeds.',
    image: 'https://images.unsplash.com/photo-1499636136210-6f4ee915583e?w=800&auto=format&fit=crop&q=85&v=bakery-dish-k7',
    dietary: ['veg'],
    prepTime: 2,
    available: true,
    customizations: [{ name: 'Pair with Hot Masala Chai', price: 30 }]
  },

  // 5. BISCUITS (Cream, Salt, Digestive, Milk, Coconut, Cashew)
  {
    id: 'bakery-dish-x1',
    name: 'Double Chocolate Cream Biscuits Box',
    category: 'desserts',
    shopSlug: 'giri-bakery',
    shopName: 'Giri Bakery',
    price: 160,
    description: 'Crispy dark cocoa biscuit sandwiches filled with smooth vanilla cream.',
    image: 'https://images.unsplash.com/photo-1558961363-fa8fdf82db35?w=800&auto=format&fit=crop&q=85&v=bakery-dish-x1',
    dietary: ['veg'],
    prepTime: 2,
    available: true,
    customizations: [{ name: 'Extra Cream Filling', price: 15 }]
  },
  {
    id: 'bakery-dish-x2',
    name: 'Crispy Salted Butter Puff Biscuits',
    category: 'desserts',
    shopSlug: 'giri-bakery',
    shopName: 'Giri Bakery',
    price: 140,
    description: 'Flaky light salted butter biscuits perfect for dipping into hot chai.',
    image: 'https://images.unsplash.com/photo-1499636136210-6f4ee915583e?w=800&auto=format&fit=crop&q=85&v=bakery-dish-x2',
    dietary: ['veg'],
    prepTime: 2,
    available: true,
    customizations: [{ name: 'Pair with Cutting Chai', price: 25 }]
  },
  {
    id: 'bakery-dish-x3',
    name: 'High-Fiber Whole Wheat Digestive Biscuits',
    category: 'desserts',
    shopSlug: 'giri-bakery',
    shopName: 'Giri Bakery',
    price: 150,
    description: 'Whole wheat & oat digestive biscuits baked crisp for healthy guilt-free snacking.',
    image: 'https://images.unsplash.com/photo-1558961363-fa8fdf82db35?w=800&auto=format&fit=crop&q=85&v=bakery-dish-x3',
    dietary: ['veg'],
    prepTime: 2,
    available: true,
    customizations: [{ name: 'Side Green Tea Bag', price: 20 }]
  },

  // 6. MUFFINS (Chocolate, Blueberry, Vanilla, Banana, Red Velvet)
  {
    id: 'bakery-dish-m1',
    name: 'Molten Belgian Chocolate Chip Muffin',
    category: 'desserts',
    shopSlug: 'giri-bakery',
    shopName: 'Giri Bakery',
    price: 180,
    description: 'Moist chocolate muffin with molten chocolate fudge core and dark chocolate chips.',
    image: 'https://images.unsplash.com/photo-1607958996333-41aef7caefaa?w=800&auto=format&fit=crop&q=85&v=bakery-dish-m1',
    dietary: ['veg'],
    prepTime: 4,
    available: true,
    customizations: [{ name: 'Warm Lava Heating', price: 10 }]
  },
  {
    id: 'bakery-dish-m2',
    name: 'Fresh Blueberry Streusel Vanilla Muffin',
    category: 'desserts',
    shopSlug: 'giri-bakery',
    shopName: 'Giri Bakery',
    price: 190,
    description: 'Fluffy vanilla muffin bursting with wild blueberries and butter crumble streusel.',
    image: 'https://images.unsplash.com/photo-1586985289688-ca3cf47d3e6e?w=800&auto=format&fit=crop&q=85&v=bakery-dish-m2',
    dietary: ['veg'],
    prepTime: 4,
    available: true,
    customizations: [{ name: 'Extra Blueberry Jam Side', price: 20 }]
  },
  {
    id: 'bakery-dish-m3',
    name: 'Madagascar Vanilla Bean Classic Muffin',
    category: 'desserts',
    shopSlug: 'giri-bakery',
    shopName: 'Giri Bakery',
    price: 160,
    description: 'Golden fluffy muffin baked with natural Madagascar vanilla bean extract.',
    image: 'https://images.unsplash.com/photo-1607958996333-41aef7caefaa?w=800&auto=format&fit=crop&q=85&v=bakery-dish-m3',
    dietary: ['veg'],
    prepTime: 4,
    available: true,
    customizations: [{ name: 'Add Chocolate Drizzle', price: 15 }]
  },
  {
    id: 'bakery-dish-m4',
    name: 'Ripe Banana Walnut Spice Muffin',
    category: 'desserts',
    shopSlug: 'giri-bakery',
    shopName: 'Giri Bakery',
    price: 170,
    description: 'Moist banana muffin baked with cinnamon spice and toasted crunchy walnut bits.',
    image: 'https://images.unsplash.com/photo-1586985289688-ca3cf47d3e6e?w=800&auto=format&fit=crop&q=85&v=bakery-dish-m4',
    dietary: ['veg'],
    prepTime: 4,
    available: true,
    customizations: [{ name: 'Extra Toasted Walnuts', price: 20 }]
  },
  {
    id: 'bakery-dish-m5',
    name: 'Red Velvet Cream Cheese Center Muffin',
    category: 'desserts',
    shopSlug: 'giri-bakery',
    shopName: 'Giri Bakery',
    price: 195,
    description: 'Crimson cocoa velvet muffin filled with sweet cream cheese lava center.',
    image: 'https://images.unsplash.com/photo-1607958996333-41aef7caefaa?w=800&auto=format&fit=crop&q=85&v=bakery-dish-m5',
    dietary: ['veg'],
    prepTime: 4,
    available: true,
    customizations: [{ name: 'Extra Cream Cheese', price: 25 }]
  },

  // 7. DONUTS (Chocolate, Glazed, Strawberry, Cinnamon, Cream-Filled)
  {
    id: 'bakery-dish-d1',
    name: 'Glazed Belgian Chocolate Ring Donut (2pcs)',
    category: 'desserts',
    shopSlug: 'giri-bakery',
    shopName: 'Giri Bakery',
    price: 170,
    description: 'Fluffy fried ring donut dipped in dark Belgian chocolate glaze & colorful sprinkles.',
    image: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?w=800&auto=format&fit=crop&q=85&v=bakery-dish-d1',
    dietary: ['veg'],
    prepTime: 4,
    available: true,
    customizations: [{ name: 'Extra Chocolate Drizzle', price: 20 }]
  },
  {
    id: 'bakery-dish-d2',
    name: 'Classic Sugar Glazed Soft Ring Donut (2pcs)',
    category: 'desserts',
    shopSlug: 'giri-bakery',
    shopName: 'Giri Bakery',
    price: 150,
    description: 'Pillowy yeast-risen ring donuts coated in warm transparent vanilla sugar glaze.',
    image: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?w=800&auto=format&fit=crop&q=85&v=bakery-dish-d2',
    dietary: ['veg'],
    prepTime: 4,
    available: true,
    customizations: [{ name: 'Warm Donut Service', price: 10 }]
  },
  {
    id: 'bakery-dish-d3',
    name: 'Fresh Strawberry Cream Glazed Donut (2pcs)',
    category: 'desserts',
    shopSlug: 'giri-bakery',
    shopName: 'Giri Bakery',
    price: 180,
    description: 'Ring donut dipped in pink strawberry glaze topped with freeze-dried berry dusting.',
    image: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?w=800&auto=format&fit=crop&q=85&v=bakery-dish-d3',
    dietary: ['veg'],
    prepTime: 4,
    available: true,
    customizations: [{ name: 'Extra Strawberry Jam', price: 20 }]
  },
  {
    id: 'bakery-dish-d4',
    name: 'Cinnamon Sugar Dusted Warm Donut (2pcs)',
    category: 'desserts',
    shopSlug: 'giri-bakery',
    shopName: 'Giri Bakery',
    price: 160,
    description: 'Warm freshly fried donuts tossed in aromatic Ceylon cinnamon powder and brown sugar.',
    image: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?w=800&auto=format&fit=crop&q=85&v=bakery-dish-d4',
    dietary: ['veg'],
    prepTime: 4,
    available: true,
    customizations: [{ name: 'Side Caramel Dip', price: 25 }]
  },
  {
    id: 'bakery-dish-d5',
    name: 'Bavarian Vanilla Custard Cream-Filled Donut',
    category: 'desserts',
    shopSlug: 'giri-bakery',
    shopName: 'Giri Bakery',
    price: 195,
    description: 'Round donut stuffed with rich Bavarian vanilla bean custard cream and dusted with powdered sugar.',
    image: 'https://images.unsplash.com/photo-1527515637462-cff94eecc1ac?w=800&auto=format&fit=crop&q=85&v=bakery-dish-d5',
    dietary: ['veg'],
    prepTime: 4,
    available: true,
    customizations: [{ name: 'Extra Custard Filling', price: 25 }]
  },

  // 8. BROWNIES (Chocolate, Walnut, Fudge, Nutella, Double Chocolate)
  {
    id: 'bakery-dish-w1',
    name: 'Fudgy Dark Chocolate Walnut Brownie',
    category: 'desserts',
    shopSlug: 'giri-bakery',
    shopName: 'Giri Bakery',
    price: 210,
    description: 'Dense chewy cocoa brownie with shiny papery top crust and toasted crunchy walnuts.',
    image: 'https://images.unsplash.com/photo-1606313564200-e75d5e30476c?w=800&auto=format&fit=crop&q=85&v=bakery-dish-w1',
    dietary: ['veg'],
    prepTime: 5,
    available: true,
    customizations: [{ name: 'Add Vanilla Ice Cream Scoop', price: 50 }]
  },
  {
    id: 'bakery-dish-w2',
    name: 'Nutella Hazelnut Double Chocolate Brownie',
    category: 'desserts',
    shopSlug: 'giri-bakery',
    shopName: 'Giri Bakery',
    price: 240,
    description: 'Molten chocolate brownie layered with Nutella hazelnut spread and chocolate chunks.',
    image: 'https://images.unsplash.com/photo-1564355808539-22fda35bed7e?w=800&auto=format&fit=crop&q=85&v=bakery-dish-w2',
    dietary: ['veg', 'chef-special'],
    prepTime: 5,
    available: true,
    customizations: [{ name: 'Hot Fudge Sauce Drizzle', price: 30 }]
  },

  // 9. PUFFS & SAVORIES (Veg, Paneer, Egg, Chicken, Mushroom, Cheese, Potato)
  {
    id: 'bakery-dish-f1',
    name: 'Spicy Masala Potato Veg Puff (2pcs)',
    category: 'starters',
    shopSlug: 'giri-bakery',
    shopName: 'Giri Bakery',
    price: 130,
    description: 'Golden flaky puff pastry turnover filled with seasoned potatoes, peas, and green chilies.',
    image: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?w=800&auto=format&fit=crop&q=85&v=bakery-dish-f1',
    dietary: ['veg', 'spicy'],
    prepTime: 6,
    available: true,
    customizations: [{ name: 'Mint Chutney Portion', price: 15 }]
  },
  {
    id: 'bakery-dish-f2',
    name: 'Tandoori Paneer Cottage Cheese Puff (2pcs)',
    category: 'starters',
    shopSlug: 'giri-bakery',
    shopName: 'Giri Bakery',
    price: 160,
    description: 'Flaky puff stuffed with spiced chargrilled tandoori paneer cubes & fried capsicum.',
    image: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=800&auto=format&fit=crop&q=85&v=bakery-dish-f2',
    dietary: ['veg', 'spicy'],
    prepTime: 6,
    available: true,
    customizations: [{ name: 'Extra Hot Garlic Dip', price: 20 }]
  },
  {
    id: 'bakery-dish-f3',
    name: 'Boiled Egg Masala Flaky Puff (2pcs)',
    category: 'starters',
    shopSlug: 'giri-bakery',
    shopName: 'Giri Bakery',
    price: 150,
    description: 'Golden layered puff turnover containing hard-boiled egg halves cooked in spicy onion gravy.',
    image: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?w=800&auto=format&fit=crop&q=85&v=bakery-dish-f3',
    dietary: ['non-veg', 'spicy'],
    prepTime: 6,
    available: true,
    customizations: [{ name: 'Side Tomato Ketchup', price: 10 }]
  },
  {
    id: 'bakery-dish-f4',
    name: 'Black Pepper Chicken Minced Puff (2pcs)',
    category: 'starters',
    shopSlug: 'giri-bakery',
    shopName: 'Giri Bakery',
    price: 180,
    description: 'Crispy layered puff filled with minced chicken, black pepper, and fried onions.',
    image: 'https://images.unsplash.com/photo-1626074353765-517a681e40be?w=800&auto=format&fit=crop&q=85&v=bakery-dish-f4',
    dietary: ['non-veg', 'spicy'],
    prepTime: 6,
    available: true,
    customizations: [{ name: 'Hot Garlic Ketchup Dip', price: 20 }]
  },

  // 10. ROLLS & SANDWICHES (Veg Roll, Paneer Roll, Chicken Roll, Veg Sandwich, Cheese Sandwich, Chicken Sandwich)
  {
    id: 'bakery-dish-r1',
    name: 'Gourmet Veg Kathi Roll with Mint Mayo',
    category: 'starters',
    shopSlug: 'giri-bakery',
    shopName: 'Giri Bakery',
    price: 170,
    description: 'Soft flaky paratha roll filled with spiced mixed vegetables, onions, and mint mayo.',
    image: 'https://images.unsplash.com/photo-1528735602780-2552fd46c7af?w=800&auto=format&fit=crop&q=85&v=bakery-dish-r1',
    dietary: ['veg'],
    prepTime: 8,
    available: true,
    customizations: [{ name: 'Add Melted Cheese', price: 25 }]
  },
  {
    id: 'bakery-dish-r2',
    name: 'Tandoori Paneer Tikka Wrap Roll',
    category: 'starters',
    shopSlug: 'giri-bakery',
    shopName: 'Giri Bakery',
    price: 210,
    description: 'Chargrilled paneer tikka cubes wrapped in a warm butter parotta with green chutney.',
    image: 'https://images.unsplash.com/photo-1528735602780-2552fd46c7af?w=800&auto=format&fit=crop&q=85&v=bakery-dish-r2',
    dietary: ['veg', 'spicy'],
    prepTime: 8,
    available: true,
    customizations: [{ name: 'Extra Mint Chutney', price: 15 }]
  },
  {
    id: 'bakery-dish-r3',
    name: 'Smoked Chicken Tikka Franky Roll',
    category: 'starters',
    shopSlug: 'giri-bakery',
    shopName: 'Giri Bakery',
    price: 240,
    description: 'Layered paratha stuffed with juicy chicken tikka, pickled onions, and spicy mayo.',
    image: 'https://images.unsplash.com/photo-1550547660-d9450f859349?w=800&auto=format&fit=crop&q=85&v=bakery-dish-r3',
    dietary: ['non-veg', 'spicy'],
    prepTime: 8,
    available: true,
    customizations: [{ name: 'Extra Spicy Mayo Dip', price: 20 }]
  },
  {
    id: 'bakery-dish-r4',
    name: 'Garden Fresh Club Veg Toast Sandwich',
    category: 'starters',
    shopSlug: 'giri-bakery',
    shopName: 'Giri Bakery',
    price: 180,
    description: 'Triple-decker toasted bread filled with cucumber, tomato, beetroot, boiled potato, and mint chutney.',
    image: 'https://images.unsplash.com/photo-1528735602780-2552fd46c7af?w=800&auto=format&fit=crop&q=85&v=bakery-dish-r4',
    dietary: ['veg'],
    prepTime: 8,
    available: true,
    customizations: [{ name: 'Add Potato Wafers', price: 20 }]
  },
  {
    id: 'bakery-dish-r5',
    name: 'Melting Cheddar Cheese Corn Toast Sandwich',
    category: 'starters',
    shopSlug: 'giri-bakery',
    shopName: 'Giri Bakery',
    price: 200,
    description: 'Golden toasted bread stuffed with sweet corn kernels, jalapenos, and gooey melted cheddar.',
    image: 'https://images.unsplash.com/photo-1528735602780-2552fd46c7af?w=800&auto=format&fit=crop&q=85&v=bakery-dish-r5',
    dietary: ['veg'],
    prepTime: 8,
    available: true,
    customizations: [{ name: 'Extra Cheddar Cheese', price: 30 }]
  },
  {
    id: 'bakery-dish-r6',
    name: 'Smoked Chicken Herb Mayo Toast Sandwich',
    category: 'starters',
    shopSlug: 'giri-bakery',
    shopName: 'Giri Bakery',
    price: 250,
    description: 'Toasted artisan bread loaded with shredded smoked chicken breast, herbs, and dijon mayo.',
    image: 'https://images.unsplash.com/photo-1550547660-d9450f859349?w=800&auto=format&fit=crop&q=85&v=bakery-dish-r6',
    dietary: ['non-veg'],
    prepTime: 8,
    available: true,
    customizations: [{ name: 'Extra Chicken Stuffing', price: 40 }]
  },

  // 11. DESSERTS (Chocolate Tart, Fruit Tart, Éclair, Macaron, Tiramisu, Pudding, Mousse)
  {
    id: 'bakery-dish-e1',
    name: 'Dark Chocolate Ganache Tart',
    category: 'desserts',
    shopSlug: 'giri-bakery',
    shopName: 'Giri Bakery',
    price: 220,
    description: 'Crispy buttery pastry shell filled with silky smooth Belgian dark chocolate ganache.',
    image: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=800&auto=format&fit=crop&q=85&v=bakery-dish-e1',
    dietary: ['veg'],
    prepTime: 4,
    available: true,
    customizations: [{ name: 'Extra Chocolate Drizzle', price: 20 }]
  },
  {
    id: 'bakery-dish-e2',
    name: 'Fresh Exotic Berry Fruit Tart',
    category: 'desserts',
    shopSlug: 'giri-bakery',
    shopName: 'Giri Bakery',
    price: 240,
    description: 'Sweet pastry tart shell filled with vanilla pastry cream and fresh strawberries, blueberries, & kiwi.',
    image: 'https://images.unsplash.com/photo-1565958011703-44f9829ba187?w=800&auto=format&fit=crop&q=85&v=bakery-dish-e2',
    dietary: ['veg'],
    prepTime: 4,
    available: true,
    customizations: [{ name: 'Extra Fresh Berries', price: 35 }]
  },
  {
    id: 'bakery-dish-e3',
    name: 'French Chocolate Custard Éclair (2pcs)',
    category: 'desserts',
    shopSlug: 'giri-bakery',
    shopName: 'Giri Bakery',
    price: 210,
    description: 'Crisp choux pastry logs filled with vanilla cream and topped with shiny chocolate fondant glaze.',
    image: 'https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=800&auto=format&fit=crop&q=85&v=bakery-dish-e3',
    dietary: ['veg'],
    prepTime: 4,
    available: true,
    customizations: [{ name: 'Extra Chocolate Glaze', price: 20 }]
  },
  {
    id: 'bakery-dish-e4',
    name: 'Assorted French Macarons Gift Box (6pcs)',
    category: 'desserts',
    shopSlug: 'giri-bakery',
    shopName: 'Giri Bakery',
    price: 380,
    description: 'Delicate almond meringue shells filled with dark chocolate ganache, pistachio, and raspberry jam.',
    image: 'https://images.unsplash.com/photo-1569864358642-9d1684040f43?w=800&auto=format&fit=crop&q=85&v=bakery-dish-e4',
    dietary: ['veg', 'chef-special'],
    prepTime: 4,
    available: true,
    customizations: [{ name: 'Gift Box Ribbon Wrapping', price: 20 }]
  },

  // 12. INDIAN SWEETS (Gulab Jamun, Rasmalai, Kaju Katli, Motichoor Laddu, Mysore Pak, Badusha)
  {
    id: 'bakery-dish-s1',
    name: 'Desi Ghee Hot Gulab Jamun Bowl (4pcs)',
    category: 'desserts',
    shopSlug: 'giri-bakery',
    shopName: 'Giri Bakery',
    price: 190,
    description: 'Soft golden fried khoya dumplings soaked in warm rose cardamom sugar syrup.',
    image: 'https://images.unsplash.com/photo-1541832676-9b763b0239ab?w=800&auto=format&fit=crop&q=85&v=bakery-dish-s1',
    dietary: ['veg'],
    prepTime: 4,
    available: true,
    customizations: [{ name: 'Add Vanilla Ice Cream Scoop', price: 45 }]
  },
  {
    id: 'bakery-dish-s2',
    name: 'Royal Saffron Kesar Rasmalai Bowl (4pcs)',
    category: 'desserts',
    shopSlug: 'giri-bakery',
    shopName: 'Giri Bakery',
    price: 240,
    description: 'Soft cottage cheese patties immersed in chilled saffron infused rabri with sliced almonds.',
    image: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?w=800&auto=format&fit=crop&q=85&v=bakery-dish-s2',
    dietary: ['veg', 'chef-special'],
    prepTime: 4,
    available: true,
    customizations: [{ name: 'Extra Saffron Milk Drizzle', price: 30 }]
  },
  {
    id: 'bakery-dish-s3',
    name: 'Pure Kaju Katli Diamond Sweets Box (250g)',
    category: 'desserts',
    shopSlug: 'giri-bakery',
    shopName: 'Giri Bakery',
    price: 350,
    description: 'Traditional diamond-shaped cashew fudge sweets made with premium cashews and silver vark.',
    image: 'https://images.unsplash.com/photo-1541832676-9b763b0239ab?w=800&auto=format&fit=crop&q=85&v=bakery-dish-s3',
    dietary: ['veg'],
    prepTime: 2,
    available: true,
    customizations: [{ name: 'Gift Box Packaging', price: 20 }]
  },
  {
    id: 'bakery-dish-s4',
    name: 'Desi Ghee Motichoor Laddu Box (250g)',
    category: 'desserts',
    shopSlug: 'giri-bakery',
    shopName: 'Giri Bakery',
    price: 280,
    description: 'Melt-in-mouth golden boondi laddus cooked in pure cows ghee with saffron & melon seeds.',
    image: 'https://images.unsplash.com/photo-1541832676-9b763b0239ab?w=800&auto=format&fit=crop&q=85&v=bakery-dish-s4',
    dietary: ['veg'],
    prepTime: 2,
    available: true,
    customizations: [{ name: 'Extra Pistachio Topping', price: 25 }]
  },

  // 13. ICE CREAM & FROZEN (Vanilla, Chocolate, Strawberry, Butterscotch, Brownie Sundae)
  {
    id: 'bakery-dish-i1',
    name: 'Belgian Chocolate & Vanilla Sundae Glass',
    category: 'desserts',
    shopSlug: 'giri-bakery',
    shopName: 'Giri Bakery',
    price: 230,
    description: 'Double scoops of dark chocolate & Madagascar vanilla ice cream topped with hot fudge, whipped cream, and cherries.',
    image: 'https://images.unsplash.com/photo-1563805042-7684c019e1cb?w=800&auto=format&fit=crop&q=85&v=bakery-dish-i1',
    dietary: ['veg'],
    prepTime: 4,
    available: true,
    customizations: [{ name: 'Extra Hot Fudge Portion', price: 30 }]
  },
  {
    id: 'bakery-dish-i2',
    name: 'Warm Fudgy Brownie Ice Cream Sundae',
    category: 'desserts',
    shopSlug: 'giri-bakery',
    shopName: 'Giri Bakery',
    price: 260,
    description: 'Warm dark chocolate walnut brownie served with vanilla ice cream scoop, hot chocolate syrup & roasted nuts.',
    image: 'https://images.unsplash.com/photo-1563805042-7684c019e1cb?w=800&auto=format&fit=crop&q=85&v=bakery-dish-i2',
    dietary: ['veg', 'chef-special'],
    prepTime: 5,
    available: true,
    customizations: [{ name: 'Extra Scoop Vanilla Ice Cream', price: 45 }]
  },

  // 14. BEVERAGES (Cold Coffee, Hot Chocolate, Cappuccino, Latte, Espresso, Masala Tea, Fresh Juice, Milkshake)
  {
    id: 'bakery-dish-v1',
    name: 'Rich Creamy Iced Cold Coffee with Ice Cream',
    category: 'drinks',
    shopSlug: 'giri-bakery',
    shopName: 'Giri Bakery',
    price: 190,
    description: 'Blended espresso with chilled milk, dark cocoa, topped with vanilla scoop & chocolate drizzle.',
    image: 'https://images.unsplash.com/photo-1517701604599-bb29b565090c?w=800&auto=format&fit=crop&q=85&v=bakery-dish-v1',
    dietary: ['veg'],
    prepTime: 5,
    available: true,
    customizations: [{ name: 'Add Whipped Cream Top', price: 25 }]
  },
  {
    id: 'bakery-dish-v2',
    name: 'Gourmet Hot Chocolate with Marshmallows',
    category: 'drinks',
    shopSlug: 'giri-bakery',
    shopName: 'Giri Bakery',
    price: 210,
    description: 'Steaming hot Dutch dark chocolate drink crowned with mini toasted fluffy marshmallows.',
    image: 'https://images.unsplash.com/photo-1542990253-0d0f5be5f0ed?w=800&auto=format&fit=crop&q=85&v=bakery-dish-v2',
    dietary: ['veg'],
    prepTime: 5,
    available: true,
    customizations: [{ name: 'Extra Marshmallows', price: 20 }]
  },
  {
    id: 'bakery-dish-v3',
    name: 'Italian Frothy Cappuccino Coffee Cup',
    category: 'drinks',
    shopSlug: 'giri-bakery',
    shopName: 'Giri Bakery',
    price: 160,
    description: 'Rich espresso shot with steamed milk foam and cocoa dusting.',
    image: 'https://images.unsplash.com/photo-1517701604599-bb29b565090c?w=800&auto=format&fit=crop&q=85&v=bakery-dish-v3',
    dietary: ['veg'],
    prepTime: 5,
    available: true,
    customizations: [{ name: 'Add Caramel Syrup', price: 25 }]
  },
  {
    id: 'bakery-dish-v4',
    name: 'Artisan Vanilla Milkshake with Whipped Cream',
    category: 'drinks',
    shopSlug: 'giri-bakery',
    shopName: 'Giri Bakery',
    price: 180,
    description: 'Thick chilled vanilla milkshake made with real vanilla beans and topped with cherry.',
    image: 'https://images.unsplash.com/photo-1517701604599-bb29b565090c?w=800&auto=format&fit=crop&q=85&v=bakery-dish-v4',
    dietary: ['veg'],
    prepTime: 5,
    available: true,
    customizations: [{ name: 'Extra Ice Cream Blend', price: 35 }]
  }
`;

// Cleanly replace any bakery items in dishes.ts
const bakeryCode = `export const GIRI_BAKERY_DISHES: MenuItem[] = [\n${completeBakeryCatalog}\n];\n`;

const bakeryIndex = dishesContent.indexOf("export const GIRI_BAKERY_DISHES");
if (bakeryIndex !== -1) {
  const endIndex = dishesContent.indexOf("const RAW_INITIAL_DISHES");
  dishesContent = dishesContent.substring(0, bakeryIndex) + bakeryCode + dishesContent.substring(endIndex);
} else {
  dishesContent = dishesContent.replace(
    "const RAW_INITIAL_DISHES: MenuItem[] = [",
    `${bakeryCode}\nconst RAW_INITIAL_DISHES: MenuItem[] = [\n  ...GIRI_BAKERY_DISHES,`
  );
}

dishesContent = dishesContent.replace(
  /const versionKey = 'giri_dishes_[^']+';/,
  "const versionKey = 'giri_dishes_v33_bakery_all_85_subcategories_completely_populated';"
);

fs.writeFileSync(dishesPath, dishesContent, 'utf8');
console.log('Successfully updated dishes.ts with 85+ authentic Bakery dishes for Giri Bakery!');

