const fs = require('fs');

const dishesPath = 'c:/Users/lenovo/OneDrive/Desktop/resturant/frontend/data/dishes.ts';
let dishesContent = fs.readFileSync(dishesPath, 'utf8');

const completeExpressBistroCatalog = `
  // ==========================================
  // GIRI EXPRESS & BISTRO COMPLETE 115 DISHES
  // ==========================================

  // 1. EXPRESS BREAKFAST
  {
    id: 'dish-eb-eb1',
    name: 'Crispy South Indian Masala Dosa',
    category: 'tiffins',
    shopSlug: 'giri-express-bistro',
    shopName: 'Giri Express & Bistro',
    price: 110,
    description: 'Golden crispy crepe stuffed with spiced potato masala, served with coconut chutney and sambar.',
    image: 'https://images.unsplash.com/photo-1668236543090-82eba5ee5976?w=800&auto=format&fit=crop&q=85&v=dish-eb-eb1',
    dietary: ['veg', 'chef-special'],
    prepTime: 10,
    available: true
  },
  {
    id: 'dish-eb-eb2',
    name: 'Steamed Steaming Soft Idli (3 Pcs)',
    category: 'tiffins',
    shopSlug: 'giri-express-bistro',
    shopName: 'Giri Express & Bistro',
    price: 80,
    description: 'Soft and fluffy steamed rice cakes served with authentic coconut chutney and piping hot sambar.',
    image: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?w=800&auto=format&fit=crop&q=85&v=dish-eb-eb2',
    dietary: ['veg'],
    prepTime: 8,
    available: true
  },
  {
    id: 'dish-eb-eb3',
    name: 'Crunchy Crispy Medu Vada (2 Pcs)',
    category: 'tiffins',
    shopSlug: 'giri-express-bistro',
    shopName: 'Giri Express & Bistro',
    price: 90,
    description: 'Deep-fried lentil doughnut with crispy exterior and fluffy soft core, paired with spicy chutney.',
    image: 'https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?w=800&auto=format&fit=crop&q=85&v=dish-eb-eb3',
    dietary: ['veg'],
    prepTime: 10,
    available: true
  },
  {
    id: 'dish-eb-eb4',
    name: 'Fluffy Poori with Potato Masala',
    category: 'tiffins',
    shopSlug: 'giri-express-bistro',
    shopName: 'Giri Express & Bistro',
    price: 120,
    description: 'Puffed deep-fried wheat breads served with traditional South Indian yellow potato gravy.',
    image: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?w=800&auto=format&fit=crop&q=85&v=dish-eb-eb4',
    dietary: ['veg'],
    prepTime: 12,
    available: true
  },
  {
    id: 'dish-eb-eb5',
    name: 'Homestyle Roasted Rava Upma',
    category: 'tiffins',
    shopSlug: 'giri-express-bistro',
    shopName: 'Giri Express & Bistro',
    price: 85,
    description: 'Savory semolina porridge tempered with mustard seeds, curry leaves, green chilies, and cashews.',
    image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800&auto=format&fit=crop&q=85&v=dish-eb-eb5',
    dietary: ['veg'],
    prepTime: 10,
    available: true
  },
  {
    id: 'dish-eb-eb6',
    name: 'Ghee Ven Pongal with Chutney',
    category: 'tiffins',
    shopSlug: 'giri-express-bistro',
    shopName: 'Giri Express & Bistro',
    price: 100,
    description: 'Warm rice and yellow moong dal cooked with pure desi ghee, black pepper, cumin, and cashews.',
    image: 'https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?w=800&auto=format&fit=crop&q=85&v=dish-eb-eb6',
    dietary: ['veg'],
    prepTime: 10,
    available: true
  },
  {
    id: 'dish-eb-eb7',
    name: 'Street Style Bread Omelette',
    category: 'tiffins',
    shopSlug: 'giri-express-bistro',
    shopName: 'Giri Express & Bistro',
    price: 95,
    description: 'Two fluffy spiced eggs wrapped around buttery toasted artisan bread slices.',
    image: 'https://images.unsplash.com/photo-1525351484163-7529414344d8?w=800&auto=format&fit=crop&q=85&v=dish-eb-eb7',
    dietary: ['non-veg'],
    prepTime: 10,
    available: true
  },

  // 2. QUICK MEALS
  {
    id: 'dish-eb-qm1',
    name: 'Deluxe Veg Quick Meal',
    category: 'mains',
    shopSlug: 'giri-express-bistro',
    shopName: 'Giri Express & Bistro',
    price: 160,
    description: 'Rice, Paneer Butter Masala, Dal Fry, Roti, Salad, Pickle, and Sweet treat.',
    image: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=800&auto=format&fit=crop&q=85&v=dish-eb-qm1',
    dietary: ['veg'],
    prepTime: 15,
    available: true
  },
  {
    id: 'dish-eb-qm2',
    name: 'Traditional South Indian Meal',
    category: 'mains',
    shopSlug: 'giri-express-bistro',
    shopName: 'Giri Express & Bistro',
    price: 170,
    description: 'Steamed Rice, Sambar, Rasam, Poriyal, Curd, Appalam, and Sweet Payasam.',
    image: 'https://images.unsplash.com/photo-1610192244261-3f33de3f55e4?w=800&auto=format&fit=crop&q=85&v=dish-eb-qm2',
    dietary: ['veg', 'chef-special'],
    prepTime: 12,
    available: true
  },
  {
    id: 'dish-eb-qm3',
    name: 'Express Mini Meal Combo',
    category: 'mains',
    shopSlug: 'giri-express-bistro',
    shopName: 'Giri Express & Bistro',
    price: 130,
    description: 'Flavored rice of the day, Chapati (2 pcs), Veg curry, and Curd rice portion.',
    image: 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=800&auto=format&fit=crop&q=85&v=dish-eb-qm3',
    dietary: ['veg'],
    prepTime: 10,
    available: true
  },
  {
    id: 'dish-eb-qm4',
    name: 'Spicy Andhra Thali Meal',
    category: 'mains',
    shopSlug: 'giri-express-bistro',
    shopName: 'Giri Express & Bistro',
    price: 180,
    description: 'Steamed rice, Andhra Pappu, Gutti Vankaya, Majjiga Pulusu, Podi & Ghee.',
    image: 'https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?w=800&auto=format&fit=crop&q=85&v=dish-eb-qm4',
    dietary: ['veg', 'spicy'],
    prepTime: 15,
    available: true
  },
  {
    id: 'dish-eb-qm5',
    name: 'Chicken Curry Quick Meal',
    category: 'mains',
    shopSlug: 'giri-express-bistro',
    shopName: 'Giri Express & Bistro',
    price: 210,
    description: 'Steamed Rice, Spicy Homestyle Chicken Curry, Dal, Butter Roti (2), and Salad.',
    image: 'https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=800&auto=format&fit=crop&q=85&v=dish-eb-qm5',
    dietary: ['non-veg', 'spicy'],
    prepTime: 15,
    available: true
  },
  {
    id: 'dish-eb-qm6',
    name: 'Bistro Executive Feast Meal',
    category: 'mains',
    shopSlug: 'giri-express-bistro',
    shopName: 'Giri Express & Bistro',
    price: 240,
    description: 'Jeera Rice, Butter Chicken / Paneer Gravy, Naan (2), Starter, Salad, Dessert.',
    image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=800&auto=format&fit=crop&q=85&v=dish-eb-qm6',
    dietary: ['chef-special'],
    prepTime: 18,
    available: true
  },

  // 3. RICE & BOWLS
  {
    id: 'dish-eb-rb1',
    name: 'Garden Veg Power Rice Bowl',
    category: 'mains',
    shopSlug: 'giri-express-bistro',
    shopName: 'Giri Express & Bistro',
    price: 150,
    description: 'Seasoned basmati rice topped with sautéed farm vegetables, corn, and fresh herbs.',
    image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800&auto=format&fit=crop&q=85&v=dish-eb-rb1',
    dietary: ['veg'],
    prepTime: 12,
    available: true
  },
  {
    id: 'dish-eb-rb2',
    name: 'Grilled Chicken Tikka Rice Bowl',
    category: 'mains',
    shopSlug: 'giri-express-bistro',
    shopName: 'Giri Express & Bistro',
    price: 195,
    description: 'Smoky chicken tikka chunks over fragrant cilantro jeera rice with makhani drizzle.',
    image: 'https://images.unsplash.com/photo-1543339308-43e59d6b73a6?w=800&auto=format&fit=crop&q=85&v=dish-eb-rb2',
    dietary: ['non-veg', 'chef-special'],
    prepTime: 14,
    available: true
  },
  {
    id: 'dish-eb-rb3',
    name: 'Kadhai Paneer Makhani Rice Bowl',
    category: 'mains',
    shopSlug: 'giri-express-bistro',
    shopName: 'Giri Express & Bistro',
    price: 180,
    description: 'Soft paneer cubes simmered in spiced gravy served over buttered steamed basmati rice.',
    image: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=800&auto=format&fit=crop&q=85&v=dish-eb-rb3',
    dietary: ['veg'],
    prepTime: 12,
    available: true
  },
  {
    id: 'dish-eb-rb4',
    name: 'Spicy Masala Egg Curry Rice Bowl',
    category: 'mains',
    shopSlug: 'giri-express-bistro',
    shopName: 'Giri Express & Bistro',
    price: 165,
    description: 'Hard-boiled roasted eggs in rich onion tomato gravy over fragrant steamed basmati rice.',
    image: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=800&auto=format&fit=crop&q=85&v=dish-eb-rb4',
    dietary: ['non-veg', 'spicy'],
    prepTime: 12,
    available: true
  },
  {
    id: 'dish-eb-rb5',
    name: 'Indo-Chinese Fried Rice Bowl',
    category: 'mains',
    shopSlug: 'giri-express-bistro',
    shopName: 'Giri Express & Bistro',
    price: 160,
    description: 'Wok-tossed long grain rice with soy, garlic, spring onions, and crunchy garden veggies.',
    image: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=800&auto=format&fit=crop&q=85&v=dish-eb-rb5',
    dietary: ['veg'],
    prepTime: 12,
    available: true
  },

  // 4. BIRYANI
  {
    id: 'dish-eb-by1',
    name: 'Hyderabadi Chicken Dum Biryani',
    category: 'biryani',
    shopSlug: 'giri-express-bistro',
    shopName: 'Giri Express & Bistro',
    price: 260,
    description: 'Long grain basmati rice slow-cooked on dum with tender marinated chicken and aromatics.',
    image: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=800&auto=format&fit=crop&q=85&v=dish-eb-by1',
    dietary: ['non-veg', 'chef-special', 'spicy'],
    prepTime: 15,
    available: true
  },
  {
    id: 'dish-eb-by2',
    name: 'Royal Tender Mutton Dum Biryani',
    category: 'biryani',
    shopSlug: 'giri-express-bistro',
    shopName: 'Giri Express & Bistro',
    price: 330,
    description: 'Richly spiced mutton pieces layered with saffron basmati rice, caramelized onions, and mint.',
    image: 'https://images.unsplash.com/photo-1633945274405-b6c8069047b0?w=800&auto=format&fit=crop&q=85&v=dish-eb-by2',
    dietary: ['non-veg', 'spicy'],
    prepTime: 18,
    available: true
  },
  {
    id: 'dish-eb-by3',
    name: 'Double Egg Dum Masala Biryani',
    category: 'biryani',
    shopSlug: 'giri-express-bistro',
    shopName: 'Giri Express & Bistro',
    price: 210,
    description: 'Boiled fried eggs layered with aromatic saffron rice and spicy biryani gravy.',
    image: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=800&auto=format&fit=crop&q=85&v=dish-eb-by3',
    dietary: ['non-veg'],
    prepTime: 14,
    available: true
  },
  {
    id: 'dish-eb-by4',
    name: 'Special Subz Garden Veg Biryani',
    category: 'biryani',
    shopSlug: 'giri-express-bistro',
    shopName: 'Giri Express & Bistro',
    price: 200,
    description: 'Farm fresh vegetables cooked dum style with basmati rice, herbs, and mild Indian spices.',
    image: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=800&auto=format&fit=crop&q=85&v=dish-eb-by4',
    dietary: ['veg'],
    prepTime: 15,
    available: true
  },
  {
    id: 'dish-eb-by5',
    name: 'Zafrani Shahi Paneer Biryani',
    category: 'biryani',
    shopSlug: 'giri-express-bistro',
    shopName: 'Giri Express & Bistro',
    price: 240,
    description: 'Marinated cottage cheese cubes layered with saffron infused basmati rice and roasted cashews.',
    image: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=800&auto=format&fit=crop&q=85&v=dish-eb-by5',
    dietary: ['veg', 'chef-special'],
    prepTime: 15,
    available: true
  },

  // 5. BURGERS
  {
    id: 'dish-eb-bg1',
    name: 'Classic Crispy Veg Herb Burger',
    category: 'fast-food',
    shopSlug: 'giri-express-bistro',
    shopName: 'Giri Express & Bistro',
    price: 125,
    description: 'Golden veg patty topped with crisp lettuce, juicy tomato, pickles, and bistro mayo in a toasted bun.',
    image: 'https://images.unsplash.com/photo-1550547660-d9450f859349?w=800&auto=format&fit=crop&q=85&v=dish-eb-bg1',
    dietary: ['veg'],
    prepTime: 12,
    available: true
  },
  {
    id: 'dish-eb-bg2',
    name: 'Spicy Chargrilled Paneer Burger',
    category: 'fast-food',
    shopSlug: 'giri-express-bistro',
    shopName: 'Giri Express & Bistro',
    price: 155,
    description: 'Thick marinated paneer steak grilled crisp with peri peri mayo and fresh onion rings.',
    image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=800&auto=format&fit=crop&q=85&v=dish-eb-bg2',
    dietary: ['veg', 'spicy'],
    prepTime: 12,
    available: true
  },
  {
    id: 'dish-eb-bg3',
    name: 'Juicy Crunchy Chicken Burger',
    category: 'fast-food',
    shopSlug: 'giri-express-bistro',
    shopName: 'Giri Express & Bistro',
    price: 165,
    description: 'Crispy fried chicken fillet topped with creamy coleslaw, melted cheese, and garlic mayo.',
    image: 'https://images.unsplash.com/photo-1615297928064-24977384d0da?w=800&auto=format&fit=crop&q=85&v=dish-eb-bg3',
    dietary: ['non-veg', 'chef-special'],
    prepTime: 12,
    available: true
  },
  {
    id: 'dish-eb-bg4',
    name: 'Double Loaded Cheese Burger',
    category: 'fast-food',
    shopSlug: 'giri-express-bistro',
    shopName: 'Giri Express & Bistro',
    price: 175,
    description: 'Melted cheddar slices layering a juicy patty with caramelised onions and secret bistro sauce.',
    image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=800&auto=format&fit=crop&q=85&v=dish-eb-bg4',
    dietary: ['veg'],
    prepTime: 12,
    available: true
  },
  {
    id: 'dish-eb-bg5',
    name: 'Smoky BBQ Grilled Chicken Burger',
    category: 'fast-food',
    shopSlug: 'giri-express-bistro',
    shopName: 'Giri Express & Bistro',
    price: 185,
    description: 'Flame-grilled chicken breast brushed with rich hickory BBQ glaze and jalapenos.',
    image: 'https://images.unsplash.com/photo-1586190848861-99aa4a171e90?w=800&auto=format&fit=crop&q=85&v=dish-eb-bg5',
    dietary: ['non-veg'],
    prepTime: 14,
    available: true
  },

  // 6. WRAPS & ROLLS
  {
    id: 'dish-eb-wr1',
    name: 'Tandoori Paneer Tikka Wrap',
    category: 'fast-food',
    shopSlug: 'giri-express-bistro',
    shopName: 'Giri Express & Bistro',
    price: 145,
    description: 'Char-grilled paneer tikka wrapped in a warm tortilla with mint chutney and bell peppers.',
    image: 'https://images.unsplash.com/photo-1626700051175-6818013e1d4f?w=800&auto=format&fit=crop&q=85&v=dish-eb-wr1',
    dietary: ['veg'],
    prepTime: 10,
    available: true
  },
  {
    id: 'dish-eb-wr2',
    name: 'Crispy Garden Veg Roll',
    category: 'fast-food',
    shopSlug: 'giri-express-bistro',
    shopName: 'Giri Express & Bistro',
    price: 120,
    description: 'Crispy fried veg croquettes rolled with shredded cabbage, onions, and sweet chili sauce.',
    image: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=800&auto=format&fit=crop&q=85&v=dish-eb-wr2',
    dietary: ['veg'],
    prepTime: 10,
    available: true
  },
  {
    id: 'dish-eb-wr3',
    name: 'Grilled Spicy Chicken Wrap',
    category: 'fast-food',
    shopSlug: 'giri-express-bistro',
    shopName: 'Giri Express & Bistro',
    price: 165,
    description: 'Juicy spiced chicken strips wrapped with fresh salad greens and garlic chipotle mayo.',
    image: 'https://images.unsplash.com/photo-1626700051175-6818013e1d4f?w=800&auto=format&fit=crop&q=85&v=dish-eb-wr3',
    dietary: ['non-veg'],
    prepTime: 10,
    available: true
  },
  {
    id: 'dish-eb-wr4',
    name: 'Kolkata Style Chicken Kathi Roll',
    category: 'fast-food',
    shopSlug: 'giri-express-bistro',
    shopName: 'Giri Express & Bistro',
    price: 155,
    description: 'Egg-paratha rolled with tender succulent chicken boti, sliced onions, and lime juice.',
    image: 'https://images.unsplash.com/photo-1626700051175-6818013e1d4f?w=800&auto=format&fit=crop&q=85&v=dish-eb-wr4',
    dietary: ['non-veg', 'chef-special'],
    prepTime: 12,
    available: true
  },
  {
    id: 'dish-eb-wr5',
    name: 'Double Egg Masala Kathi Roll',
    category: 'fast-food',
    shopSlug: 'giri-express-bistro',
    shopName: 'Giri Express & Bistro',
    price: 130,
    description: 'Fluffy two-egg omelette layered over crispy paratha with tangy onion slaw.',
    image: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=800&auto=format&fit=crop&q=85&v=dish-eb-wr5',
    dietary: ['non-veg'],
    prepTime: 10,
    available: true
  },
  {
    id: 'dish-eb-wr6',
    name: 'Smoky BBQ Chicken Wrap',
    category: 'fast-food',
    shopSlug: 'giri-express-bistro',
    shopName: 'Giri Express & Bistro',
    price: 175,
    description: 'Pulled BBQ chicken, crunchy bell peppers, corn, and smoked cheese rolled in a warm flatbread.',
    image: 'https://images.unsplash.com/photo-1626700051175-6818013e1d4f?w=800&auto=format&fit=crop&q=85&v=dish-eb-wr6',
    dietary: ['non-veg'],
    prepTime: 12,
    available: true
  },

  // 7. SANDWICHES
  {
    id: 'dish-eb-sw1',
    name: 'Classic Veg Grilled Sandwich',
    category: 'fast-food',
    shopSlug: 'giri-express-bistro',
    shopName: 'Giri Express & Bistro',
    price: 120,
    description: 'Triple layer toasted bread filled with sliced cucumber, tomato, potato, and green chutney.',
    image: 'https://images.unsplash.com/photo-1528735602780-2552fd46c7af?w=800&auto=format&fit=crop&q=85&v=dish-eb-sw1',
    dietary: ['veg'],
    prepTime: 10,
    available: true
  },
  {
    id: 'dish-eb-sw2',
    name: 'Melted Double Cheese Toastie',
    category: 'fast-food',
    shopSlug: 'giri-express-bistro',
    shopName: 'Giri Express & Bistro',
    price: 135,
    description: 'Gooey melted mozzarella and cheddar cheese seasoned with oregano and chili flakes.',
    image: 'https://images.unsplash.com/photo-1528736235302-52922df5c122?w=800&auto=format&fit=crop&q=85&v=dish-eb-sw2',
    dietary: ['veg'],
    prepTime: 8,
    available: true
  },
  {
    id: 'dish-eb-sw3',
    name: 'Spiced Paneer Tikka Mayo Sandwich',
    category: 'fast-food',
    shopSlug: 'giri-express-bistro',
    shopName: 'Giri Express & Bistro',
    price: 150,
    description: 'Grilled cottage cheese cubes mixed with garlic mayo, bell peppers, and herbs.',
    image: 'https://images.unsplash.com/photo-1539252554453-80ab65ce3586?w=800&auto=format&fit=crop&q=85&v=dish-eb-sw3',
    dietary: ['veg'],
    prepTime: 10,
    available: true
  },
  {
    id: 'dish-eb-sw4',
    name: 'Herb Grilled Chicken Sandwich',
    category: 'fast-food',
    shopSlug: 'giri-express-bistro',
    shopName: 'Giri Express & Bistro',
    price: 170,
    description: 'Shredded roasted chicken breast tossed with honey mustard mayo and crispy lettuce.',
    image: 'https://images.unsplash.com/photo-1553909489-cd47e0907980?w=800&auto=format&fit=crop&q=85&v=dish-eb-sw4',
    dietary: ['non-veg', 'chef-special'],
    prepTime: 12,
    available: true
  },
  {
    id: 'dish-eb-sw5',
    name: 'Grand Bistro Club Sandwich',
    category: 'fast-food',
    shopSlug: 'giri-express-bistro',
    shopName: 'Giri Express & Bistro',
    price: 190,
    description: 'Three-tiered artisan toast packed with egg, chicken breast, cheese, tomatoes, and lettuce.',
    image: 'https://images.unsplash.com/photo-1567234669003-dce7a7a88821?w=800&auto=format&fit=crop&q=85&v=dish-eb-sw5',
    dietary: ['non-veg'],
    prepTime: 14,
    available: true
  },

  // 8. PIZZA
  {
    id: 'dish-eb-pz1',
    name: 'Classic Italian Margherita Pizza',
    category: 'pizzas',
    shopSlug: 'giri-express-bistro',
    shopName: 'Giri Express & Bistro',
    price: 240,
    description: 'San Marzano tomato sauce base topped with fresh mozzarella cheese and basil leaves.',
    image: 'https://images.unsplash.com/photo-1604382354936-07c5d9983bd3?w=800&auto=format&fit=crop&q=85&v=dish-eb-pz1',
    dietary: ['veg'],
    prepTime: 15,
    available: true
  },
  {
    id: 'dish-eb-pz2',
    name: 'Garden Farmhouse Veggie Pizza',
    category: 'pizzas',
    shopSlug: 'giri-express-bistro',
    shopName: 'Giri Express & Bistro',
    price: 280,
    description: 'Loaded with capsicum, onion, sweet corn, mushrooms, olives, and extra mozzarella cheese.',
    image: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=800&auto=format&fit=crop&q=85&v=dish-eb-pz2',
    dietary: ['veg'],
    prepTime: 15,
    available: true
  },
  {
    id: 'dish-eb-pz3',
    name: 'Tandoori Paneer Tikka Pizza',
    category: 'pizzas',
    shopSlug: 'giri-express-bistro',
    shopName: 'Giri Express & Bistro',
    price: 310,
    description: 'Spiced cottage cheese cubes, red onions, capsicum, and makhani sauce swirl on hand-tossed crust.',
    image: 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=800&auto=format&fit=crop&q=85&v=dish-eb-pz3',
    dietary: ['veg', 'chef-special'],
    prepTime: 15,
    available: true
  },
  {
    id: 'dish-eb-pz4',
    name: 'Desi Chicken Tikka Pizza',
    category: 'pizzas',
    shopSlug: 'giri-express-bistro',
    shopName: 'Giri Express & Bistro',
    price: 340,
    description: 'Juicy chicken tikka chunks, paprika, onions, and stringy mozzarella on tomato basil sauce.',
    image: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=800&auto=format&fit=crop&q=85&v=dish-eb-pz4',
    dietary: ['non-veg', 'spicy'],
    prepTime: 15,
    available: true
  },
  {
    id: 'dish-eb-pz5',
    name: 'Hickory BBQ Smoked Chicken Pizza',
    category: 'pizzas',
    shopSlug: 'giri-express-bistro',
    shopName: 'Giri Express & Bistro',
    price: 360,
    description: 'Smoky BBQ chicken, jalapenos, sweet red onions, and melted mozzarella cheese.',
    image: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=800&auto=format&fit=crop&q=85&v=dish-eb-pz5',
    dietary: ['non-veg'],
    prepTime: 15,
    available: true
  },

  // 9. PASTA
  {
    id: 'dish-eb-ps1',
    name: 'Creamy White Sauce Alfredo Pasta',
    category: 'italian',
    shopSlug: 'giri-express-bistro',
    shopName: 'Giri Express & Bistro',
    price: 230,
    description: 'Penne pasta tossed in rich velvety parmesan cream sauce with garlic and fresh herbs.',
    image: 'https://images.unsplash.com/photo-1645112411341-6c4fd023714a?w=800&auto=format&fit=crop&q=85&v=dish-eb-ps1',
    dietary: ['veg', 'chef-special'],
    prepTime: 14,
    available: true
  },
  {
    id: 'dish-eb-ps2',
    name: 'Spicy Red Sauce Arrabbiata Pasta',
    category: 'italian',
    shopSlug: 'giri-express-bistro',
    shopName: 'Giri Express & Bistro',
    price: 220,
    description: 'Penne pasta cooked in crushed San Marzano tomato sauce infused with garlic and red chili flakes.',
    image: 'https://images.unsplash.com/photo-1621996346565-e3def646d9a1?w=800&auto=format&fit=crop&q=85&v=dish-eb-ps2',
    dietary: ['veg', 'spicy'],
    prepTime: 14,
    available: true
  },
  {
    id: 'dish-eb-ps3',
    name: 'Fresh Basil Pesto Cream Pasta',
    category: 'italian',
    shopSlug: 'giri-express-bistro',
    shopName: 'Giri Express & Bistro',
    price: 250,
    description: 'Fusilli pasta coated in house-made basil pesto sauce, olive oil, pine nuts, and parmesan.',
    image: 'https://images.unsplash.com/photo-1473093295043-cdd812d0e601?w=800&auto=format&fit=crop&q=85&v=dish-eb-ps3',
    dietary: ['veg'],
    prepTime: 15,
    available: true
  },
  {
    id: 'dish-eb-ps4',
    name: 'Wild Button Mushroom Cream Pasta',
    category: 'italian',
    shopSlug: 'giri-express-bistro',
    shopName: 'Giri Express & Bistro',
    price: 240,
    description: 'Sautéed wild mushrooms and penne pasta bathed in garlicky white wine cream sauce.',
    image: 'https://images.unsplash.com/photo-1551183053-bf91a1d81141?w=800&auto=format&fit=crop&q=85&v=dish-eb-ps4',
    dietary: ['veg'],
    prepTime: 14,
    available: true
  },
  {
    id: 'dish-eb-ps5',
    name: 'Tender Grilled Chicken Penne Pasta',
    category: 'italian',
    shopSlug: 'giri-express-bistro',
    shopName: 'Giri Express & Bistro',
    price: 270,
    description: 'Herb-marinated chicken strips tossed with penne pasta in pink aurora rose sauce.',
    image: 'https://images.unsplash.com/photo-1621996346565-e3def646d9a1?w=800&auto=format&fit=crop&q=85&v=dish-eb-ps5',
    dietary: ['non-veg'],
    prepTime: 15,
    available: true
  },

  // 10. EXPRESS STARTERS
  {
    id: 'dish-eb-st1',
    name: 'Crispy Sweet Corn Salt & Pepper',
    category: 'starters',
    shopSlug: 'giri-express-bistro',
    shopName: 'Giri Express & Bistro',
    price: 150,
    description: 'Crispy fried sweet corn kernels tossed with crushed black pepper, spring onions, and garlic.',
    image: 'https://images.unsplash.com/photo-1551782450-a2132b4ba21d?w=800&auto=format&fit=crop&q=85&v=dish-eb-st1',
    dietary: ['veg'],
    prepTime: 10,
    available: true
  },
  {
    id: 'dish-eb-st2',
    name: 'Spicy Indo-Chinese Gobi 65',
    category: 'starters',
    shopSlug: 'giri-express-bistro',
    shopName: 'Giri Express & Bistro',
    price: 140,
    description: 'Cauliflower florets marinated in spiced batter, fried crisp, and tempered with curry leaves.',
    image: 'https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?w=800&auto=format&fit=crop&q=85&v=dish-eb-st2',
    dietary: ['veg', 'spicy'],
    prepTime: 12,
    available: true
  },
  {
    id: 'dish-eb-st3',
    name: 'Authentic South Indian Chicken 65',
    category: 'starters',
    shopSlug: 'giri-express-bistro',
    shopName: 'Giri Express & Bistro',
    price: 210,
    description: 'Boneless chicken cubes tossed with red chili marinade, yogurt, garlic, and curry leaves.',
    image: 'https://images.unsplash.com/photo-1610057099443-fde8c4d50f91?w=800&auto=format&fit=crop&q=85&v=dish-eb-st3',
    dietary: ['non-veg', 'chef-special', 'spicy'],
    prepTime: 14,
    available: true
  },
  {
    id: 'dish-eb-st4',
    name: 'Crunchy Bistro Chicken Popcorn',
    category: 'starters',
    shopSlug: 'giri-express-bistro',
    shopName: 'Giri Express & Bistro',
    price: 190,
    description: 'Bite-sized chicken nuggets fried until golden crisp, served with spicy mayo dip.',
    image: 'https://images.unsplash.com/photo-1562967914-608f82629710?w=800&auto=format&fit=crop&q=85&v=dish-eb-st4',
    dietary: ['non-veg'],
    prepTime: 10,
    available: true
  },
  {
    id: 'dish-eb-st5',
    name: 'Wok-Tossed Spicy Chilli Paneer',
    category: 'starters',
    shopSlug: 'giri-express-bistro',
    shopName: 'Giri Express & Bistro',
    price: 180,
    description: 'Cottage cheese cubes wok-fried with bell peppers, onions, green chilies, and soy sauce.',
    image: 'https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?w=800&auto=format&fit=crop&q=85&v=dish-eb-st5',
    dietary: ['veg', 'spicy'],
    prepTime: 12,
    available: true
  },

  // 11. FRIES & SNACKS
  {
    id: 'dish-eb-fs1',
    name: 'Golden Salted French Fries',
    category: 'fast-food',
    shopSlug: 'giri-express-bistro',
    shopName: 'Giri Express & Bistro',
    price: 110,
    description: 'Crispy golden potato fries lightly salted, served with tomato ketchup.',
    image: 'https://images.unsplash.com/photo-1576107232684-1279f3908594?w=800&auto=format&fit=crop&q=85&v=dish-eb-fs1',
    dietary: ['veg'],
    prepTime: 8,
    available: true
  },
  {
    id: 'dish-eb-fs2',
    name: 'Spicy Peri Peri Seasoned Fries',
    category: 'fast-food',
    shopSlug: 'giri-express-bistro',
    shopName: 'Giri Express & Bistro',
    price: 130,
    description: 'Crispy fries tossed in zesty African peri peri spice mix.',
    image: 'https://images.unsplash.com/photo-1573080496219-bb080dd4f877?w=800&auto=format&fit=crop&q=85&v=dish-eb-fs2',
    dietary: ['veg', 'spicy'],
    prepTime: 8,
    available: true
  },
  {
    id: 'dish-eb-fs3',
    name: 'Loaded Melted Cheese Fries',
    category: 'fast-food',
    shopSlug: 'giri-express-bistro',
    shopName: 'Giri Express & Bistro',
    price: 150,
    description: 'Crispy fries smothered in warm liquid cheese sauce and jalapeno slice toppings.',
    image: 'https://images.unsplash.com/photo-1585109649139-366815a0d713?w=800&auto=format&fit=crop&q=85&v=dish-eb-fs3',
    dietary: ['veg', 'chef-special'],
    prepTime: 10,
    available: true
  },
  {
    id: 'dish-eb-fs4',
    name: 'Crispy Garlic Seasoned Potato Wedges',
    category: 'fast-food',
    shopSlug: 'giri-express-bistro',
    shopName: 'Giri Express & Bistro',
    price: 135,
    description: 'Thick cut skin-on potato wedges seasoned with garlic herb rub.',
    image: 'https://images.unsplash.com/photo-1618040996337-56904b7850b9?w=800&auto=format&fit=crop&q=85&v=dish-eb-fs4',
    dietary: ['veg'],
    prepTime: 10,
    available: true
  },
  {
    id: 'dish-eb-fs5',
    name: 'Cheesy Mexican Salsa Nachos',
    category: 'fast-food',
    shopSlug: 'giri-express-bistro',
    shopName: 'Giri Express & Bistro',
    price: 160,
    description: 'Tortilla corn chips topped with warm cheese sauce, fresh tomato salsa, and jalapenos.',
    image: 'https://images.unsplash.com/photo-1513456852971-30c0b8199d4d?w=800&auto=format&fit=crop&q=85&v=dish-eb-fs5',
    dietary: ['veg'],
    prepTime: 8,
    available: true
  },

  // 12. CHICKEN SPECIALS
  {
    id: 'dish-eb-cs1',
    name: 'Crispy Fried Spicy Chicken Wings',
    category: 'starters',
    shopSlug: 'giri-express-bistro',
    shopName: 'Giri Express & Bistro',
    price: 220,
    description: 'Crispy bone-in chicken wings tossed in fiery red hot sauce.',
    image: 'https://images.unsplash.com/photo-1567620832903-9fc6debc209f?w=800&auto=format&fit=crop&q=85&v=dish-eb-cs1',
    dietary: ['non-veg', 'spicy'],
    prepTime: 14,
    available: true
  },
  {
    id: 'dish-eb-cs2',
    name: 'Golden Crunchy Chicken Strips',
    category: 'starters',
    shopSlug: 'giri-express-bistro',
    shopName: 'Giri Express & Bistro',
    price: 200,
    description: 'Tender chicken breast tenders coated in seasoned breadcrumbs and deep fried.',
    image: 'https://images.unsplash.com/photo-1562967914-608f82629710?w=800&auto=format&fit=crop&q=85&v=dish-eb-cs2',
    dietary: ['non-veg'],
    prepTime: 12,
    available: true
  },
  {
    id: 'dish-eb-cs3',
    name: 'Indo-Chinese Dry Chilli Chicken',
    category: 'starters',
    shopSlug: 'giri-express-bistro',
    shopName: 'Giri Express & Bistro',
    price: 210,
    description: 'Fried chicken pieces tossed with green chilies, garlic, capsicum, and dark soy glaze.',
    image: 'https://images.unsplash.com/photo-1610057099443-fde8c4d50f91?w=800&auto=format&fit=crop&q=85&v=dish-eb-cs3',
    dietary: ['non-veg', 'spicy'],
    prepTime: 14,
    available: true
  },
  {
    id: 'dish-eb-cs4',
    name: 'Black Pepper Crusted Chicken Fry',
    category: 'starters',
    shopSlug: 'giri-express-bistro',
    shopName: 'Giri Express & Bistro',
    price: 220,
    description: 'South Indian style succulent chicken pieces tossed with freshly ground black pepper and curry leaves.',
    image: 'https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?w=800&auto=format&fit=crop&q=85&v=dish-eb-cs4',
    dietary: ['non-veg', 'spicy'],
    prepTime: 14,
    available: true
  },
  {
    id: 'dish-eb-cs5',
    name: 'Smoky Glazed BBQ Chicken Drumsticks',
    category: 'starters',
    shopSlug: 'giri-express-bistro',
    shopName: 'Giri Express & Bistro',
    price: 240,
    description: 'Char-grilled chicken drumsticks slathered with rich sweet and smoky barbecue sauce.',
    image: 'https://images.unsplash.com/photo-1598515214211-89d3c73ae83b?w=800&auto=format&fit=crop&q=85&v=dish-eb-cs5',
    dietary: ['non-veg', 'chef-special'],
    prepTime: 15,
    available: true
  },

  // 13. VEG SPECIALS
  {
    id: 'dish-eb-vs1',
    name: 'Charcoal Roasted Paneer Tikka',
    category: 'starters',
    shopSlug: 'giri-express-bistro',
    shopName: 'Giri Express & Bistro',
    price: 190,
    description: 'Cottage cheese cubes marinated in spiced yogurt and grilled in charcoal tandoor with onions.',
    image: 'https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?w=800&auto=format&fit=crop&q=85&v=dish-eb-vs1',
    dietary: ['veg', 'chef-special'],
    prepTime: 14,
    available: true
  },
  {
    id: 'dish-eb-vs2',
    name: 'Indo-Chinese Dry Veg Manchurian',
    category: 'starters',
    shopSlug: 'giri-express-bistro',
    shopName: 'Giri Express & Bistro',
    price: 160,
    description: 'Minced vegetable dumplings fried crisp and tossed in tangy soy-garlic sauce.',
    image: 'https://images.unsplash.com/photo-1541832676-9b763b0239ab?w=800&auto=format&fit=crop&q=85&v=dish-eb-vs2',
    dietary: ['veg'],
    prepTime: 12,
    available: true
  },
  {
    id: 'dish-eb-vs3',
    name: 'Spicy Dry Chilli Paneer',
    category: 'starters',
    shopSlug: 'giri-express-bistro',
    shopName: 'Giri Express & Bistro',
    price: 180,
    description: 'Fried cottage cheese cubes tossed with capsicum, onion, green chilies, and tangy soy sauce.',
    image: 'https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?w=800&auto=format&fit=crop&q=85&v=dish-eb-vs3',
    dietary: ['veg', 'spicy'],
    prepTime: 12,
    available: true
  },
  {
    id: 'dish-eb-vs4',
    name: 'Chettinad Mushroom Pepper Fry',
    category: 'starters',
    shopSlug: 'giri-express-bistro',
    shopName: 'Giri Express & Bistro',
    price: 175,
    description: 'Fresh button mushrooms sautéed with crushed pepper, fennel seeds, garlic, and curry leaves.',
    image: 'https://images.unsplash.com/photo-1608039829572-78524f79c4c7?w=800&auto=format&fit=crop&q=85&v=dish-eb-vs4',
    dietary: ['veg', 'spicy'],
    prepTime: 12,
    available: true
  },
  {
    id: 'dish-eb-vs5',
    name: 'Golden Crispy Baby Corn Pepper Fry',
    category: 'starters',
    shopSlug: 'giri-express-bistro',
    shopName: 'Giri Express & Bistro',
    price: 165,
    description: 'Tender baby corn spears batter fried and tossed with black pepper and spring onions.',
    image: 'https://images.unsplash.com/photo-1551782450-a2132b4ba21d?w=800&auto=format&fit=crop&q=85&v=dish-eb-vs5',
    dietary: ['veg'],
    prepTime: 10,
    available: true
  },

  // 14. BISTRO COFFEE
  {
    id: 'dish-eb-bc1',
    name: 'Artisan Dark Roast Espresso Shot',
    category: 'drinks',
    shopSlug: 'giri-express-bistro',
    shopName: 'Giri Express & Bistro',
    price: 90,
    description: 'Single origin Arabica bean shot with intense aroma and golden crema.',
    image: 'https://images.unsplash.com/photo-1510591509098-f4fdc6d0ff04?w=800&auto=format&fit=crop&q=85&v=dish-eb-bc1',
    dietary: ['veg'],
    prepTime: 4,
    available: true
  },
  {
    id: 'dish-eb-bc2',
    name: 'Classic Hot Dark Roast Americano',
    category: 'drinks',
    shopSlug: 'giri-express-bistro',
    shopName: 'Giri Express & Bistro',
    price: 110,
    description: 'Double espresso shot diluted with hot purified water for a smooth rich flavor.',
    image: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=800&auto=format&fit=crop&q=85&v=dish-eb-bc2',
    dietary: ['veg'],
    prepTime: 5,
    available: true
  },
  {
    id: 'dish-eb-bc3',
    name: 'Velvety Frothy Milk Cappuccino',
    category: 'drinks',
    shopSlug: 'giri-express-bistro',
    shopName: 'Giri Express & Bistro',
    price: 130,
    description: 'Equal parts espresso, steamed milk, and thick velvety microfoam dusted with cocoa.',
    image: 'https://images.unsplash.com/photo-1572442388796-11668a67e53d?w=800&auto=format&fit=crop&q=85&v=dish-eb-bc3',
    dietary: ['veg', 'chef-special'],
    prepTime: 6,
    available: true
  },
  {
    id: 'dish-eb-bc4',
    name: 'Smooth Steamed Cafe Latte',
    category: 'drinks',
    shopSlug: 'giri-express-bistro',
    shopName: 'Giri Express & Bistro',
    price: 140,
    description: 'Espresso combined with steamed milk and a thin layer of foam art.',
    image: 'https://images.unsplash.com/photo-1534778101976-62847782c213?w=800&auto=format&fit=crop&q=85&v=dish-eb-bc4',
    dietary: ['veg'],
    prepTime: 6,
    available: true
  },
  {
    id: 'dish-eb-bc5',
    name: 'Belgian Chocolate Cafe Mocha',
    category: 'drinks',
    shopSlug: 'giri-express-bistro',
    shopName: 'Giri Express & Bistro',
    price: 155,
    description: 'Rich dark chocolate syrup mixed with espresso shot, steamed milk, and cream top.',
    image: 'https://images.unsplash.com/photo-1578314675249-a6910f80cc4e?w=800&auto=format&fit=crop&q=85&v=dish-eb-bc5',
    dietary: ['veg'],
    prepTime: 7,
    available: true
  },
  {
    id: 'dish-eb-bc6',
    name: 'South Indian Brass Filter Coffee',
    category: 'drinks',
    shopSlug: 'giri-express-bistro',
    shopName: 'Giri Express & Bistro',
    price: 70,
    description: 'Traditional decoction brewed coffee frothed with hot milk in brass dabarah set.',
    image: 'https://images.unsplash.com/photo-1517256064527-09c73fc73e38?w=800&auto=format&fit=crop&q=85&v=dish-eb-bc6',
    dietary: ['veg', 'chef-special'],
    prepTime: 5,
    available: true
  },

  // 15. COLD BEVERAGES
  {
    id: 'dish-eb-cb1',
    name: 'Classic Thick Cold Coffee with Ice Cream',
    category: 'drinks',
    shopSlug: 'giri-express-bistro',
    shopName: 'Giri Express & Bistro',
    price: 140,
    description: 'Chilled espresso blended with chilled milk, sugar, and topped with vanilla ice cream scoop.',
    image: 'https://images.unsplash.com/photo-1517701604599-bb29b565090c?w=800&auto=format&fit=crop&q=85&v=dish-eb-cb1',
    dietary: ['veg', 'chef-special'],
    prepTime: 6,
    available: true
  },
  {
    id: 'dish-eb-cb2',
    name: 'Chilled Vanilla Iced Latte',
    category: 'drinks',
    shopSlug: 'giri-express-bistro',
    shopName: 'Giri Express & Bistro',
    price: 145,
    description: 'Espresso poured over ice cubes, milk, and natural Madagascar vanilla syrup.',
    image: 'https://images.unsplash.com/photo-1517701604599-bb29b565090c?w=800&auto=format&fit=crop&q=85&v=dish-eb-cb2',
    dietary: ['veg'],
    prepTime: 5,
    available: true
  },
  {
    id: 'dish-eb-cb3',
    name: 'Dark Chocolate Iced Mocha',
    category: 'drinks',
    shopSlug: 'giri-express-bistro',
    shopName: 'Giri Express & Bistro',
    price: 155,
    description: 'Chilled espresso, dark cocoa sauce, milk, and crushed ice topped with chocolate drizzle.',
    image: 'https://images.unsplash.com/photo-1572442388796-11668a67e53d?w=800&auto=format&fit=crop&q=85&v=dish-eb-cb3',
    dietary: ['veg'],
    prepTime: 6,
    available: true
  },
  {
    id: 'dish-eb-cb4',
    name: 'Refreshing Lemon Mint Iced Tea',
    category: 'drinks',
    shopSlug: 'giri-express-bistro',
    shopName: 'Giri Express & Bistro',
    price: 110,
    description: 'Freshly brewed black tea infused with lemon juice, mint leaves, and ice cubes.',
    image: 'https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=800&auto=format&fit=crop&q=85&v=dish-eb-cb4',
    dietary: ['veg'],
    prepTime: 5,
    available: true
  },
  {
    id: 'dish-eb-cb5',
    name: 'Double Chocolate Fudge Frappe',
    category: 'drinks',
    shopSlug: 'giri-express-bistro',
    shopName: 'Giri Express & Bistro',
    price: 165,
    description: 'Blended icy chocolate beverage crowned with whipped cream and chocolate chips.',
    image: 'https://images.unsplash.com/photo-1572490122747-3968b75cc699?w=800&auto=format&fit=crop&q=85&v=dish-eb-cb5',
    dietary: ['veg'],
    prepTime: 7,
    available: true
  },

  // 16. MOCKTAILS & COOLERS
  {
    id: 'dish-eb-mc1',
    name: 'Sparkling Virgin Mint Mojito',
    category: 'drinks',
    shopSlug: 'giri-express-bistro',
    shopName: 'Giri Express & Bistro',
    price: 130,
    description: 'Fresh mint leaves crushed with lime wedges, sugar, and topped with sparkling soda and ice.',
    image: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?w=800&auto=format&fit=crop&q=85&v=dish-eb-mc1',
    dietary: ['veg', 'chef-special'],
    prepTime: 5,
    available: true
  },
  {
    id: 'dish-eb-mc2',
    name: 'Tropical Blue Lagoon Cooler',
    category: 'drinks',
    shopSlug: 'giri-express-bistro',
    shopName: 'Giri Express & Bistro',
    price: 140,
    description: 'Blue curacao syrup shaken with lemon juice, sprite, and crushed ice garnish.',
    image: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?w=800&auto=format&fit=crop&q=85&v=dish-eb-mc2',
    dietary: ['veg'],
    prepTime: 5,
    available: true
  },
  {
    id: 'dish-eb-mc3',
    name: 'Crisp Green Apple Sparkler Cooler',
    category: 'drinks',
    shopSlug: 'giri-express-bistro',
    shopName: 'Giri Express & Bistro',
    price: 135,
    description: 'Tangy green apple syrup combined with lime, mint, and fizzy soda.',
    image: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?w=800&auto=format&fit=crop&q=85&v=dish-eb-mc3',
    dietary: ['veg'],
    prepTime: 5,
    available: true
  },
  {
    id: 'dish-eb-mc4',
    name: 'Zesty Lemon Mint Detox Cooler',
    category: 'drinks',
    shopSlug: 'giri-express-bistro',
    shopName: 'Giri Express & Bistro',
    price: 110,
    description: 'Fresh squeezed lemon juice, mint leaves, black salt, and chilled mineral water.',
    image: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?w=800&auto=format&fit=crop&q=85&v=dish-eb-mc4',
    dietary: ['veg'],
    prepTime: 4,
    available: true
  },
  {
    id: 'dish-eb-mc5',
    name: 'Sweet Strawberry Basil Cooler',
    category: 'drinks',
    shopSlug: 'giri-express-bistro',
    shopName: 'Giri Express & Bistro',
    price: 140,
    description: 'Ripe strawberry crush muddled with fresh basil and chilled sparkling water.',
    image: 'https://images.unsplash.com/photo-1553530666-ba11a7da3888?w=800&auto=format&fit=crop&q=85&v=dish-eb-mc5',
    dietary: ['veg'],
    prepTime: 5,
    available: true
  },

  // 17. FRESH JUICES
  {
    id: 'dish-eb-fj1',
    name: 'Freshly Squeezed Orange Juice',
    category: 'drinks',
    shopSlug: 'giri-express-bistro',
    shopName: 'Giri Express & Bistro',
    price: 110,
    description: '100% natural cold pressed Valencia orange juice served chilled with no added sugar.',
    image: 'https://images.unsplash.com/photo-1613478223719-2ab802602423?w=800&auto=format&fit=crop&q=85&v=dish-eb-fj1',
    dietary: ['veg'],
    prepTime: 5,
    available: true
  },
  {
    id: 'dish-eb-fj2',
    name: 'Hydrating Fresh Watermelon Juice',
    category: 'drinks',
    shopSlug: 'giri-express-bistro',
    shopName: 'Giri Express & Bistro',
    price: 90,
    description: 'Freshly blended sweet watermelon juice infused with a dash of mint.',
    image: 'https://images.unsplash.com/photo-1589733955941-5eeaf752f6dd?w=800&auto=format&fit=crop&q=85&v=dish-eb-fj2',
    dietary: ['veg'],
    prepTime: 5,
    available: true
  },
  {
    id: 'dish-eb-fj3',
    name: 'Golden Fresh Pineapple Juice',
    category: 'drinks',
    shopSlug: 'giri-express-bistro',
    shopName: 'Giri Express & Bistro',
    price: 100,
    description: 'Pure cold-extracted ripe pineapple juice with a hint of rock salt.',
    image: 'https://images.unsplash.com/photo-1550258987-190a2d41a8ba?w=800&auto=format&fit=crop&q=85&v=dish-eb-fj3',
    dietary: ['veg'],
    prepTime: 5,
    available: true
  },
  {
    id: 'dish-eb-fj4',
    name: 'Rich Antioxidant Pomegranate Juice',
    category: 'drinks',
    shopSlug: 'giri-express-bistro',
    shopName: 'Giri Express & Bistro',
    price: 130,
    description: 'Freshly pressed ruby red pomegranate juice loaded with natural goodness.',
    image: 'https://images.unsplash.com/photo-1613478223719-2ab802602423?w=800&auto=format&fit=crop&q=85&v=dish-eb-fj4',
    dietary: ['veg', 'chef-special'],
    prepTime: 6,
    available: true
  },
  {
    id: 'dish-eb-fj5',
    name: 'Tangy Fresh Sweet Lime (Mosambi) Juice',
    category: 'drinks',
    shopSlug: 'giri-express-bistro',
    shopName: 'Giri Express & Bistro',
    price: 95,
    description: 'Freshly extracted sweet lime juice seasoned with chat masala and black salt.',
    image: 'https://images.unsplash.com/photo-1613478223719-2ab802602423?w=800&auto=format&fit=crop&q=85&v=dish-eb-fj5',
    dietary: ['veg'],
    prepTime: 5,
    available: true
  },

  // 18. MILKSHAKES
  {
    id: 'dish-eb-ms1',
    name: 'Rich Belgian Chocolate Thick Shake',
    category: 'drinks',
    shopSlug: 'giri-express-bistro',
    shopName: 'Giri Express & Bistro',
    price: 150,
    description: 'Creamy milk blended with dark Dutch chocolate ice cream and cocoa sauce.',
    image: 'https://images.unsplash.com/photo-1572490122747-3968b75cc699?w=800&auto=format&fit=crop&q=85&v=dish-eb-ms1',
    dietary: ['veg', 'chef-special'],
    prepTime: 6,
    available: true
  },
  {
    id: 'dish-eb-ms2',
    name: 'Classic Creamy Vanilla Shake',
    category: 'drinks',
    shopSlug: 'giri-express-bistro',
    shopName: 'Giri Express & Bistro',
    price: 130,
    description: 'Smooth Madagascar vanilla bean ice cream blended with cold whole milk.',
    image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=800&auto=format&fit=crop&q=85&v=dish-eb-ms2',
    dietary: ['veg'],
    prepTime: 5,
    available: true
  },
  {
    id: 'dish-eb-ms3',
    name: 'Real Strawberry Thick Milkshake',
    category: 'drinks',
    shopSlug: 'giri-express-bistro',
    shopName: 'Giri Express & Bistro',
    price: 140,
    description: 'Blended real strawberry fruit chunks, strawberry ice cream, and chilled milk.',
    image: 'https://images.unsplash.com/photo-1553530666-ba11a7da3888?w=800&auto=format&fit=crop&q=85&v=dish-eb-ms3',
    dietary: ['veg'],
    prepTime: 6,
    available: true
  },
  {
    id: 'dish-eb-ms4',
    name: 'Alphonso Mango Thick Milkshake',
    category: 'drinks',
    shopSlug: 'giri-express-bistro',
    shopName: 'Giri Express & Bistro',
    price: 150,
    description: 'Lush Alphonso mango pulp blended with rich vanilla ice cream.',
    image: 'https://images.unsplash.com/photo-1623065422902-30a2d299bbe4?w=800&auto=format&fit=crop&q=85&v=dish-eb-ms4',
    dietary: ['veg'],
    prepTime: 6,
    available: true
  },
  {
    id: 'dish-eb-ms5',
    name: 'Crunchy Chocolate Oreo Biscuit Shake',
    category: 'drinks',
    shopSlug: 'giri-express-bistro',
    shopName: 'Giri Express & Bistro',
    price: 160,
    description: 'Oreo cookies crushed into thick vanilla chocolate ice cream shake topped with Oreo crumble.',
    image: 'https://images.unsplash.com/photo-1572490122747-3968b75cc699?w=800&auto=format&fit=crop&q=85&v=dish-eb-ms5',
    dietary: ['veg', 'chef-special'],
    prepTime: 7,
    available: true
  },

  // 19. DESSERTS
  {
    id: 'dish-eb-ds1',
    name: 'Warm Sizzling Chocolate Brownie',
    category: 'desserts',
    shopSlug: 'giri-express-bistro',
    shopName: 'Giri Express & Bistro',
    price: 130,
    description: 'Dense dark chocolate fudge brownie served hot with a drizzle of chocolate sauce.',
    image: 'https://images.unsplash.com/photo-1606313564200-e75d5e30476c?w=800&auto=format&fit=crop&q=85&v=dish-eb-ds1',
    dietary: ['veg', 'chef-special'],
    prepTime: 6,
    available: true
  },
  {
    id: 'dish-eb-ds2',
    name: 'Classic New York Baked Cheesecake',
    category: 'desserts',
    shopSlug: 'giri-express-bistro',
    shopName: 'Giri Express & Bistro',
    price: 180,
    description: 'Rich cream cheese cake slice over graham cracker crust with berry compote topping.',
    image: 'https://images.unsplash.com/photo-1533134242443-d4fd215305ad?w=800&auto=format&fit=crop&q=85&v=dish-eb-ds2',
    dietary: ['veg'],
    prepTime: 5,
    available: true
  },
  {
    id: 'dish-eb-ds3',
    name: 'Authentic Italian Espresso Tiramisu',
    category: 'desserts',
    shopSlug: 'giri-express-bistro',
    shopName: 'Giri Express & Bistro',
    price: 190,
    description: 'Ladyfinger biscuits soaked in espresso layered with mascarpone cream and cocoa powder.',
    image: 'https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=800&auto=format&fit=crop&q=85&v=dish-eb-ds3',
    dietary: ['veg'],
    prepTime: 5,
    available: true
  },
  {
    id: 'dish-eb-ds4',
    name: 'Silky Belgian Chocolate Mousse',
    category: 'desserts',
    shopSlug: 'giri-express-bistro',
    shopName: 'Giri Express & Bistro',
    price: 140,
    description: 'Light and airy whipped dark chocolate mousse served in a glass dessert cup.',
    image: 'https://images.unsplash.com/photo-1541781774459-bb2af2f05b55?w=800&auto=format&fit=crop&q=85&v=dish-eb-ds4',
    dietary: ['veg'],
    prepTime: 5,
    available: true
  },
  {
    id: 'dish-eb-ds5',
    name: 'Hot Ghee Gulab Jamun (2 Pcs)',
    category: 'desserts',
    shopSlug: 'giri-express-bistro',
    shopName: 'Giri Express & Bistro',
    price: 80,
    description: 'Soft milk dumplings fried in desi ghee and soaked in warm cardamom rose sugar syrup.',
    image: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?w=800&auto=format&fit=crop&q=85&v=dish-eb-ds5',
    dietary: ['veg'],
    prepTime: 5,
    available: true
  },

  // 20. COMBOS
  {
    id: 'dish-eb-cb-cb1',
    name: 'Express Burger & Fries Combo',
    category: 'fast-food',
    shopSlug: 'giri-express-bistro',
    shopName: 'Giri Express & Bistro',
    price: 230,
    description: 'Crispy Veg / Chicken Burger, Salted French Fries, and a Cold Drink of your choice.',
    image: 'https://images.unsplash.com/photo-1610614819513-58e34989848b?w=800&auto=format&fit=crop&q=85&v=dish-eb-cb-cb1',
    dietary: ['chef-special'],
    prepTime: 12,
    available: true
  },
  {
    id: 'dish-eb-cb-cb2',
    name: 'Special Biryani Feast Combo',
    category: 'biryani',
    shopSlug: 'giri-express-bistro',
    shopName: 'Giri Express & Bistro',
    price: 320,
    description: 'Chicken Biryani portion, Chicken 65 (4 pcs), Raitha, Mirchi ka Salan, and Gulab Jamun.',
    image: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=800&auto=format&fit=crop&q=85&v=dish-eb-cb-cb2',
    dietary: ['non-veg', 'chef-special'],
    prepTime: 15,
    available: true
  },
  {
    id: 'dish-eb-cb-cb3',
    name: 'Bistro Wrap & Beverage Combo',
    category: 'fast-food',
    shopSlug: 'giri-express-bistro',
    shopName: 'Giri Express & Bistro',
    price: 240,
    description: 'Choice of Kathi Roll / Paneer Wrap served with Peri Peri Fries and Iced Tea.',
    image: 'https://images.unsplash.com/photo-1626700051175-6818013e1d4f?w=800&auto=format&fit=crop&q=85&v=dish-eb-cb-cb3',
    dietary: ['veg'],
    prepTime: 12,
    available: true
  },
  {
    id: 'dish-eb-cb-cb4',
    name: 'Gourmet Sandwich Meal Combo',
    category: 'fast-food',
    shopSlug: 'giri-express-bistro',
    shopName: 'Giri Express & Bistro',
    price: 220,
    description: 'Grilled Cheese / Veg Sandwich, Potato Wedges, and Cold Coffee with ice cream.',
    image: 'https://images.unsplash.com/photo-1567234669003-dce7a7a88821?w=800&auto=format&fit=crop&q=85&v=dish-eb-cb-cb4',
    dietary: ['veg'],
    prepTime: 12,
    available: true
  },
  {
    id: 'dish-eb-cb-cb5',
    name: 'Italian Pizza & Pasta Combo',
    category: 'pizzas',
    shopSlug: 'giri-express-bistro',
    shopName: 'Giri Express & Bistro',
    price: 450,
    description: 'Medium Margherita / Farmhouse Pizza, Alfredo Penne Pasta, and Garlic Bread (2 pcs).',
    image: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=800&auto=format&fit=crop&q=85&v=dish-eb-cb-cb5',
    dietary: ['veg', 'chef-special'],
    prepTime: 18,
    available: true
  },
  {
    id: 'dish-eb-cb-cb6',
    name: 'Bistro Ultimate Family Feast Combo',
    category: 'mains',
    shopSlug: 'giri-express-bistro',
    shopName: 'Giri Express & Bistro',
    price: 890,
    description: 'Chicken Dum Biryani (2), Paneer Tikka Pizza, Chicken Wings (6 pcs), 4 Cold Beverages.',
    image: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800&auto=format&fit=crop&q=85&v=dish-eb-cb-cb6',
    dietary: ['chef-special'],
    prepTime: 22,
    available: true
  }
`;

const insertIndex = dishesContent.lastIndexOf('];');

if (insertIndex === -1) {
  console.error('Could not find end of INITIAL_DISHES array');
  process.exit(1);
}

// Insert complete catalog right before the end of INITIAL_DISHES
let updatedContent = dishesContent.slice(0, insertIndex) + ',\n' + completeExpressBistroCatalog + dishesContent.slice(insertIndex);

// Bump version key to clear localStorage
const newVersionKey = 'giri_dishes_v39_express_bistro_all_20_categories';
updatedContent = updatedContent.replace(/const versionKey = 'giri_dishes_v\d+[^']*';/, `const versionKey = '${newVersionKey}';`);

fs.writeFileSync(dishesPath, updatedContent, 'utf8');
console.log('✅ Successfully added all 115 Giri Express & Bistro dishes and updated versionKey!');
