const fs = require('fs');

const dishesPath = 'c:/Users/lenovo/OneDrive/Desktop/resturant/frontend/data/dishes.ts';
let dishesContent = fs.readFileSync(dishesPath, 'utf8');

const completeGrillCatalog = `
  // ==========================================
  // GIRI GRILL COMPLETE 70+ AUTHENTIC DISHES
  // ==========================================
  
  // 1. GRILLED CHICKEN
  {
    id: 'dish-grill-gc1',
    name: 'Charcoal Grilled Herb Chicken Breast',
    category: 'starters',
    shopSlug: 'giri-grill',
    shopName: 'Giri Grill',
    price: 360,
    description: 'Juicy tender chicken breast marinated in olive oil, fresh thyme, rosemary, and cracked black pepper, flame-grilled over natural charcoal.',
    image: 'https://images.unsplash.com/photo-1532550907401-a500c9a57435?w=800&auto=format&fit=crop&q=85&v=dish-grill-gc1',
    dietary: ['non-veg', 'chef-special'],
    prepTime: 15,
    available: true,
    customizations: [{ name: 'Side Herb Garlic Dip', price: 30 }]
  },
  {
    id: 'dish-grill-gc2',
    name: 'Smokey BBQ Grilled Chicken Leg Quarter',
    category: 'starters',
    shopSlug: 'giri-grill',
    shopName: 'Giri Grill',
    price: 340,
    description: 'Succulent whole chicken leg marinated in smoked paprika, garlic, and tangy BBQ glaze, slow-grilled to perfection.',
    image: 'https://images.unsplash.com/photo-1598515214211-89d3c73ae83b?w=800&auto=format&fit=crop&q=85&v=dish-grill-gc2',
    dietary: ['non-veg'],
    prepTime: 15,
    available: true,
    customizations: [{ name: 'Extra BBQ Sauce Drizzle', price: 25 }]
  },
  {
    id: 'dish-grill-gc3',
    name: 'Flame-Spiced Grilled Chicken Wings (8pcs)',
    category: 'starters',
    shopSlug: 'giri-grill',
    shopName: 'Giri Grill',
    price: 320,
    description: 'Jumbo chicken wings coated in hot chili marinade and flame-grilled with garlic butter finish.',
    image: 'https://images.unsplash.com/photo-1527477396000-e27163b481c2?w=800&auto=format&fit=crop&q=85&v=dish-grill-gc3',
    dietary: ['non-veg', 'spicy'],
    prepTime: 12,
    available: true,
    customizations: [{ name: 'Blue Cheese Dip Portion', price: 35 }]
  },
  {
    id: 'dish-grill-gc4',
    name: 'Classic Turkish Chicken Shashlik Skewers',
    category: 'starters',
    shopSlug: 'giri-grill',
    shopName: 'Giri Grill',
    price: 380,
    description: 'Tender chicken chunks skewered with colorful bell peppers, onions, and tomatoes, grilled with oriental spices.',
    image: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=800&auto=format&fit=crop&q=85&v=dish-grill-gc4',
    dietary: ['non-veg'],
    prepTime: 15,
    available: true,
    customizations: [{ name: 'Extra Skewer (1pc)', price: 90 }]
  },
  {
    id: 'dish-grill-gc5',
    name: 'Smokey Tandoori Chicken Tikka (8pcs)',
    category: 'starters',
    shopSlug: 'giri-grill',
    shopName: 'Giri Grill',
    price: 390,
    description: 'Boneless chicken morsels marinated in spiced hung yogurt, mustard oil, and Kasuri methi, charred in clay oven.',
    image: 'https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?w=800&auto=format&fit=crop&q=85&v=dish-grill-gc5',
    dietary: ['non-veg', 'chef-special'],
    prepTime: 15,
    available: true,
    customizations: [{ name: 'Mint Chutney Tub', price: 20 }]
  },
  {
    id: 'dish-grill-gc6',
    name: 'Royal Creamy Malai Chicken Tikka',
    category: 'starters',
    shopSlug: 'giri-grill',
    shopName: 'Giri Grill',
    price: 420,
    description: 'Melt-in-mouth chicken pieces marinated in cashews, fresh cream, white pepper, and cardamom, flame-grilled.',
    image: 'https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?w=800&auto=format&fit=crop&q=85&v=dish-grill-gc6',
    dietary: ['non-veg', 'chef-special'],
    prepTime: 16,
    available: true,
    customizations: [{ name: 'Extra Cream Cheese Drizzle', price: 30 }]
  },

  // 2. TANDOORI CHICKEN
  {
    id: 'dish-grill-tc1',
    name: 'Signature Royal Full Tandoori Chicken',
    category: 'starters',
    shopSlug: 'giri-grill',
    shopName: 'Giri Grill',
    price: 650,
    description: 'Whole chicken marinated overnight in red Kashmiri chili, ginger-garlic paste, and secret spices, roasted in clay tandoor.',
    image: 'https://images.unsplash.com/photo-1610057099443-fde8c4d50f91?w=800&auto=format&fit=crop&q=85&v=dish-grill-tc1',
    dietary: ['non-veg', 'chef-special'],
    prepTime: 25,
    available: true,
    customizations: [{ name: 'Extra Lachha Paratha (2pcs)', price: 60 }]
  },
  {
    id: 'dish-grill-tc2',
    name: 'Classic Half Tandoori Chicken',
    category: 'starters',
    shopSlug: 'giri-grill',
    shopName: 'Giri Grill',
    price: 360,
    description: 'Half chicken cut roasted with charcoal aroma, served with mint chutney and onion rings.',
    image: 'https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?w=800&auto=format&fit=crop&q=85&v=dish-grill-tc2',
    dietary: ['non-veg'],
    prepTime: 18,
    available: true,
    customizations: [{ name: 'Lemon Squeezers Extra', price: 0 }]
  },
  {
    id: 'dish-grill-tc3',
    name: 'Tandoori Spiced Chicken Leg Quarters (2pcs)',
    category: 'starters',
    shopSlug: 'giri-grill',
    shopName: 'Giri Grill',
    price: 350,
    description: 'Plump chicken leg quarters marinated in tandoori masalas and charred golden red.',
    image: 'https://images.unsplash.com/photo-1598515214211-89d3c73ae83b?w=800&auto=format&fit=crop&q=85&v=dish-grill-tc3',
    dietary: ['non-veg'],
    prepTime: 15,
    available: true,
    customizations: [{ name: 'Mint Mayonnaise Dip', price: 25 }]
  },
  {
    id: 'dish-grill-tc4',
    name: 'Charcoal Tandoori Chicken Wings (8pcs)',
    category: 'starters',
    shopSlug: 'giri-grill',
    shopName: 'Giri Grill',
    price: 330,
    description: 'Crispy charred tandoori wings served with spicy garlic mint dip.',
    image: 'https://images.unsplash.com/photo-1527477396000-e27163b481c2?w=800&auto=format&fit=crop&q=85&v=dish-grill-tc4',
    dietary: ['non-veg', 'spicy'],
    prepTime: 12,
    available: true,
    customizations: [{ name: 'Extra Spicy Dip', price: 20 }]
  },

  // 3. CHICKEN KEBABS
  {
    id: 'dish-grill-ck1',
    name: 'Royal Mughlai Chicken Seekh Kebab',
    category: 'starters',
    shopSlug: 'giri-grill',
    shopName: 'Giri Grill',
    price: 390,
    description: 'Finely minced chicken spiced with green chilies, cilantro, and royal garam masala, grilled on iron skewers.',
    image: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=800&auto=format&fit=crop&q=85&v=dish-grill-ck1',
    dietary: ['non-veg', 'chef-special'],
    prepTime: 15,
    available: true,
    customizations: [{ name: 'Butter Toasting', price: 20 }]
  },
  {
    id: 'dish-grill-ck2',
    name: 'Soft Silken Reshmi Kebab (6pcs)',
    category: 'starters',
    shopSlug: 'giri-grill',
    shopName: 'Giri Grill',
    price: 420,
    description: 'Juicy chicken kebabs blended with cashew paste, cream, and egg white, grilled till golden soft.',
    image: 'https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?w=800&auto=format&fit=crop&q=85&v=dish-grill-ck2',
    dietary: ['non-veg'],
    prepTime: 15,
    available: true,
    customizations: [{ name: 'Extra Garlic Butter', price: 25 }]
  },
  {
    id: 'dish-grill-ck3',
    name: 'Mint & Spinach Hariyali Chicken Kebab',
    category: 'starters',
    shopSlug: 'giri-grill',
    shopName: 'Giri Grill',
    price: 380,
    description: 'Chicken cubes coated in vibrant green marinade of fresh mint, coriander, spinach, and roasted cumin.',
    image: 'https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?w=800&auto=format&fit=crop&q=85&v=dish-grill-ck3',
    dietary: ['non-veg'],
    prepTime: 14,
    available: true,
    customizations: [{ name: 'Mint Chutney Tub', price: 15 }]
  },
  {
    id: 'dish-grill-ck4',
    name: 'Tandoori Stuffed Tangdi Kebab (3pcs)',
    category: 'starters',
    shopSlug: 'giri-grill',
    shopName: 'Giri Grill',
    price: 440,
    description: 'Drumsticks stuffed with spiced minced chicken, dry fruits, and grilled over red coals.',
    image: 'https://images.unsplash.com/photo-1598515214211-89d3c73ae83b?w=800&auto=format&fit=crop&q=85&v=dish-grill-ck4',
    dietary: ['non-veg', 'chef-special'],
    prepTime: 18,
    available: true,
    customizations: [{ name: 'Extra Stuffed Minced Meat', price: 40 }]
  },
  {
    id: 'dish-grill-ck5',
    name: 'Fire-Grilled Spicy Chicken Boti Kebab',
    category: 'starters',
    shopSlug: 'giri-grill',
    shopName: 'Giri Grill',
    price: 390,
    description: 'Bite-sized chicken chunks tossed in spicy Hyderabadi marination and flame-grilled.',
    image: 'https://images.unsplash.com/photo-1532550907401-a500c9a57435?w=800&auto=format&fit=crop&q=85&v=dish-grill-ck5',
    dietary: ['non-veg', 'spicy'],
    prepTime: 14,
    available: true,
    customizations: [{ name: 'Chili Powder Sprinkle', price: 0 }]
  },

  // 4. MUTTON GRILL
  {
    id: 'dish-grill-mg1',
    name: 'Mughlai Spiced Mutton Seekh Kebab',
    category: 'starters',
    shopSlug: 'giri-grill',
    shopName: 'Giri Grill',
    price: 490,
    description: 'Hand-ground tender lamb minced with aromatic spices, fresh mint, and charcoal-grilled on skewers.',
    image: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=800&auto=format&fit=crop&q=85&v=dish-grill-mg1',
    dietary: ['non-veg', 'chef-special'],
    prepTime: 16,
    available: true,
    customizations: [{ name: 'Side Rumali Roti', price: 30 }]
  },
  {
    id: 'dish-grill-mg2',
    name: 'Tender Mutton Shashlik Skewers',
    category: 'starters',
    shopSlug: 'giri-grill',
    shopName: 'Giri Grill',
    price: 520,
    description: 'Juicy lamb chunks marinated in papaya paste and red wine vinegar, grilled with roasted onions and capsicum.',
    image: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=800&auto=format&fit=crop&q=85&v=dish-grill-mg2',
    dietary: ['non-veg'],
    prepTime: 18,
    available: true,
    customizations: [{ name: 'Extra Lamb Skewer', price: 130 }]
  },
  {
    id: 'dish-grill-mg3',
    name: 'Charcoal Fire Grilled Mutton Chops (4pcs)',
    category: 'starters',
    shopSlug: 'giri-grill',
    shopName: 'Giri Grill',
    price: 580,
    description: 'Prime lamb chops marinated in garlic rosemary and Garam masala, charred on open flame.',
    image: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=800&auto=format&fit=crop&q=85&v=dish-grill-mg3',
    dietary: ['non-veg', 'chef-special'],
    prepTime: 20,
    available: true,
    customizations: [{ name: 'Extra Mutton Chop (1pc)', price: 140 }]
  },
  {
    id: 'dish-grill-mg4',
    name: 'Spicy Tandoori Mutton Boti Kebab',
    category: 'starters',
    shopSlug: 'giri-grill',
    shopName: 'Giri Grill',
    price: 530,
    description: 'Tender boneless mutton cubes marinated in Guntur chili paste and raw mango powder.',
    image: 'https://images.unsplash.com/photo-1532550907401-a500c9a57435?w=800&auto=format&fit=crop&q=85&v=dish-grill-mg4',
    dietary: ['non-veg', 'spicy'],
    prepTime: 16,
    available: true,
    customizations: [{ name: 'Lemon Mayo Dip', price: 25 }]
  },
  {
    id: 'dish-grill-mg5',
    name: 'Royal Shahi Mutton Tikka',
    category: 'starters',
    shopSlug: 'giri-grill',
    shopName: 'Giri Grill',
    price: 560,
    description: 'Succulent lamb tikka infused with saffron, nutmeg, and yellow chili powder.',
    image: 'https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?w=800&auto=format&fit=crop&q=85&v=dish-grill-mg5',
    dietary: ['non-veg', 'chef-special'],
    prepTime: 18,
    available: true,
    customizations: [{ name: 'Extra Saffron Glaze', price: 35 }]
  },

  // 5. FISH GRILL
  {
    id: 'dish-grill-fg1',
    name: 'Whole Tandoori Grilled Pomfret',
    category: 'starters',
    shopSlug: 'giri-grill',
    shopName: 'Giri Grill',
    price: 620,
    description: 'Whole fresh pomfret fish marinated in coastal carom seed spices and lemon, grilled golden.',
    image: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=800&auto=format&fit=crop&q=85&v=dish-grill-fg1',
    dietary: ['non-veg', 'chef-special'],
    prepTime: 20,
    available: true,
    customizations: [{ name: 'Side Garlic Butter Dip', price: 30 }]
  },
  {
    id: 'dish-grill-fg2',
    name: 'Norwegian Wood-Fired Salmon Fillet',
    category: 'starters',
    shopSlug: 'giri-grill',
    shopName: 'Giri Grill',
    price: 680,
    description: 'Wild Norwegian salmon grilled skin-crisp with dill butter, sea salt, and capers.',
    image: 'https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=800&auto=format&fit=crop&q=85&v=dish-grill-fg2',
    dietary: ['non-veg', 'chef-special'],
    prepTime: 18,
    available: true,
    customizations: [{ name: 'Extra Capers & Lemon', price: 25 }]
  },
  {
    id: 'dish-grill-fg3',
    name: 'Mediterranean Herb Grilled Seabass',
    category: 'starters',
    shopSlug: 'giri-grill',
    shopName: 'Giri Grill',
    price: 650,
    description: 'Fresh seabass fillet rubbed with garlic, oregano, olive oil, and charred lemon slices.',
    image: 'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?w=800&auto=format&fit=crop&q=85&v=dish-grill-fg3',
    dietary: ['non-veg'],
    prepTime: 18,
    available: true,
    customizations: [{ name: 'Side Roasted Potatoes', price: 40 }]
  },
  {
    id: 'dish-grill-fg4',
    name: 'Charcoal Grilled Ajwaini Fish Tikka',
    category: 'starters',
    shopSlug: 'giri-grill',
    shopName: 'Giri Grill',
    price: 480,
    description: "Boneless fish tikka chunks infused with bishop's weed (ajwain), yellow chili, and mustard oil.",
    image: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=800&auto=format&fit=crop&q=85&v=dish-grill-fg4',
    dietary: ['non-veg'],
    prepTime: 15,
    available: true,
    customizations: [{ name: 'Tartar Dip Tub', price: 25 }]
  },
  {
    id: 'dish-grill-fg5',
    name: 'Pan-Seared Lemon Herb White Fish',
    category: 'starters',
    shopSlug: 'giri-grill',
    shopName: 'Giri Grill',
    price: 490,
    description: 'Delicate white fish fillet seared with clarified butter, garlic, and fresh parsley sauce.',
    image: 'https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=800&auto=format&fit=crop&q=85&v=dish-grill-fg5',
    dietary: ['non-veg'],
    prepTime: 14,
    available: true,
    customizations: [{ name: 'Extra Parsley Butter', price: 20 }]
  },

  // 6. PRAWNS & SEAFOOD
  {
    id: 'dish-grill-ps1',
    name: 'Jumbo Butter Garlic Grilled Prawns (6pcs)',
    category: 'starters',
    shopSlug: 'giri-grill',
    shopName: 'Giri Grill',
    price: 640,
    description: 'King prawns tossed in roasted garlic, herb butter, and cracked white pepper, flame-grilled.',
    image: 'https://images.unsplash.com/photo-1565680018434-b513d5e5fd47?w=800&auto=format&fit=crop&q=85&v=dish-grill-ps1',
    dietary: ['non-veg', 'chef-special'],
    prepTime: 15,
    available: true,
    customizations: [{ name: 'Extra Garlic Butter Dip', price: 30 }]
  },
  {
    id: 'dish-grill-ps2',
    name: 'Sizzling Garlic Prawn Skewers',
    category: 'starters',
    shopSlug: 'giri-grill',
    shopName: 'Giri Grill',
    price: 620,
    description: 'Plump prawns skewered with garlic butter drizzle and parsley.',
    image: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=800&auto=format&fit=crop&q=85&v=dish-grill-ps2',
    dietary: ['non-veg'],
    prepTime: 14,
    available: true,
    customizations: [{ name: 'Extra Prawn Skewer', price: 120 }]
  },
  {
    id: 'dish-grill-ps3',
    name: 'Claypot Tandoori King Prawns',
    category: 'starters',
    shopSlug: 'giri-grill',
    shopName: 'Giri Grill',
    price: 650,
    description: 'Jumbo prawns marinated in red chili yogurt and lemon, tandoor roasted.',
    image: 'https://images.unsplash.com/photo-1565680018434-b513d5e5fd47?w=800&auto=format&fit=crop&q=85&v=dish-grill-ps3',
    dietary: ['non-veg', 'chef-special'],
    prepTime: 16,
    available: true,
    customizations: [{ name: 'Mint Dip', price: 20 }]
  },
  {
    id: 'dish-grill-ps4',
    name: 'Spicy Schezwan Chilli Prawn Grill',
    category: 'starters',
    shopSlug: 'giri-grill',
    shopName: 'Giri Grill',
    price: 610,
    description: 'Prawns marinated in red chili paste, soy, garlic, and scallions, grilled crisp.',
    image: 'https://images.unsplash.com/photo-1565680018434-b513d5e5fd47?w=800&auto=format&fit=crop&q=85&v=dish-grill-ps4',
    dietary: ['non-veg', 'spicy'],
    prepTime: 14,
    available: true,
    customizations: [{ name: 'Extra Schezwan Dip', price: 25 }]
  },
  {
    id: 'dish-grill-ps5',
    name: 'Artisanal Prawn & Veggie Shashlik',
    category: 'starters',
    shopSlug: 'giri-grill',
    shopName: 'Giri Grill',
    price: 630,
    description: 'Skewered jumbo prawns, bell peppers, and cherry tomatoes grilled over charcoal.',
    image: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=800&auto=format&fit=crop&q=85&v=dish-grill-ps5',
    dietary: ['non-veg'],
    prepTime: 15,
    available: true,
    customizations: [{ name: 'Side Garlic Bread Slice', price: 30 }]
  },

  // 7. VEG GRILL
  {
    id: 'dish-grill-vg1',
    name: 'Flame-Grilled Cottage Cheese Steak',
    category: 'starters',
    shopSlug: 'giri-grill',
    shopName: 'Giri Grill',
    price: 340,
    description: 'Thick slab of fresh paneer marinated in pesto olive oil and grilled with charred zucchini.',
    image: 'https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?w=800&auto=format&fit=crop&q=85&v=dish-grill-vg1',
    dietary: ['veg'],
    prepTime: 14,
    available: true,
    customizations: [{ name: 'Pesto Drizzle', price: 25 }]
  },
  {
    id: 'dish-grill-vg2',
    name: 'Classic Tandoori Paneer Tikka',
    category: 'starters',
    shopSlug: 'giri-grill',
    shopName: 'Giri Grill',
    price: 320,
    description: 'Cottage cheese cubes marinated in hung curd, Kashmiri chili, and kasuri methi, tandoor grilled.',
    image: 'https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?w=800&auto=format&fit=crop&q=85&v=dish-grill-vg2',
    dietary: ['veg', 'chef-special'],
    prepTime: 14,
    available: true,
    customizations: [{ name: 'Mint Chutney', price: 15 }]
  },
  {
    id: 'dish-grill-vg3',
    name: 'Butter Garlic Grilled Button Mushrooms',
    category: 'starters',
    shopSlug: 'giri-grill',
    shopName: 'Giri Grill',
    price: 290,
    description: 'Whole fresh button mushrooms stuffed with cheese and herbs, charcoal-grilled.',
    image: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800&auto=format&fit=crop&q=85&v=dish-grill-vg3',
    dietary: ['veg'],
    prepTime: 12,
    available: true,
    customizations: [{ name: 'Extra Cheese Stuffing', price: 30 }]
  },
  {
    id: 'dish-grill-vg4',
    name: 'Smokey Tandoori Stuffed Mushroom',
    category: 'starters',
    shopSlug: 'giri-grill',
    shopName: 'Giri Grill',
    price: 310,
    description: 'Mushrooms stuffed with paneer and spices, roasted in clay tandoor.',
    image: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800&auto=format&fit=crop&q=85&v=dish-grill-vg4',
    dietary: ['veg'],
    prepTime: 14,
    available: true,
    customizations: [{ name: 'Extra Spiced Gravy Dip', price: 20 }]
  },
  {
    id: 'dish-grill-vg5',
    name: 'Mexican Spiced Grilled Sweet Corn (2pcs)',
    category: 'starters',
    shopSlug: 'giri-grill',
    shopName: 'Giri Grill',
    price: 220,
    description: 'Whole sweet corn cobs rubbed with lime juice, chili powder, butter, and cotija cheese.',
    image: 'https://images.unsplash.com/photo-1551782450-a2132b4ba21d?w=800&auto=format&fit=crop&q=85&v=dish-grill-vg5',
    dietary: ['veg'],
    prepTime: 10,
    available: true,
    customizations: [{ name: 'Cotija Cheese Powder', price: 15 }]
  },
  {
    id: 'dish-grill-vg6',
    name: 'Herb Roasted Mediterranean Grilled Vegetables',
    category: 'starters',
    shopSlug: 'giri-grill',
    shopName: 'Giri Grill',
    price: 280,
    description: 'Assorted bell peppers, zucchini, broccoli, corn, and baby potatoes grilled with olive oil.',
    image: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=800&auto=format&fit=crop&q=85&v=dish-grill-vg6',
    dietary: ['veg'],
    prepTime: 12,
    available: true,
    customizations: [{ name: 'Extra Olive Oil Drizzle', price: 20 }]
  },

  // 8. PANEER & TIKKA SPECIALS
  {
    id: 'dish-grill-pt1',
    name: 'Tangy Achari Paneer Tikka',
    category: 'starters',
    shopSlug: 'giri-grill',
    shopName: 'Giri Grill',
    price: 330,
    description: 'Paneer cubes marinated in pickling spices (mustard, fennel, nigella) and tandoor charred.',
    image: 'https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?w=800&auto=format&fit=crop&q=85&v=dish-grill-pt1',
    dietary: ['veg', 'spicy'],
    prepTime: 14,
    available: true,
    customizations: [{ name: 'Extra Pickle Dip', price: 20 }]
  },
  {
    id: 'dish-grill-pt2',
    name: 'Rich Creamy Malai Paneer Tikka',
    category: 'starters',
    shopSlug: 'giri-grill',
    shopName: 'Giri Grill',
    price: 350,
    description: 'Soft paneer marinated in cream, cardamom, cashews, and cheese, grilled golden.',
    image: 'https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?w=800&auto=format&fit=crop&q=85&v=dish-grill-pt2',
    dietary: ['veg', 'chef-special'],
    prepTime: 15,
    available: true,
    customizations: [{ name: 'Cheese Dip Tub', price: 25 }]
  },
  {
    id: 'dish-grill-pt3',
    name: 'Minty Hariyali Paneer Tikka',
    category: 'starters',
    shopSlug: 'giri-grill',
    shopName: 'Giri Grill',
    price: 330,
    description: 'Paneer marinated in fresh mint, coriander, and green chili paste.',
    image: 'https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?w=800&auto=format&fit=crop&q=85&v=dish-grill-pt3',
    dietary: ['veg'],
    prepTime: 14,
    available: true,
    customizations: [{ name: 'Mint Sauce', price: 15 }]
  },
  {
    id: 'dish-grill-pt4',
    name: 'Royal Afghani Soft Paneer Tikka',
    category: 'starters',
    shopSlug: 'giri-grill',
    shopName: 'Giri Grill',
    price: 360,
    description: 'Paneer marinated in white pepper, melon seed paste, cream, and charred gently.',
    image: 'https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?w=800&auto=format&fit=crop&q=85&v=dish-grill-pt4',
    dietary: ['veg', 'chef-special'],
    prepTime: 15,
    available: true,
    customizations: [{ name: 'White Cream Drizzle', price: 25 }]
  },

  // 9. MIXED GRILL
  {
    id: 'dish-grill-mg-pl1',
    name: 'Grand Chicken Mixed Grill Platter',
    category: 'starters',
    shopSlug: 'giri-grill',
    shopName: 'Giri Grill',
    price: 680,
    description: 'Assortment of Chicken Tikka, Malai Tikka, Chicken Seekh, and Tangdi Kebab with dips.',
    image: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=800&auto=format&fit=crop&q=85&v=dish-grill-mg-pl1',
    dietary: ['non-veg', 'chef-special'],
    prepTime: 20,
    available: true,
    customizations: [{ name: 'Side Naan Basket', price: 60 }]
  },
  {
    id: 'dish-grill-mg-pl2',
    name: 'Royal Mutton Mixed Grill Platter',
    category: 'starters',
    shopSlug: 'giri-grill',
    shopName: 'Giri Grill',
    price: 820,
    description: 'Mutton Seekh, Mutton Boti, Mutton Chops, and Mutton Shashlik served with rumali roti.',
    image: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=800&auto=format&fit=crop&q=85&v=dish-grill-mg-pl2',
    dietary: ['non-veg', 'chef-special'],
    prepTime: 22,
    available: true,
    customizations: [{ name: 'Extra Rumali Roti (2pcs)', price: 40 }]
  },
  {
    id: 'dish-grill-mg-pl3',
    name: 'Coastal Seafood Mixed Grill Platter',
    category: 'starters',
    shopSlug: 'giri-grill',
    shopName: 'Giri Grill',
    price: 950,
    description: 'Grilled Pomfret, Garlic Prawns, Fish Tikka, and Prawn Shashlik served with lemon butter dip.',
    image: 'https://images.unsplash.com/photo-1565680018434-b513d5e5fd47?w=800&auto=format&fit=crop&q=85&v=dish-grill-mg-pl3',
    dietary: ['non-veg', 'chef-special'],
    prepTime: 22,
    available: true,
    customizations: [{ name: 'Garlic Butter Boat', price: 40 }]
  },
  {
    id: 'dish-grill-mg-pl4',
    name: 'Maharaja Royal Mixed Grill Platter',
    category: 'starters',
    shopSlug: 'giri-grill',
    shopName: 'Giri Grill',
    price: 1100,
    description: 'Grand feast of chicken, mutton, prawns, and fish grilled over live charcoal.',
    image: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=800&auto=format&fit=crop&q=85&v=dish-grill-mg-pl4',
    dietary: ['non-veg', 'chef-special'],
    prepTime: 25,
    available: true,
    customizations: [{ name: 'Extra Mint Dip & Salan', price: 50 }]
  },
  {
    id: 'dish-grill-mg-pl5',
    name: 'Giri Family Mega Grill Feast Platter',
    category: 'starters',
    shopSlug: 'giri-grill',
    shopName: 'Giri Grill',
    price: 1450,
    description: 'Massive platter serving 4-5 people with full tandoori chicken, kebabs, prawns, and garlic breads.',
    image: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=800&auto=format&fit=crop&q=85&v=dish-grill-mg-pl5',
    dietary: ['non-veg', 'chef-special'],
    prepTime: 30,
    available: true,
    customizations: [{ name: 'Family Soft Drink Bottle (1.25L)', price: 70 }]
  },

  // 10. BBQ SPECIALS
  {
    id: 'dish-grill-bbq1',
    name: 'Authentic Smoked BBQ Half Chicken',
    category: 'starters',
    shopSlug: 'giri-grill',
    shopName: 'Giri Grill',
    price: 480,
    description: 'Half chicken slow-smoked with hickory wood chips and glazed with honey BBQ sauce.',
    image: 'https://images.unsplash.com/photo-1598515214211-89d3c73ae83b?w=800&auto=format&fit=crop&q=85&v=dish-grill-bbq1',
    dietary: ['non-veg'],
    prepTime: 20,
    available: true,
    customizations: [{ name: 'Extra Hickory Sauce', price: 30 }]
  },
  {
    id: 'dish-grill-bbq2',
    name: 'Crispy Honey Glazed BBQ Wings (8pcs)',
    category: 'starters',
    shopSlug: 'giri-grill',
    shopName: 'Giri Grill',
    price: 360,
    description: 'Flame-grilled wings smothered in sweet honey BBQ glaze.',
    image: 'https://images.unsplash.com/photo-1527477396000-e27163b481c2?w=800&auto=format&fit=crop&q=85&v=dish-grill-bbq2',
    dietary: ['non-veg'],
    prepTime: 14,
    available: true,
    customizations: [{ name: 'Ranch Dip', price: 25 }]
  },
  {
    id: 'dish-grill-bbq3',
    name: 'Slow-Cooked Smoked BBQ Ribs',
    category: 'starters',
    shopSlug: 'giri-grill',
    shopName: 'Giri Grill',
    price: 690,
    description: 'Tender ribs slow-roasted for 6 hours until meat falls off bone, glazed with smoky sauce.',
    image: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=800&auto=format&fit=crop&q=85&v=dish-grill-bbq3',
    dietary: ['non-veg', 'chef-special'],
    prepTime: 22,
    available: true,
    customizations: [{ name: 'Side Coleslaw Salad', price: 40 }]
  },
  {
    id: 'dish-grill-bbq4',
    name: 'Spicy Honey Mustard BBQ Chicken Skewers',
    category: 'starters',
    shopSlug: 'giri-grill',
    shopName: 'Giri Grill',
    price: 390,
    description: 'Chicken cubes glazed with honey mustard BBQ sauce on wooden skewers.',
    image: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=800&auto=format&fit=crop&q=85&v=dish-grill-bbq4',
    dietary: ['non-veg'],
    prepTime: 15,
    available: true,
    customizations: [{ name: 'Mustard Dip', price: 20 }]
  },
  {
    id: 'dish-grill-bbq5',
    name: 'Charcoal Smoked BBQ Jumbo Prawns',
    category: 'starters',
    shopSlug: 'giri-grill',
    shopName: 'Giri Grill',
    price: 660,
    description: 'Jumbo prawns brushed with spicy house BBQ sauce and charred over charcoal.',
    image: 'https://images.unsplash.com/photo-1565680018434-b513d5e5fd47?w=800&auto=format&fit=crop&q=85&v=dish-grill-bbq5',
    dietary: ['non-veg', 'chef-special'],
    prepTime: 16,
    available: true,
    customizations: [{ name: 'Extra BBQ Sauce', price: 30 }]
  },

  // 11. SHASHLIK & SKEWERS
  {
    id: 'dish-grill-ss1',
    name: 'Turkish Style Chicken Shashlik Skewers',
    category: 'starters',
    shopSlug: 'giri-grill',
    shopName: 'Giri Grill',
    price: 390,
    description: 'Chicken, onions, peppers marinated in yogurt & cumin, grilled over open flame.',
    image: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=800&auto=format&fit=crop&q=85&v=dish-grill-ss1',
    dietary: ['non-veg'],
    prepTime: 15,
    available: true,
    customizations: [{ name: 'Side Garlic Dip', price: 25 }]
  },
  {
    id: 'dish-grill-ss2',
    name: 'Tender Lamb Mutton Shashlik Skewers',
    category: 'starters',
    shopSlug: 'giri-grill',
    shopName: 'Giri Grill',
    price: 510,
    description: 'Marinated mutton chunks with roasted cherry tomatoes and red onions.',
    image: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=800&auto=format&fit=crop&q=85&v=dish-grill-ss2',
    dietary: ['non-veg', 'chef-special'],
    prepTime: 18,
    available: true,
    customizations: [{ name: 'Extra Mutton Skewer', price: 120 }]
  },
  {
    id: 'dish-grill-ss3',
    name: 'Garden Fresh Vegetable Shashlik Skewers',
    category: 'starters',
    shopSlug: 'giri-grill',
    shopName: 'Giri Grill',
    price: 290,
    description: 'Paneer, mushrooms, bell peppers, and pineapple grilled on wooden skewers.',
    image: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=800&auto=format&fit=crop&q=85&v=dish-grill-ss3',
    dietary: ['veg'],
    prepTime: 12,
    available: true,
    customizations: [{ name: 'Pineapple Dip', price: 20 }]
  },
  {
    id: 'dish-grill-ss4',
    name: 'Garlic Butter Prawn Skewers (6pcs)',
    category: 'starters',
    shopSlug: 'giri-grill',
    shopName: 'Giri Grill',
    price: 620,
    description: 'Prawns threaded on skewers with garlic, butter, and lemon glaze.',
    image: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=800&auto=format&fit=crop&q=85&v=dish-grill-ss4',
    dietary: ['non-veg'],
    prepTime: 15,
    available: true,
    customizations: [{ name: 'Garlic Butter Dip', price: 30 }]
  },
  {
    id: 'dish-grill-ss5',
    name: 'Giri Signature Mixed Grill Skewers',
    category: 'starters',
    shopSlug: 'giri-grill',
    shopName: 'Giri Grill',
    price: 580,
    description: 'Combination of chicken, lamb, prawn, and veg skewers served on a wooden board.',
    image: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=800&auto=format&fit=crop&q=85&v=dish-grill-ss5',
    dietary: ['non-veg', 'chef-special'],
    prepTime: 18,
    available: true,
    customizations: [{ name: 'Herb Butter Dip', price: 25 }]
  },

  // 12. GRILL PLATTERS
  {
    id: 'dish-grill-gp1',
    name: 'Classic Chicken Kebab & Tikka Platter',
    category: 'starters',
    shopSlug: 'giri-grill',
    shopName: 'Giri Grill',
    price: 590,
    description: 'Combination of Chicken Tikka, Seekh Kebab, and Reshmi Kebab with naan bread.',
    image: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=800&auto=format&fit=crop&q=85&v=dish-grill-gp1',
    dietary: ['non-veg'],
    prepTime: 18,
    available: true,
    customizations: [{ name: 'Butter Naan Portion', price: 35 }]
  },
  {
    id: 'dish-grill-gp2',
    name: 'Royal Mutton Chops & Boti Platter',
    category: 'starters',
    shopSlug: 'giri-grill',
    shopName: 'Giri Grill',
    price: 790,
    description: 'Mutton Seekh, Mutton Chops, and Mutton Tikka served with mint raita.',
    image: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=800&auto=format&fit=crop&q=85&v=dish-grill-gp2',
    dietary: ['non-veg', 'chef-special'],
    prepTime: 20,
    available: true,
    customizations: [{ name: 'Mint Raita Bowl', price: 30 }]
  },
  {
    id: 'dish-grill-gp3',
    name: 'Oceanic Seafood Grill Platter',
    category: 'starters',
    shopSlug: 'giri-grill',
    shopName: 'Giri Grill',
    price: 890,
    description: 'Grilled Salmon, Tandoori Prawns, and Fish Tikka served with garlic butter sauce.',
    image: 'https://images.unsplash.com/photo-1565680018434-b513d5e5fd47?w=800&auto=format&fit=crop&q=85&v=dish-grill-gp3',
    dietary: ['non-veg', 'chef-special'],
    prepTime: 22,
    available: true,
    customizations: [{ name: 'Lemon Wedge Plate', price: 0 }]
  },
  {
    id: 'dish-grill-gp4',
    name: 'Deluxe Vegetarian Tandoori Platter',
    category: 'starters',
    shopSlug: 'giri-grill',
    shopName: 'Giri Grill',
    price: 490,
    description: 'Paneer Tikka, Mushroom Tikka, Grilled Corn, and Veg Seekh Kebab.',
    image: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=800&auto=format&fit=crop&q=85&v=dish-grill-gp4',
    dietary: ['veg'],
    prepTime: 16,
    available: true,
    customizations: [{ name: 'Extra Paneer Pieces', price: 50 }]
  },
  {
    id: 'dish-grill-gp5',
    name: 'Grand Family Feast Platter',
    category: 'starters',
    shopSlug: 'giri-grill',
    shopName: 'Giri Grill',
    price: 1290,
    description: 'Massive platter with full tandoori chicken, mutton kebabs, grilled prawns, and parathas.',
    image: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=800&auto=format&fit=crop&q=85&v=dish-grill-gp5',
    dietary: ['non-veg', 'chef-special'],
    prepTime: 28,
    available: true,
    customizations: [{ name: 'Cold Drink 1.25L', price: 70 }]
  },

  // 13. GRILLED BURGERS
  {
    id: 'dish-grill-gb1',
    name: 'Flame-Grilled Chicken Breast Burger',
    category: 'pizzas',
    shopSlug: 'giri-grill',
    shopName: 'Giri Grill',
    price: 340,
    description: 'Charcoal-grilled chicken breast, melted cheddar cheese, lettuce, tomato, and garlic mayo in brioche bun.',
    image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=800&auto=format&fit=crop&q=85&v=dish-grill-gb1',
    dietary: ['non-veg'],
    prepTime: 15,
    available: true,
    customizations: [{ name: 'Add Seasoned French Fries', price: 80 }]
  },
  {
    id: 'dish-grill-gb2',
    name: 'Smokey BBQ Bacon Chicken Burger',
    category: 'pizzas',
    shopSlug: 'giri-grill',
    shopName: 'Giri Grill',
    price: 380,
    description: 'Grilled chicken patty with honey BBQ sauce, smoked bacon, crispy onion rings, and pickles.',
    image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=800&auto=format&fit=crop&q=85&v=dish-grill-gb2',
    dietary: ['non-veg', 'chef-special'],
    prepTime: 16,
    available: true,
    customizations: [{ name: 'Extra Cheddar Slice', price: 30 }]
  },
  {
    id: 'dish-grill-gb3',
    name: 'Spicy Charcoal Grilled Paneer Burger',
    category: 'pizzas',
    shopSlug: 'giri-grill',
    shopName: 'Giri Grill',
    price: 290,
    description: 'Thick grilled paneer patty topped with mint mayo, charred peppers, and cheese.',
    image: 'https://images.unsplash.com/photo-1550547660-d9450f859349?w=800&auto=format&fit=crop&q=85&v=dish-grill-gb3',
    dietary: ['veg'],
    prepTime: 14,
    available: true,
    customizations: [{ name: 'Extra Mint Mayo', price: 20 }]
  },
  {
    id: 'dish-grill-gb4',
    name: 'Ultimate Double Grilled Chicken Burger',
    category: 'pizzas',
    shopSlug: 'giri-grill',
    shopName: 'Giri Grill',
    price: 420,
    description: 'Double grilled chicken patties, double cheese, caramelized onions, and house sauce.',
    image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=800&auto=format&fit=crop&q=85&v=dish-grill-gb4',
    dietary: ['non-veg', 'chef-special'],
    prepTime: 18,
    available: true,
    customizations: [{ name: 'Extra Cheese Slice', price: 30 }]
  },

  // 14. GRILLED SANDWICHES
  {
    id: 'dish-grill-gs1',
    name: 'Artisan Grilled Chicken Club Sandwich',
    category: 'pizzas',
    shopSlug: 'giri-grill',
    shopName: 'Giri Grill',
    price: 310,
    description: 'Triple decker toasted sandwich with grilled chicken breast, egg, cheese, lettuce, and mayo.',
    image: 'https://images.unsplash.com/photo-1528735602780-2552fd46c7af?w=800&auto=format&fit=crop&q=85&v=dish-grill-gs1',
    dietary: ['non-veg'],
    prepTime: 12,
    available: true,
    customizations: [{ name: 'Side French Fries', price: 70 }]
  },
  {
    id: 'dish-grill-gs2',
    name: 'Smokey BBQ Chicken & Cheese Sandwich',
    category: 'pizzas',
    shopSlug: 'giri-grill',
    shopName: 'Giri Grill',
    price: 330,
    description: 'Shredded grilled chicken in BBQ sauce with melted mozzarella grilled golden on sourdough.',
    image: 'https://images.unsplash.com/photo-1528735602780-2552fd46c7af?w=800&auto=format&fit=crop&q=85&v=dish-grill-gs2',
    dietary: ['non-veg'],
    prepTime: 12,
    available: true,
    customizations: [{ name: 'Extra BBQ Drizzle', price: 20 }]
  },
  {
    id: 'dish-grill-gs3',
    name: 'Spiced Paneer Tikka Mayo Grilled Sandwich',
    category: 'pizzas',
    shopSlug: 'giri-grill',
    shopName: 'Giri Grill',
    price: 270,
    description: 'Grilled paneer tikka cubes with mint chutney and cheese pressed in multigrain bread.',
    image: 'https://images.unsplash.com/photo-1528735602780-2552fd46c7af?w=800&auto=format&fit=crop&q=85&v=dish-grill-gs3',
    dietary: ['veg'],
    prepTime: 10,
    available: true,
    customizations: [{ name: 'Extra Mint Dip', price: 15 }]
  },
  {
    id: 'dish-grill-gs4',
    name: 'Mediterranean Grilled Veggie & Cheese Sandwich',
    category: 'pizzas',
    shopSlug: 'giri-grill',
    shopName: 'Giri Grill',
    price: 250,
    description: 'Grilled zucchini, bell peppers, corn, and melted cheddar cheese in crusty sourdough.',
    image: 'https://images.unsplash.com/photo-1528735602780-2552fd46c7af?w=800&auto=format&fit=crop&q=85&v=dish-grill-gs4',
    dietary: ['veg'],
    prepTime: 10,
    available: true,
    customizations: [{ name: 'Extra Cheese Melt', price: 25 }]
  }
`;

const grillCode = `export const GIRI_GRILL_DISHES: MenuItem[] = [\n${completeGrillCatalog}\n];\n`;

const grillIndex = dishesContent.indexOf("export const GIRI_GRILL_DISHES");
if (grillIndex !== -1) {
  const endIndex = dishesContent.indexOf("const RAW_INITIAL_DISHES");
  dishesContent = dishesContent.substring(0, grillIndex) + grillCode + dishesContent.substring(endIndex);
} else {
  dishesContent = dishesContent.replace(
    "const RAW_INITIAL_DISHES: MenuItem[] = [",
    `${grillCode}\nconst RAW_INITIAL_DISHES: MenuItem[] = [\n  ...GIRI_GRILL_DISHES,`
  );
}

dishesContent = dishesContent.replace(
  /const versionKey = 'giri_dishes_[^']+';/,
  "const versionKey = 'giri_dishes_v34_grill_all_14_categories_populated';"
);

fs.writeFileSync(dishesPath, dishesContent, 'utf8');
console.log('Successfully updated dishes.ts with 70+ authentic Grill dishes for Giri Grill!');
