const fs = require('fs');

const dishesPath = 'c:/Users/lenovo/OneDrive/Desktop/resturant/frontend/data/dishes.ts';
let dishesContent = fs.readFileSync(dishesPath, 'utf8');

const completeSpiceGardenCatalog = `
  // ==========================================
  // GIRI SPICE GARDEN COMPLETE 85+ AUTHENTIC DISHES
  // ==========================================
  
  // 1. SOUTH INDIAN SPECIALS
  {
    id: 'dish-sg-si1',
    name: 'Special Ghee Roast Crispy Paper Masala Dosa',
    category: 'tiffins',
    shopSlug: 'giri-spice-garden',
    shopName: 'Giri Spice Garden',
    price: 190,
    description: 'Golden extra crispy fermented rice crepe roasted in pure cow ghee, stuffed with spiced potato masala, served with 3 chutneys & sambar.',
    image: 'https://images.unsplash.com/photo-1668236543090-82eba5ee5976?w=800&auto=format&fit=crop&q=85&v=dish-sg-si1',
    dietary: ['veg', 'chef-special'],
    prepTime: 12,
    available: true,
    customizations: [{ name: 'Extra Pure Ghee Drizzle', price: 25 }]
  },
  {
    id: 'dish-sg-si2',
    name: 'Soft Ghee Button Idli Sambar (12pcs)',
    category: 'tiffins',
    shopSlug: 'giri-spice-garden',
    shopName: 'Giri Spice Garden',
    price: 160,
    description: 'Mini steamed rice cakes soaked in hot aromatic lentil sambar and topped with melted cow ghee.',
    image: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?w=800&auto=format&fit=crop&q=85&v=dish-sg-si2',
    dietary: ['veg'],
    prepTime: 8,
    available: true,
    customizations: [{ name: 'Extra Gunpowder Podi', price: 20 }]
  },
  {
    id: 'dish-sg-si3',
    name: 'Crispy Medu Vada Sambar & Chutney (3pcs)',
    category: 'tiffins',
    shopSlug: 'giri-spice-garden',
    shopName: 'Giri Spice Garden',
    price: 150,
    description: 'Deep-fried crispy lentil donuts seasoned with peppercorns, curry leaves, and ginger.',
    image: 'https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?w=800&auto=format&fit=crop&q=85&v=dish-sg-si3',
    dietary: ['veg'],
    prepTime: 10,
    available: true,
    customizations: [{ name: 'Extra Coconut Chutney', price: 15 }]
  },
  {
    id: 'dish-sg-si4',
    name: 'Onion Tomato Cheese Masala Uttapam',
    category: 'tiffins',
    shopSlug: 'giri-spice-garden',
    shopName: 'Giri Spice Garden',
    price: 180,
    description: 'Thick savory pancake topped with finely chopped onions, juicy tomatoes, green chilies, and melted cheese.',
    image: 'https://images.unsplash.com/photo-1668236543090-82eba5ee5976?w=800&auto=format&fit=crop&q=85&v=dish-sg-si4',
    dietary: ['veg'],
    prepTime: 12,
    available: true,
    customizations: [{ name: 'Extra Cheese Topping', price: 30 }]
  },
  {
    id: 'dish-sg-si5',
    name: 'Andhra Special MLA Upma Pesarattu',
    category: 'tiffins',
    shopSlug: 'giri-spice-garden',
    shopName: 'Giri Spice Garden',
    price: 190,
    description: 'Green gram pesarattu dosa stuffed with ginger upma and served with spicy ginger ginger chutney.',
    image: 'https://images.unsplash.com/photo-1668236543090-82eba5ee5976?w=800&auto=format&fit=crop&q=85&v=dish-sg-si5',
    dietary: ['veg', 'chef-special'],
    prepTime: 12,
    available: true,
    customizations: [{ name: 'Extra Allam Chutney', price: 20 }]
  },
  {
    id: 'dish-sg-si6',
    name: 'Desi Ghee Cashew Ven Pongal',
    category: 'tiffins',
    shopSlug: 'giri-spice-garden',
    shopName: 'Giri Spice Garden',
    price: 170,
    description: 'Comforting rice and yellow moong dal cooked with whole black pepper, cumin, ginger, ghee, and roasted cashews.',
    image: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?w=800&auto=format&fit=crop&q=85&v=dish-sg-si6',
    dietary: ['veg'],
    prepTime: 10,
    available: true,
    customizations: [{ name: 'Extra Fried Cashews', price: 30 }]
  },

  // 2. ANDHRA SPECIALS
  {
    id: 'dish-sg-as1',
    name: 'Spicy Guntur Andhra Chicken Curry',
    category: 'mains',
    shopSlug: 'giri-spice-garden',
    shopName: 'Giri Spice Garden',
    price: 380,
    description: 'Fiery Andhra style chicken curry cooked with roasted Guntur red chilies, poppies, poppy seeds, and coconut paste.',
    image: 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?w=800&auto=format&fit=crop&q=85&v=dish-sg-as1',
    dietary: ['non-veg', 'spicy', 'chef-special'],
    prepTime: 18,
    available: true,
    customizations: [{ name: 'Extra Spicy Gravy Portion', price: 30 }]
  },
  {
    id: 'dish-sg-as2',
    name: 'Tangy Gongura Leaf Chicken Curry',
    category: 'mains',
    shopSlug: 'giri-spice-garden',
    shopName: 'Giri Spice Garden',
    price: 390,
    description: 'Traditional Andhra delicacy chicken simmered with tart sorrel leaves (gongura) and fragrant spices.',
    image: 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?w=800&auto=format&fit=crop&q=85&v=dish-sg-as2',
    dietary: ['non-veg', 'chef-special'],
    prepTime: 18,
    available: true,
    customizations: [{ name: 'Extra Gongura Paste Blend', price: 35 }]
  },
  {
    id: 'dish-sg-as3',
    name: 'Spicy Gongura Tender Mutton Roast',
    category: 'mains',
    shopSlug: 'giri-spice-garden',
    shopName: 'Giri Spice Garden',
    price: 490,
    description: 'Succulent mutton bone-in pieces slow-cooked with fresh tangy gongura leaves and green chilies.',
    image: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=800&auto=format&fit=crop&q=85&v=dish-sg-as3',
    dietary: ['non-veg', 'spicy', 'chef-special'],
    prepTime: 22,
    available: true,
    customizations: [{ name: 'Extra Mutton Gravy', price: 50 }]
  },
  {
    id: 'dish-sg-as4',
    name: 'Authentic Telangana Natu Kodi Country Chicken Curry',
    category: 'mains',
    shopSlug: 'giri-spice-garden',
    shopName: 'Giri Spice Garden',
    price: 420,
    description: 'Free-range country chicken cooked in traditional claypot with roasted coriander, coconut, and crushed black pepper.',
    image: 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?w=800&auto=format&fit=crop&q=85&v=dish-sg-as4',
    dietary: ['non-veg', 'spicy'],
    prepTime: 20,
    available: true,
    customizations: [{ name: 'Side Steamed Rice Portion', price: 40 }]
  },
  {
    id: 'dish-sg-as5',
    name: 'Andhra Style Spicy Royyala Prawn Iguru Fry',
    category: 'mains',
    shopSlug: 'giri-spice-garden',
    shopName: 'Giri Spice Garden',
    price: 460,
    description: 'Fresh prawns pan-fried in onion-tomato masala, curry leaves, green chilies, and coconut reduction.',
    image: 'https://images.unsplash.com/photo-1565680018434-b513d5e5fd47?w=800&auto=format&fit=crop&q=85&v=dish-sg-as5',
    dietary: ['non-veg', 'spicy', 'chef-special'],
    prepTime: 16,
    available: true,
    customizations: [{ name: 'Extra Prawn Pieces (4pcs)', price: 100 }]
  },

  // 3. HYDERABADI SPECIALS
  {
    id: 'dish-sg-hs1',
    name: 'Royal Hyderabadi Zafrani Chicken Dum Biryani',
    category: 'biryani',
    shopSlug: 'giri-spice-garden',
    shopName: 'Giri Spice Garden',
    price: 420,
    description: 'Long grain basmati rice and marinated chicken cooked on dum with saffron, fried onions, mint, served with mirchi ka salan & raita.',
    image: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=800&auto=format&fit=crop&q=85&v=dish-sg-hs1',
    dietary: ['non-veg', 'chef-special'],
    prepTime: 20,
    available: true,
    customizations: [{ name: 'Extra Mirchi Ka Salan', price: 30 }]
  },
  {
    id: 'dish-sg-hs2',
    name: 'Signature Hyderabadi Spicy Crispy Chicken 65',
    category: 'starters',
    shopSlug: 'giri-spice-garden',
    shopName: 'Giri Spice Garden',
    price: 340,
    description: 'Deep-fried chicken morsels tossed with red chili, curry leaves, garlic, and yogurt sauce.',
    image: 'https://images.unsplash.com/photo-1610057099443-fde8c4d50f91?w=800&auto=format&fit=crop&q=85&v=dish-sg-hs2',
    dietary: ['non-veg', 'spicy', 'chef-special'],
    prepTime: 14,
    available: true,
    customizations: [{ name: 'Extra Curry Leaf Tempering', price: 15 }]
  },
  {
    id: 'dish-sg-hs3',
    name: 'Traditional Hyderabadi Sesame Peanut Mirchi Ka Salan',
    category: 'mains',
    shopSlug: 'giri-spice-garden',
    shopName: 'Giri Spice Garden',
    price: 220,
    description: 'Large roasted green chilies simmered in rich gravy of roasted peanuts, sesame seeds, coconut, and tamarind.',
    image: 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?w=800&auto=format&fit=crop&q=85&v=dish-sg-hs3',
    dietary: ['veg', 'spicy'],
    prepTime: 12,
    available: true,
    customizations: [{ name: 'Extra Gravy Bowl', price: 30 }]
  },
  {
    id: 'dish-sg-hs4',
    name: 'Slow Cooked Royal Mutton Hyderabadi Haleem',
    category: 'mains',
    shopSlug: 'giri-spice-garden',
    shopName: 'Giri Spice Garden',
    price: 390,
    description: 'Rich paste of tender mutton, wheat, lentils, ghee, and spices slow-cooked for 12 hours, garnished with fried onions & cashews.',
    image: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=800&auto=format&fit=crop&q=85&v=dish-sg-hs4',
    dietary: ['non-veg', 'chef-special'],
    prepTime: 15,
    available: true,
    customizations: [{ name: 'Extra Desi Ghee Drizzle', price: 30 }]
  },
  {
    id: 'dish-sg-hs5',
    name: 'Royal Hyderabadi Saffron Double Ka Meetha',
    category: 'desserts',
    shopSlug: 'giri-spice-garden',
    shopName: 'Giri Spice Garden',
    price: 190,
    description: 'Golden fried bread slices soaked in cardamom-saffron milk syrup topped with thick rabri, silver leaf, and pistachios.',
    image: 'https://images.unsplash.com/photo-1587314168485-3236d6710814?w=800&auto=format&fit=crop&q=85&v=dish-sg-hs5',
    dietary: ['veg', 'chef-special'],
    prepTime: 10,
    available: true,
    customizations: [{ name: 'Extra Rabri Dip', price: 35 }]
  },

  // 4. NORTH INDIAN CURRIES
  {
    id: 'dish-sg-nc1',
    name: 'Punjabi Royal Murgh Makhani Butter Chicken',
    category: 'mains',
    shopSlug: 'giri-spice-garden',
    shopName: 'Giri Spice Garden',
    price: 440,
    description: 'Charcoal roasted tandoori chicken tikka cooked in velvety rich tomato, cream, cashew, and butter gravy.',
    image: 'https://images.unsplash.com/photo-1588166524941-3bf61a9c41db?w=800&auto=format&fit=crop&q=85&v=dish-sg-nc1',
    dietary: ['non-veg', 'chef-special'],
    prepTime: 18,
    available: true,
    customizations: [{ name: 'Extra Butter Cream Drizzle', price: 35 }]
  },
  {
    id: 'dish-sg-nc2',
    name: 'Spicy Bell Pepper Kadai Chicken Gravy',
    category: 'mains',
    shopSlug: 'giri-spice-garden',
    shopName: 'Giri Spice Garden',
    price: 390,
    description: 'Chicken pieces cooked with coarsely ground kadai spices, onions, tomatoes, and crunchy bell peppers in iron wok.',
    image: 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?w=800&auto=format&fit=crop&q=85&v=dish-sg-nc2',
    dietary: ['non-veg'],
    prepTime: 16,
    available: true,
    customizations: [{ name: 'Extra Kadai Masala', price: 20 }]
  },
  {
    id: 'dish-sg-nc3',
    name: 'Tandoori Roasted Chicken Tikka Masala',
    category: 'mains',
    shopSlug: 'giri-spice-garden',
    shopName: 'Giri Spice Garden',
    price: 410,
    description: 'Grilled chicken tikka morsels simmered in spiced onion-tomato gravy with kasuri methi.',
    image: 'https://images.unsplash.com/photo-1588166524941-3bf61a9c41db?w=800&auto=format&fit=crop&q=85&v=dish-sg-nc3',
    dietary: ['non-veg'],
    prepTime: 16,
    available: true,
    customizations: [{ name: 'Side Garlic Naan', price: 60 }]
  },
  {
    id: 'dish-sg-nc4',
    name: 'Kashmiri Royal Spiced Mutton Rogan Josh',
    category: 'mains',
    shopSlug: 'giri-spice-garden',
    shopName: 'Giri Spice Garden',
    price: 490,
    description: 'Tender lamb slow-cooked in traditional Kashmiri red gravy scented with alkanet root (ratanjot) and fennel.',
    image: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=800&auto=format&fit=crop&q=85&v=dish-sg-nc4',
    dietary: ['non-veg', 'chef-special'],
    prepTime: 22,
    available: true,
    customizations: [{ name: 'Extra Rogan Oil Drizzle', price: 30 }]
  },
  {
    id: 'dish-sg-nc5',
    name: 'Slow Cooked Creamy Desi Ghee Dal Makhani',
    category: 'mains',
    shopSlug: 'giri-spice-garden',
    shopName: 'Giri Spice Garden',
    price: 290,
    description: 'Overnight slow-cooked black lentils enriched with fresh cream, butter, and mild aromatic spices.',
    image: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=800&auto=format&fit=crop&q=85&v=dish-sg-nc5',
    dietary: ['veg', 'chef-special'],
    prepTime: 15,
    available: true,
    customizations: [{ name: 'Extra Butter Cube', price: 20 }]
  },

  // 5. PANEER SPECIALS
  {
    id: 'dish-sg-ps1',
    name: 'Creamy Shahi Paneer Butter Masala',
    category: 'mains',
    shopSlug: 'giri-spice-garden',
    shopName: 'Giri Spice Garden',
    price: 340,
    description: 'Fresh cottage cheese cubes cooked in rich tomato cashew cream gravy with butter & kasuri methi.',
    image: 'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?w=800&auto=format&fit=crop&q=85&v=dish-sg-ps1',
    dietary: ['veg', 'chef-special'],
    prepTime: 15,
    available: true,
    customizations: [{ name: 'Extra Paneer Cubes (4pcs)', price: 50 }]
  },
  {
    id: 'dish-sg-ps2',
    name: 'Spicy Capsicum Onion Kadai Paneer Gravy',
    category: 'mains',
    shopSlug: 'giri-spice-garden',
    shopName: 'Giri Spice Garden',
    price: 330,
    description: 'Paneer and bell peppers tossed in fresh ground kadai masala and thick spicy tomato onion gravy.',
    image: 'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?w=800&auto=format&fit=crop&q=85&v=dish-sg-ps2',
    dietary: ['veg'],
    prepTime: 14,
    available: true,
    customizations: [{ name: 'Extra Cheese Grating', price: 25 }]
  },
  {
    id: 'dish-sg-ps3',
    name: 'Charcoal Grilled Paneer Tikka Gravy Masala',
    category: 'mains',
    shopSlug: 'giri-spice-garden',
    shopName: 'Giri Spice Garden',
    price: 350,
    description: 'Smokey tandoori paneer tikka cubes simmered in spiced tikka gravy.',
    image: 'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?w=800&auto=format&fit=crop&q=85&v=dish-sg-ps3',
    dietary: ['veg'],
    prepTime: 15,
    available: true,
    customizations: [{ name: 'Side Butter Naan', price: 60 }]
  },
  {
    id: 'dish-sg-ps4',
    name: 'Fresh Spinach Cream Palak Paneer',
    category: 'mains',
    shopSlug: 'giri-spice-garden',
    shopName: 'Giri Spice Garden',
    price: 320,
    description: 'Soft cottage cheese cubes simmered in smooth tempered spinach puree with garlic & cream.',
    image: 'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?w=800&auto=format&fit=crop&q=85&v=dish-sg-ps4',
    dietary: ['veg'],
    prepTime: 14,
    available: true,
    customizations: [{ name: 'Extra Garlic Tempering', price: 20 }]
  },
  {
    id: 'dish-sg-ps5',
    name: 'Royal Mughlai Cashew Cream Shahi Paneer',
    category: 'mains',
    shopSlug: 'giri-spice-garden',
    shopName: 'Giri Spice Garden',
    price: 360,
    description: 'Rich white gravy made with melon seeds, cashews, saffron, cardamom, and soft paneer triangles.',
    image: 'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?w=800&auto=format&fit=crop&q=85&v=dish-sg-ps5',
    dietary: ['veg', 'chef-special'],
    prepTime: 15,
    available: true,
    customizations: [{ name: 'Silver Leaf Garnishing', price: 0 }]
  },

  // 6. VEG CURRIES
  {
    id: 'dish-sg-vc1',
    name: 'Garden Fresh Mixed Vegetable Masala Curry',
    category: 'mains',
    shopSlug: 'giri-spice-garden',
    shopName: 'Giri Spice Garden',
    price: 270,
    description: 'Assorted seasonal vegetables simmered in aromatic onion-tomato masala.',
    image: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=800&auto=format&fit=crop&q=85&v=dish-sg-vc1',
    dietary: ['veg'],
    prepTime: 12,
    available: true,
    customizations: [{ name: 'Extra Gravy Portion', price: 25 }]
  },
  {
    id: 'dish-sg-vc2',
    name: 'Yellow Arhar Dal Tadka Desi Ghee Fry',
    category: 'mains',
    shopSlug: 'giri-spice-garden',
    shopName: 'Giri Spice Garden',
    price: 220,
    description: 'Yellow lentils cooked till soft and tempered with garlic, cumin, red chili, and desi ghee.',
    image: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=800&auto=format&fit=crop&q=85&v=dish-sg-vc2',
    dietary: ['veg'],
    prepTime: 10,
    available: true,
    customizations: [{ name: 'Double Garlic Tadka', price: 20 }]
  },
  {
    id: 'dish-sg-vc3',
    name: 'Homestyle Spiced Yellow Dal Fry',
    category: 'mains',
    shopSlug: 'giri-spice-garden',
    shopName: 'Giri Spice Garden',
    price: 210,
    description: 'Simple delicious comfort yellow dal tempered with mustard seeds and curry leaves.',
    image: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=800&auto=format&fit=crop&q=85&v=dish-sg-vc3',
    dietary: ['veg'],
    prepTime: 10,
    available: true,
    customizations: [{ name: 'Side Steamed Rice', price: 40 }]
  },
  {
    id: 'dish-sg-vc4',
    name: 'Punjabi Amritsari Spicy Chana Masala',
    category: 'mains',
    shopSlug: 'giri-spice-garden',
    shopName: 'Giri Spice Garden',
    price: 240,
    description: 'Tender chickpeas cooked in dark tangy spiced tea-infused Punjabi gravy with pomegranate powder.',
    image: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=800&auto=format&fit=crop&q=85&v=dish-sg-vc4',
    dietary: ['veg'],
    prepTime: 12,
    available: true,
    customizations: [{ name: 'Side Bhatura (1pc)', price: 40 }]
  },
  {
    id: 'dish-sg-vc5',
    name: 'Roasted Potato & Cauliflower Aloo Gobi Masala',
    category: 'mains',
    shopSlug: 'giri-spice-garden',
    shopName: 'Giri Spice Garden',
    price: 230,
    description: 'Pan-roasted potatoes and cauliflower florets tossed with ginger, turmeric, and cumin.',
    image: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=800&auto=format&fit=crop&q=85&v=dish-sg-vc5',
    dietary: ['veg'],
    prepTime: 12,
    available: true,
    customizations: [{ name: 'Extra Ginger Juliennes', price: 0 }]
  },

  // 7. CHICKEN SPECIALS
  {
    id: 'dish-sg-cs1',
    name: 'Homestyle Spiced Chicken Curry Gravy',
    category: 'mains',
    shopSlug: 'giri-spice-garden',
    shopName: 'Giri Spice Garden',
    price: 350,
    description: 'Tender chicken pieces cooked in traditional Indian onion, tomato, ginger & garlic gravy.',
    image: 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?w=800&auto=format&fit=crop&q=85&v=dish-sg-cs1',
    dietary: ['non-veg'],
    prepTime: 16,
    available: true,
    customizations: [{ name: 'Extra Coriander Garnish', price: 0 }]
  },
  {
    id: 'dish-sg-cs2',
    name: 'Chettinad Crushed Black Pepper Chicken Dry',
    category: 'mains',
    shopSlug: 'giri-spice-garden',
    shopName: 'Giri Spice Garden',
    price: 370,
    description: 'South Indian style dry chicken roast tossed with freshly cracked black pepper and curry leaves.',
    image: 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?w=800&auto=format&fit=crop&q=85&v=dish-sg-cs2',
    dietary: ['non-veg', 'spicy'],
    prepTime: 15,
    available: true,
    customizations: [{ name: 'Extra Pepper Spice', price: 20 }]
  },
  {
    id: 'dish-sg-cs3',
    name: 'Indo-Chinese Spicy Garlic Chilli Chicken',
    category: 'chinese',
    shopSlug: 'giri-spice-garden',
    shopName: 'Giri Spice Garden',
    price: 330,
    description: 'Battered chicken fried crisp and wok-tossed with red chilies, soy sauce, garlic, and capsicum.',
    image: 'https://images.unsplash.com/photo-1610057099443-fde8c4d50f91?w=800&auto=format&fit=crop&q=85&v=dish-sg-cs3',
    dietary: ['non-veg', 'spicy'],
    prepTime: 14,
    available: true,
    customizations: [{ name: 'Gravy Style Option', price: 0 }]
  },
  {
    id: 'dish-sg-cs4',
    name: 'Karaikudi Roasted Spice Chicken Chettinad Curry',
    category: 'mains',
    shopSlug: 'giri-spice-garden',
    shopName: 'Giri Spice Garden',
    price: 380,
    description: 'Spicy Tamil Nadu chicken curry prepared with freshly ground roasted Chettinad masala.',
    image: 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?w=800&auto=format&fit=crop&q=85&v=dish-sg-cs4',
    dietary: ['non-veg', 'spicy', 'chef-special'],
    prepTime: 18,
    available: true,
    customizations: [{ name: 'Side Parotta (2pcs)', price: 50 }]
  },
  {
    id: 'dish-sg-cs5',
    name: 'Royal Mughlai Cashew Nut Chicken Korma',
    category: 'mains',
    shopSlug: 'giri-spice-garden',
    shopName: 'Giri Spice Garden',
    price: 390,
    description: 'Mildly spiced velvety chicken curry cooked in almond cashew paste cream gravy with kewra water.',
    image: 'https://images.unsplash.com/photo-1588166524941-3bf61a9c41db?w=800&auto=format&fit=crop&q=85&v=dish-sg-cs5',
    dietary: ['non-veg', 'chef-special'],
    prepTime: 18,
    available: true,
    customizations: [{ name: 'Extra Cashew Gravy', price: 30 }]
  },

  // 8. MUTTON SPECIALS
  {
    id: 'dish-sg-ms1',
    name: 'Spicy Desi Style Mutton Gravy Curry',
    category: 'mains',
    shopSlug: 'giri-spice-garden',
    shopName: 'Giri Spice Garden',
    price: 470,
    description: 'Slow-cooked goat meat cooked in whole Indian spices, onion, tomato, and garlic gravy.',
    image: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=800&auto=format&fit=crop&q=85&v=dish-sg-ms1',
    dietary: ['non-veg'],
    prepTime: 22,
    available: true,
    customizations: [{ name: 'Bone Juice Extra Gravy', price: 35 }]
  },
  {
    id: 'dish-sg-ms2',
    name: 'Shahi Awadhi Creamy Mutton Korma',
    category: 'mains',
    shopSlug: 'giri-spice-garden',
    shopName: 'Giri Spice Garden',
    price: 490,
    description: 'Rich Awadhi style mutton curry cooked with fried onions, yogurt, brown cashew paste, and saffron.',
    image: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=800&auto=format&fit=crop&q=85&v=dish-sg-ms2',
    dietary: ['non-veg', 'chef-special'],
    prepTime: 22,
    available: true,
    customizations: [{ name: 'Extra Saffron Essence', price: 25 }]
  },
  {
    id: 'dish-sg-ms3',
    name: 'Traditional Kashmiri Mutton Rogan Josh',
    category: 'mains',
    shopSlug: 'giri-spice-garden',
    shopName: 'Giri Spice Garden',
    price: 510,
    description: 'Authentic Kashmiri lamb curry with fennel, ginger, and vibrant Kashmiri red chilli.',
    image: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=800&auto=format&fit=crop&q=85&v=dish-sg-ms3',
    dietary: ['non-veg', 'chef-special'],
    prepTime: 22,
    available: true,
    customizations: [{ name: 'Side Naan Basket', price: 60 }]
  },
  {
    id: 'dish-sg-ms4',
    name: 'Spicy Pepper Mutton Chukka Fry',
    category: 'mains',
    shopSlug: 'giri-spice-garden',
    shopName: 'Giri Spice Garden',
    price: 480,
    description: 'Tender boneless mutton pieces dry roasted with crushed black pepper, shallots, and curry leaves.',
    image: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=800&auto=format&fit=crop&q=85&v=dish-sg-ms4',
    dietary: ['non-veg', 'spicy'],
    prepTime: 20,
    available: true,
    customizations: [{ name: 'Extra Roasted Pepper', price: 20 }]
  },
  {
    id: 'dish-sg-ms5',
    name: 'Spiced Minced Mutton Keema Matar Fry',
    category: 'mains',
    shopSlug: 'giri-spice-garden',
    shopName: 'Giri Spice Garden',
    price: 460,
    description: 'Hand-minced lamb meat cooked with sweet green peas, whole spices, and fresh cilantro.',
    image: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=800&auto=format&fit=crop&q=85&v=dish-sg-ms5',
    dietary: ['non-veg'],
    prepTime: 18,
    available: true,
    customizations: [{ name: 'Side Pav Bun (2pcs)', price: 30 }]
  },

  // 9. SEAFOOD SPECIALS
  {
    id: 'dish-sg-sf1',
    name: 'Coastal Coconut Tamarind Fish Curry',
    category: 'mains',
    shopSlug: 'giri-spice-garden',
    shopName: 'Giri Spice Garden',
    price: 420,
    description: 'Fresh king fish steaks simmered in tangy tamarind and rich coconut milk curry sauce.',
    image: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=800&auto=format&fit=crop&q=85&v=dish-sg-sf1',
    dietary: ['non-veg', 'chef-special'],
    prepTime: 18,
    available: true,
    customizations: [{ name: 'Extra Coconut Gravy', price: 30 }]
  },
  {
    id: 'dish-sg-sf2',
    name: 'Tawa Crispy Spiced King Fish Fry',
    category: 'starters',
    shopSlug: 'giri-spice-garden',
    shopName: 'Giri Spice Garden',
    price: 440,
    description: 'King fish slices marinated in red chili, ginger-garlic, lemon, and tawa fried crisp.',
    image: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=800&auto=format&fit=crop&q=85&v=dish-sg-sf2',
    dietary: ['non-veg', 'spicy'],
    prepTime: 15,
    available: true,
    customizations: [{ name: 'Lemon Slice Extra', price: 0 }]
  },
  {
    id: 'dish-sg-sf3',
    name: 'Andhra Spicy Chepala Pulusu Fish Curry',
    category: 'mains',
    shopSlug: 'giri-spice-garden',
    shopName: 'Giri Spice Garden',
    price: 450,
    description: 'Traditional Andhra fish curry cooked with raw mango, tamarind juice, and fiery red chilies.',
    image: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=800&auto=format&fit=crop&q=85&v=dish-sg-sf3',
    dietary: ['non-veg', 'spicy', 'chef-special'],
    prepTime: 18,
    available: true,
    customizations: [{ name: 'Extra Tamarind Pulusu', price: 30 }]
  },
  {
    id: 'dish-sg-sf4',
    name: 'Creamy Coconut Garlic Prawn Curry',
    category: 'mains',
    shopSlug: 'giri-spice-garden',
    shopName: 'Giri Spice Garden',
    price: 480,
    description: 'Juicy tiger prawns cooked in creamy coconut gravy tempered with mustard seeds and curry leaves.',
    image: 'https://images.unsplash.com/photo-1565680018434-b513d5e5fd47?w=800&auto=format&fit=crop&q=85&v=dish-sg-sf4',
    dietary: ['non-veg', 'chef-special'],
    prepTime: 16,
    available: true,
    customizations: [{ name: 'Extra Prawn Pieces (3pcs)', price: 90 }]
  },
  {
    id: 'dish-sg-sf5',
    name: 'Spicy Black Pepper Garlic Prawn Chukka Fry',
    category: 'starters',
    shopSlug: 'giri-spice-garden',
    shopName: 'Giri Spice Garden',
    price: 490,
    description: 'Prawns dry tossed with coarsely crushed black pepper, garlic, onion, and lime.',
    image: 'https://images.unsplash.com/photo-1565680018434-b513d5e5fd47?w=800&auto=format&fit=crop&q=85&v=dish-sg-sf5',
    dietary: ['non-veg', 'spicy'],
    prepTime: 14,
    available: true,
    customizations: [{ name: 'Extra Garlic Butter Dip', price: 30 }]
  },

  // 10. RICE & PULAO
  {
    id: 'dish-sg-rp1',
    name: 'Fragrant Cumin Tempered Jeera Rice',
    category: 'rice-meals',
    shopSlug: 'giri-spice-garden',
    shopName: 'Giri Spice Garden',
    price: 180,
    description: 'Steamed basmati rice tempered with roasted cumin seeds, ghee, and fresh coriander.',
    image: 'https://images.unsplash.com/photo-1596797038530-2c107229654b?w=800&auto=format&fit=crop&q=85&v=dish-sg-rp1',
    dietary: ['veg'],
    prepTime: 10,
    available: true,
    customizations: [{ name: 'Extra Desi Ghee Drizzle', price: 20 }]
  },
  {
    id: 'dish-sg-rp2',
    name: 'Malabar Pure Cow Ghee Cashew Rice',
    category: 'rice-meals',
    shopSlug: 'giri-spice-garden',
    shopName: 'Giri Spice Garden',
    price: 210,
    description: 'Aromatic basmati rice cooked in pure desi ghee, fried cashews, raisins, and whole cinnamon.',
    image: 'https://images.unsplash.com/photo-1596797038530-2c107229654b?w=800&auto=format&fit=crop&q=85&v=dish-sg-rp2',
    dietary: ['veg', 'chef-special'],
    prepTime: 12,
    available: true,
    customizations: [{ name: 'Extra Roasted Cashews', price: 30 }]
  },
  {
    id: 'dish-sg-rp3',
    name: 'Garden Fresh Veggie Basmati Pulao',
    category: 'rice-meals',
    shopSlug: 'giri-spice-garden',
    shopName: 'Giri Spice Garden',
    price: 220,
    description: 'Mildly spiced rice cooked with green peas, carrots, beans, paneer, and mint.',
    image: 'https://images.unsplash.com/photo-1596797038530-2c107229654b?w=800&auto=format&fit=crop&q=85&v=dish-sg-rp3',
    dietary: ['veg'],
    prepTime: 12,
    available: true,
    customizations: [{ name: 'Side Cucumber Raita', price: 25 }]
  },
  {
    id: 'dish-sg-rp4',
    name: 'Spicy Andhra Style Chicken Pulao',
    category: 'rice-meals',
    shopSlug: 'giri-spice-garden',
    shopName: 'Giri Spice Garden',
    price: 340,
    description: 'Tender chicken morsels cooked with chittimutyalu basmati rice and green chili paste.',
    image: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=800&auto=format&fit=crop&q=85&v=dish-sg-rp4',
    dietary: ['non-veg', 'spicy'],
    prepTime: 16,
    available: true,
    customizations: [{ name: 'Side Raita Tub', price: 20 }]
  },
  {
    id: 'dish-sg-rp5',
    name: 'Royal Hyderabadi Mutton Pulao',
    category: 'rice-meals',
    shopSlug: 'giri-spice-garden',
    shopName: 'Giri Spice Garden',
    price: 440,
    description: 'Fragrant mutton pulao cooked in bone broth stock, ghee, whole cardamom, and fried onions.',
    image: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=800&auto=format&fit=crop&q=85&v=dish-sg-rp5',
    dietary: ['non-veg', 'chef-special'],
    prepTime: 18,
    available: true,
    customizations: [{ name: 'Extra Salan Bowl', price: 30 }]
  },

  // 11. BIRYANI SPECIALS
  {
    id: 'dish-sg-bs1',
    name: 'Hyderabadi Special Chicken Dum Biryani',
    category: 'biryani',
    shopSlug: 'giri-spice-garden',
    shopName: 'Giri Spice Garden',
    price: 380,
    description: 'Signature Dum Biryani cooked with succulent chicken, saffron basmati rice, mint, served with raita & salan.',
    image: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=800&auto=format&fit=crop&q=85&v=dish-sg-bs1',
    dietary: ['non-veg', 'chef-special'],
    prepTime: 18,
    available: true,
    customizations: [{ name: 'Extra Chicken Piece (1pc)', price: 90 }]
  },
  {
    id: 'dish-sg-bs2',
    name: 'Royal Hyderabadi Mutton Dum Biryani',
    category: 'biryani',
    shopSlug: 'giri-spice-garden',
    shopName: 'Giri Spice Garden',
    price: 480,
    description: 'Tender lamb pieces layered with long grain basmati rice and cooked on slow dum with royal spices.',
    image: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=800&auto=format&fit=crop&q=85&v=dish-sg-bs2',
    dietary: ['non-veg', 'chef-special'],
    prepTime: 20,
    available: true,
    customizations: [{ name: 'Extra Mutton Piece (1pc)', price: 120 }]
  },
  {
    id: 'dish-sg-bs3',
    name: 'Spiced Egg Dum Biryani (2 Eggs)',
    category: 'biryani',
    shopSlug: 'giri-spice-garden',
    shopName: 'Giri Spice Garden',
    price: 280,
    description: 'Boiled eggs seared in chili masala and layered with saffron dum biryani rice.',
    image: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=800&auto=format&fit=crop&q=85&v=dish-sg-bs3',
    dietary: ['non-veg'],
    prepTime: 14,
    available: true,
    customizations: [{ name: 'Extra Boiled Egg (1pc)', price: 25 }]
  },
  {
    id: 'dish-sg-bs4',
    name: 'Tandoori Paneer Tikka Dum Biryani',
    category: 'biryani',
    shopSlug: 'giri-spice-garden',
    shopName: 'Giri Spice Garden',
    price: 320,
    description: 'Charcoal grilled cottage cheese tikka layered with fragrant biryani rice, mint, and caramelized onions.',
    image: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=800&auto=format&fit=crop&q=85&v=dish-sg-bs4',
    dietary: ['veg'],
    prepTime: 16,
    available: true,
    customizations: [{ name: 'Extra Paneer Pieces', price: 40 }]
  },
  {
    id: 'dish-sg-bs5',
    name: 'Coastal King Prawn Basmati Biryani',
    category: 'biryani',
    shopSlug: 'giri-spice-garden',
    shopName: 'Giri Spice Garden',
    price: 490,
    description: 'Jumbo prawns marinated in coastal spices and dum cooked with fragrant basmati rice.',
    image: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=800&auto=format&fit=crop&q=85&v=dish-sg-bs5',
    dietary: ['non-veg', 'chef-special'],
    prepTime: 20,
    available: true,
    customizations: [{ name: 'Extra Prawns (3pcs)', price: 100 }]
  },

  // 12. INDIAN BREADS
  {
    id: 'dish-sg-ib1',
    name: 'Tandoori Soft Butter Naan',
    category: 'mains',
    shopSlug: 'giri-spice-garden',
    shopName: 'Giri Spice Garden',
    price: 60,
    description: 'Leavened refined flour flatbread baked fresh in clay tandoor and brushed with butter.',
    image: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?w=800&auto=format&fit=crop&q=85&v=dish-sg-ib1',
    dietary: ['veg'],
    prepTime: 5,
    available: true,
    customizations: [{ name: 'Extra Butter Spread', price: 10 }]
  },
  {
    id: 'dish-sg-ib2',
    name: 'Roasted Garlic Butter Naan',
    category: 'mains',
    shopSlug: 'giri-spice-garden',
    shopName: 'Giri Spice Garden',
    price: 75,
    description: 'Tandoori naan topped with roasted garlic flakes, fresh coriander, and melted butter.',
    image: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?w=800&auto=format&fit=crop&q=85&v=dish-sg-ib2',
    dietary: ['veg', 'chef-special'],
    prepTime: 6,
    available: true,
    customizations: [{ name: 'Extra Roasted Garlic', price: 15 }]
  },
  {
    id: 'dish-sg-ib3',
    name: 'Whole Wheat Tandoori Roti',
    category: 'mains',
    shopSlug: 'giri-spice-garden',
    shopName: 'Giri Spice Garden',
    price: 40,
    description: 'Healthy whole wheat flour flatbread baked in clay oven tandoor.',
    image: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?w=800&auto=format&fit=crop&q=85&v=dish-sg-ib3',
    dietary: ['veg'],
    prepTime: 4,
    available: true,
    customizations: [{ name: 'Butter Toasting', price: 10 }]
  },
  {
    id: 'dish-sg-ib4',
    name: 'Multi-Layered Crispy Laccha Paratha',
    category: 'mains',
    shopSlug: 'giri-spice-garden',
    shopName: 'Giri Spice Garden',
    price: 65,
    description: 'Flaky multi-layered tandoori paratha brushed with melted butter.',
    image: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?w=800&auto=format&fit=crop&q=85&v=dish-sg-ib4',
    dietary: ['veg'],
    prepTime: 6,
    available: true,
    customizations: [{ name: 'Ajwain Flavoring', price: 10 }]
  },
  {
    id: 'dish-sg-ib5',
    name: 'Soft Tandoori Butter Roti',
    category: 'mains',
    shopSlug: 'giri-spice-garden',
    shopName: 'Giri Spice Garden',
    price: 45,
    description: 'Tandoori whole wheat roti generously brushed with cow butter.',
    image: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?w=800&auto=format&fit=crop&q=85&v=dish-sg-ib5',
    dietary: ['veg'],
    prepTime: 4,
    available: true,
    customizations: [{ name: 'Extra Butter Portion', price: 10 }]
  },

  // 13. SPICE GARDEN STARTERS
  {
    id: 'dish-sg-st1',
    name: 'Spicy Indo-Chinese Crispy Pepper Corn',
    category: 'starters',
    shopSlug: 'giri-spice-garden',
    shopName: 'Giri Spice Garden',
    price: 240,
    description: 'Crispy fried sweet corn kernels tossed with black pepper, spring onions, and garlic.',
    image: 'https://images.unsplash.com/photo-1551782450-a2132b4ba21d?w=800&auto=format&fit=crop&q=85&v=dish-sg-st1',
    dietary: ['veg'],
    prepTime: 10,
    available: true,
    customizations: [{ name: 'Extra Lemon Spice Sprinkle', price: 0 }]
  },
  {
    id: 'dish-sg-st2',
    name: 'Crispy Spiced Curry Leaf Paneer 65',
    category: 'starters',
    shopSlug: 'giri-spice-garden',
    shopName: 'Giri Spice Garden',
    price: 280,
    description: 'Paneer cubes fried crisp and tossed in south Indian chili garlic 65 sauce with curry leaves.',
    image: 'https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?w=800&auto=format&fit=crop&q=85&v=dish-sg-st2',
    dietary: ['veg', 'spicy'],
    prepTime: 12,
    available: true,
    customizations: [{ name: 'Mint Chutney Tub', price: 15 }]
  },
  {
    id: 'dish-sg-st3',
    name: 'Crispy Fried Spiced Gobi 65',
    category: 'starters',
    shopSlug: 'giri-spice-garden',
    shopName: 'Giri Spice Garden',
    price: 220,
    description: 'Cauliflower florets marinated in spicy red batter and fried till crunchy.',
    image: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=800&auto=format&fit=crop&q=85&v=dish-sg-st3',
    dietary: ['veg'],
    prepTime: 12,
    available: true,
    customizations: [{ name: 'Chili Mayo Dip', price: 20 }]
  },
  {
    id: 'dish-sg-st4',
    name: 'Classic Spicy Hyderabadi Chicken 65',
    category: 'starters',
    shopSlug: 'giri-spice-garden',
    shopName: 'Giri Spice Garden',
    price: 320,
    description: 'Juicy chicken morsels spiced with red chili, curd, garlic, and fried with green chilies & curry leaves.',
    image: 'https://images.unsplash.com/photo-1610057099443-fde8c4d50f91?w=800&auto=format&fit=crop&q=85&v=dish-sg-st4',
    dietary: ['non-veg', 'spicy', 'chef-special'],
    prepTime: 14,
    available: true,
    customizations: [{ name: 'Extra Green Chili Tempering', price: 15 }]
  },
  {
    id: 'dish-sg-st5',
    name: 'Crispy Battered Spiced Fish 65 Bites',
    category: 'starters',
    shopSlug: 'giri-spice-garden',
    shopName: 'Giri Spice Garden',
    price: 360,
    description: 'Boneless fish nuggets coated in South Indian 65 spices and fried golden crisp.',
    image: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=800&auto=format&fit=crop&q=85&v=dish-sg-st5',
    dietary: ['non-veg'],
    prepTime: 14,
    available: true,
    customizations: [{ name: 'Tartar Sauce Dip', price: 25 }]
  },

  // 14. KEBABS & TIKKAS
  {
    id: 'dish-sg-kt1',
    name: 'Charcoal Roasted Tandoori Chicken Tikka',
    category: 'starters',
    shopSlug: 'giri-spice-garden',
    shopName: 'Giri Spice Garden',
    price: 360,
    description: 'Boneless chicken cubes marinated in hung curd, Kashmiri chili, mustard oil, and tandoor roasted.',
    image: 'https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?w=800&auto=format&fit=crop&q=85&v=dish-sg-kt1',
    dietary: ['non-veg'],
    prepTime: 15,
    available: true,
    customizations: [{ name: 'Mint Chutney', price: 15 }]
  },
  {
    id: 'dish-sg-kt2',
    name: 'Mint Spinach Hariyali Chicken Kebab',
    category: 'starters',
    shopSlug: 'giri-spice-garden',
    shopName: 'Giri Spice Garden',
    price: 370,
    description: 'Succulent chicken pieces coated in mint, cilantro, green chili, and roasted cumin paste.',
    image: 'https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?w=800&auto=format&fit=crop&q=85&v=dish-sg-kt2',
    dietary: ['non-veg'],
    prepTime: 15,
    available: true,
    customizations: [{ name: 'Extra Mint Dip', price: 20 }]
  },
  {
    id: 'dish-sg-kt3',
    name: 'Soft Creamy Cashew Reshmi Kebab',
    category: 'starters',
    shopSlug: 'giri-spice-garden',
    shopName: 'Giri Spice Garden',
    price: 390,
    description: 'Melt-in-mouth chicken kebabs marinated in cashew paste, cream, and egg white.',
    image: 'https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?w=800&auto=format&fit=crop&q=85&v=dish-sg-kt3',
    dietary: ['non-veg', 'chef-special'],
    prepTime: 16,
    available: true,
    customizations: [{ name: 'Butter Drizzle', price: 20 }]
  },
  {
    id: 'dish-sg-kt4',
    name: 'Classic Tandoori Paneer Tikka (8pcs)',
    category: 'starters',
    shopSlug: 'giri-spice-garden',
    shopName: 'Giri Spice Garden',
    price: 320,
    description: 'Fresh cottage cheese blocks skewered with bell peppers and onions, tandoor grilled.',
    image: 'https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?w=800&auto=format&fit=crop&q=85&v=dish-sg-kt4',
    dietary: ['veg'],
    prepTime: 14,
    available: true,
    customizations: [{ name: 'Extra Mint Sauce', price: 15 }]
  },
  {
    id: 'dish-sg-kt5',
    name: 'Spiced Minced Mutton Seekh Kebab',
    category: 'starters',
    shopSlug: 'giri-spice-garden',
    shopName: 'Giri Spice Garden',
    price: 460,
    description: 'Minced lamb blended with herbs and spices, grilled on iron skewers over charcoal coals.',
    image: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=800&auto=format&fit=crop&q=85&v=dish-sg-kt5',
    dietary: ['non-veg', 'chef-special'],
    prepTime: 18,
    available: true,
    customizations: [{ name: 'Rumali Roti Side', price: 30 }]
  },

  // 15. TRADITIONAL SPECIALS
  {
    id: 'dish-sg-ts1',
    name: 'Rajasthani Royal Dal Baati Churma',
    category: 'mains',
    shopSlug: 'giri-spice-garden',
    shopName: 'Giri Spice Garden',
    price: 340,
    description: 'Traditional baked wheat flour balls (baati) soaked in pure desi ghee, served with Panchmel Dal and sweet crushed wheat Churma.',
    image: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=800&auto=format&fit=crop&q=85&v=dish-sg-ts1',
    dietary: ['veg', 'chef-special'],
    prepTime: 18,
    available: true,
    customizations: [{ name: 'Extra Desi Ghee Bowl', price: 30 }]
  },
  {
    id: 'dish-sg-ts2',
    name: 'Punjabi Fluffy Bhature with Chole Masala (2pcs)',
    category: 'mains',
    shopSlug: 'giri-spice-garden',
    shopName: 'Giri Spice Garden',
    price: 220,
    description: 'Large deep-fried puffed bhatura served with spicy Punjabi chickpea masala, fried chili, and pickle.',
    image: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=800&auto=format&fit=crop&q=85&v=dish-sg-ts2',
    dietary: ['veg'],
    prepTime: 12,
    available: true,
    customizations: [{ name: 'Extra Bhatura (1pc)', price: 40 }]
  },
  {
    id: 'dish-sg-ts3',
    name: 'Punjabi Jammu Rajma Rasila Masala',
    category: 'mains',
    shopSlug: 'giri-spice-garden',
    shopName: 'Giri Spice Garden',
    price: 210,
    description: 'Red kidney beans slow-cooked in thick onion, tomato, and ginger gravy with aromatic garam masala.',
    image: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=800&auto=format&fit=crop&q=85&v=dish-sg-ts3',
    dietary: ['veg'],
    prepTime: 12,
    available: true,
    customizations: [{ name: 'Side Steamed Rice', price: 40 }]
  },
  {
    id: 'dish-sg-ts4',
    name: 'Rich Mughlai Creamy Cashew Malai Kofta',
    category: 'mains',
    shopSlug: 'giri-spice-garden',
    shopName: 'Giri Spice Garden',
    price: 330,
    description: 'Deep-fried cottage cheese & potato dumplings stuffed with dry fruits, simmered in rich creamy white cashew gravy.',
    image: 'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?w=800&auto=format&fit=crop&q=85&v=dish-sg-ts4',
    dietary: ['veg', 'chef-special'],
    prepTime: 16,
    available: true,
    customizations: [{ name: 'Extra Malai Cream', price: 25 }]
  },
  {
    id: 'dish-sg-ts5',
    name: 'Spiced Mixed Vegetable Kofta Gravy',
    category: 'mains',
    shopSlug: 'giri-spice-garden',
    shopName: 'Giri Spice Garden',
    price: 280,
    description: 'Fried vegetable balls simmered in tangy spiced onion tomato gravy.',
    image: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=800&auto=format&fit=crop&q=85&v=dish-sg-ts5',
    dietary: ['veg'],
    prepTime: 14,
    available: true,
    customizations: [{ name: 'Extra Gravy Bowl', price: 25 }]
  },

  // 16. DESSERTS
  {
    id: 'dish-sg-ds1',
    name: 'Warm Desi Ghee Gulab Jamun (2pcs)',
    category: 'desserts',
    shopSlug: 'giri-spice-garden',
    shopName: 'Giri Spice Garden',
    price: 120,
    description: 'Soft fried khoya milk solids soaked in rose cardamom sugar syrup.',
    image: 'https://images.unsplash.com/photo-1587314168485-3236d6710814?w=800&auto=format&fit=crop&q=85&v=dish-sg-ds1',
    dietary: ['veg'],
    prepTime: 5,
    available: true,
    customizations: [{ name: 'Add Vanilla Ice Cream Scoop', price: 40 }]
  },
  {
    id: 'dish-sg-ds2',
    name: 'Soft Saffron Pistachio Milk Rasmalai (2pcs)',
    category: 'desserts',
    shopSlug: 'giri-spice-garden',
    shopName: 'Giri Spice Garden',
    price: 150,
    description: 'Spongy cottage cheese patties soaked in chilled saffron-infused thickened milk garnished with pistachios.',
    image: 'https://images.unsplash.com/photo-1587314168485-3236d6710814?w=800&auto=format&fit=crop&q=85&v=dish-sg-ds2',
    dietary: ['veg', 'chef-special'],
    prepTime: 5,
    available: true,
    customizations: [{ name: 'Extra Saffron Milk Drizzle', price: 20 }]
  },
  {
    id: 'dish-sg-ds3',
    name: 'Hyderabadi Fried Bread Saffron Rabri Meetha',
    category: 'desserts',
    shopSlug: 'giri-spice-garden',
    shopName: 'Giri Spice Garden',
    price: 160,
    description: 'Golden fried bread triangles soaked in thick rabri, silver leaf, almond flakes & pistachios.',
    image: 'https://images.unsplash.com/photo-1587314168485-3236d6710814?w=800&auto=format&fit=crop&q=85&v=dish-sg-ds3',
    dietary: ['veg'],
    prepTime: 8,
    available: true,
    customizations: [{ name: 'Extra Rabri Portion', price: 30 }]
  },
  {
    id: 'dish-sg-ds4',
    name: 'Desi Ghee Red Carrot Halwa',
    category: 'desserts',
    shopSlug: 'giri-spice-garden',
    shopName: 'Giri Spice Garden',
    price: 140,
    description: 'Grated fresh red carrots simmered in milk, khoya, pure ghee, cardamom, and roasted nuts.',
    image: 'https://images.unsplash.com/photo-1587314168485-3236d6710814?w=800&auto=format&fit=crop&q=85&v=dish-sg-ds4',
    dietary: ['veg'],
    prepTime: 5,
    available: true,
    customizations: [{ name: 'Extra Roasted Almonds', price: 20 }]
  },
  {
    id: 'dish-sg-ds5',
    name: 'Traditional Malai Pista Matka Kulfi',
    category: 'desserts',
    shopSlug: 'giri-spice-garden',
    shopName: 'Giri Spice Garden',
    price: 110,
    description: 'Rich dense frozen cream kulfi flavored with saffron, cardamom, and chopped pistachios served in earthenware matka.',
    image: 'https://images.unsplash.com/photo-1587314168485-3236d6710814?w=800&auto=format&fit=crop&q=85&v=dish-sg-ds5',
    dietary: ['veg'],
    prepTime: 3,
    available: true,
    customizations: [{ name: 'Extra Rose Falooda Drizzle', price: 25 }]
  },

  // 17. BEVERAGES
  {
    id: 'dish-sg-bv1',
    name: 'Kulhad Ginger Cardamom Masala Chai',
    category: 'drinks',
    shopSlug: 'giri-spice-garden',
    shopName: 'Giri Spice Garden',
    price: 60,
    description: 'Traditional Indian milk tea brewed with fresh crushed ginger, cardamom, and spices served in clay kulhad cup.',
    image: 'https://images.unsplash.com/photo-1517701604599-bb29b565090c?w=800&auto=format&fit=crop&q=85&v=dish-sg-bv1',
    dietary: ['veg'],
    prepTime: 5,
    available: true,
    customizations: [{ name: 'Less Sugar Option', price: 0 }]
  },
  {
    id: 'dish-sg-bv2',
    name: 'Authentic South Indian Brass Filter Coffee',
    category: 'drinks',
    shopSlug: 'giri-spice-garden',
    shopName: 'Giri Spice Garden',
    price: 70,
    description: 'Strong frothy coffee brewed using traditional brass filter decoction and whole fat milk.',
    image: 'https://images.unsplash.com/photo-1517701604599-bb29b565090c?w=800&auto=format&fit=crop&q=85&v=dish-sg-bv2',
    dietary: ['veg', 'chef-special'],
    prepTime: 5,
    available: true,
    customizations: [{ name: 'Extra Strong Decoction', price: 0 }]
  },
  {
    id: 'dish-sg-bv3',
    name: 'Alphonso Mango Cream Sweet Lassi',
    category: 'drinks',
    shopSlug: 'giri-spice-garden',
    shopName: 'Giri Spice Garden',
    price: 110,
    description: 'Thick chilled sweet yogurt lassi blended with Alphonso mango pulp and topped with malai.',
    image: 'https://images.unsplash.com/photo-1517701604599-bb29b565090c?w=800&auto=format&fit=crop&q=85&v=dish-sg-bv3',
    dietary: ['veg'],
    prepTime: 5,
    available: true,
    customizations: [{ name: 'Extra Mango Pulp', price: 20 }]
  },
  {
    id: 'dish-sg-bv4',
    name: 'Chilled Punjabi Sweet Yogurt Lassi',
    category: 'drinks',
    shopSlug: 'giri-spice-garden',
    shopName: 'Giri Spice Garden',
    price: 90,
    description: 'Traditional thick churned sweet yogurt drink garnished with cardamom and fresh cream.',
    image: 'https://images.unsplash.com/photo-1517701604599-bb29b565090c?w=800&auto=format&fit=crop&q=85&v=dish-sg-bv4',
    dietary: ['veg'],
    prepTime: 4,
    available: true,
    customizations: [{ name: 'Side Rose Syrup', price: 15 }]
  },
  {
    id: 'dish-sg-bv5',
    name: 'Sparkling Sweet & Salt Fresh Lime Soda',
    category: 'drinks',
    shopSlug: 'giri-spice-garden',
    shopName: 'Giri Spice Garden',
    price: 80,
    description: 'Refreshing chilled soda water mixed with fresh lime juice, sugar, and black salt.',
    image: 'https://images.unsplash.com/photo-1517701604599-bb29b565090c?w=800&auto=format&fit=crop&q=85&v=dish-sg-bv5',
    dietary: ['veg'],
    prepTime: 4,
    available: true,
    customizations: [{ name: 'Mint Leaves Infusion', price: 10 }]
  }
`;

const spiceGardenCode = `export const GIRI_SPICE_GARDEN_DISHES: MenuItem[] = [\n${completeSpiceGardenCatalog}\n];\n`;

const sgIndex = dishesContent.indexOf("export const GIRI_SPICE_GARDEN_DISHES");
if (sgIndex !== -1) {
  const endIndex = dishesContent.indexOf("const RAW_INITIAL_DISHES");
  dishesContent = dishesContent.substring(0, sgIndex) + spiceGardenCode + dishesContent.substring(endIndex);
} else {
  dishesContent = dishesContent.replace(
    "const RAW_INITIAL_DISHES: MenuItem[] = [",
    `${spiceGardenCode}\nconst RAW_INITIAL_DISHES: MenuItem[] = [\n  ...GIRI_SPICE_GARDEN_DISHES,`
  );
}

dishesContent = dishesContent.replace(
  /const versionKey = 'giri_dishes_[^']+';/,
  "const versionKey = 'giri_dishes_v35_spice_garden_all_17_categories_populated';"
);

fs.writeFileSync(dishesPath, dishesContent, 'utf8');
console.log('Successfully updated dishes.ts with 85+ authentic dishes for Giri Spice Garden!');
