const fs = require('fs');

const dishesPath = 'c:/Users/lenovo/OneDrive/Desktop/resturant/frontend/data/dishes.ts';
let dishesContent = fs.readFileSync(dishesPath, 'utf8');

const completeCafeCatalog = `
  // ==========================================
  // GIRI CAFE COMPLETE 100+ AUTHENTIC ITEMS
  // ==========================================

  // 1. HOT COFFEE
  {
    id: 'dish-cf-hc1',
    name: 'Artisan Single Origin Espresso Shot',
    category: 'drinks',
    shopSlug: 'giri-cafe',
    shopName: 'Giri Café',
    price: 120,
    description: 'Concentrated shot of 100% Arabica dark roast coffee with golden crema layer.',
    image: 'https://images.unsplash.com/photo-1510591509098-f4fdc6d0ff04?w=800&auto=format&fit=crop&q=85&v=dish-cf-hc1',
    dietary: ['veg', 'chef-special'],
    prepTime: 4,
    available: true,
    customizations: [{ name: 'Double Shot (Doppio)', price: 40 }]
  },
  {
    id: 'dish-cf-hc2',
    name: 'Classic Hot Dark Roast Americano',
    category: 'drinks',
    shopSlug: 'giri-cafe',
    shopName: 'Giri Café',
    price: 140,
    description: 'Espresso shot diluted with hot filtered water for a clean bold coffee flavor.',
    image: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=800&auto=format&fit=crop&q=85&v=dish-cf-hc2',
    dietary: ['veg'],
    prepTime: 5,
    available: true,
    customizations: [{ name: 'Extra Shot Espresso', price: 35 }]
  },
  {
    id: 'dish-cf-hc3',
    name: 'Creamy Frothy Milk Cappuccino',
    category: 'drinks',
    shopSlug: 'giri-cafe',
    shopName: 'Giri Café',
    price: 160,
    description: 'Equal parts espresso, steamed milk, and velvety thick milk foam dusted with cocoa powder.',
    image: 'https://images.unsplash.com/photo-1572442388796-11668a67e53d?w=800&auto=format&fit=crop&q=85&v=dish-cf-hc3',
    dietary: ['veg', 'chef-special'],
    prepTime: 6,
    available: true,
    customizations: [{ name: 'Cinnamon Dusting', price: 0 }]
  },
  {
    id: 'dish-cf-hc4',
    name: 'Velvety Smooth Hot Cafe Latte',
    category: 'drinks',
    shopSlug: 'giri-cafe',
    shopName: 'Giri Café',
    price: 170,
    description: 'Espresso combined with steamed milk and a delicate top layer of microfoam latte art.',
    image: 'https://images.unsplash.com/photo-1534778101976-62847782c213?w=800&auto=format&fit=crop&q=85&v=dish-cf-hc4',
    dietary: ['veg'],
    prepTime: 6,
    available: true,
    customizations: [{ name: 'Oat Milk Substitute', price: 30 }]
  },
  {
    id: 'dish-cf-hc5',
    name: 'Rich Belgian Dark Chocolate Cafe Mocha',
    category: 'drinks',
    shopSlug: 'giri-cafe',
    shopName: 'Giri Café',
    price: 190,
    description: 'Espresso blended with Belgian dark chocolate sauce, steamed milk, topped with whipped cream.',
    image: 'https://images.unsplash.com/photo-1578314675249-a6910f80cc4e?w=800&auto=format&fit=crop&q=85&v=dish-cf-hc5',
    dietary: ['veg', 'chef-special'],
    prepTime: 7,
    available: true,
    customizations: [{ name: 'Extra Whipped Cream', price: 25 }]
  },
  {
    id: 'dish-cf-hc6',
    name: 'Microfoam Ristretto Flat White Coffee',
    category: 'drinks',
    shopSlug: 'giri-cafe',
    shopName: 'Giri Café',
    price: 175,
    description: 'Double ristretto shot topped with velvety smooth steamed whole milk.',
    image: 'https://images.unsplash.com/photo-1577968897966-3d4325b36b61?w=800&auto=format&fit=crop&q=85&v=dish-cf-hc6',
    dietary: ['veg'],
    prepTime: 5,
    available: true,
    customizations: [{ name: 'Almond Milk Option', price: 30 }]
  },
  {
    id: 'dish-cf-hc7',
    name: 'Espresso Macchiato with Milk Foam',
    category: 'drinks',
    shopSlug: 'giri-cafe',
    shopName: 'Giri Café',
    price: 150,
    description: 'Bold espresso shot marked with a dollop of warm thick milk foam.',
    image: 'https://images.unsplash.com/photo-1485808191679-5f86510681a2?w=800&auto=format&fit=crop&q=85&v=dish-cf-hc7',
    dietary: ['veg'],
    prepTime: 4,
    available: true,
    customizations: [{ name: 'Extra Foam', price: 10 }]
  },
  {
    id: 'dish-cf-hc8',
    name: 'South Indian Artisan Filter Coffee',
    category: 'drinks',
    shopSlug: 'giri-cafe',
    shopName: 'Giri Café',
    price: 110,
    description: 'Traditional decoction brewed with chicory and frothed with hot boiled whole milk.',
    image: 'https://images.unsplash.com/photo-1517701604599-bb29b565090c?w=800&auto=format&fit=crop&q=85&v=dish-cf-hc8',
    dietary: ['veg'],
    prepTime: 5,
    available: true,
    customizations: [{ name: 'Brass Dabara Cup Serve', price: 0 }]
  },

  // 2. SPECIALTY COFFEE
  {
    id: 'dish-cf-sc1',
    name: 'Salted Caramel Drizzle Cafe Latte',
    category: 'drinks',
    shopSlug: 'giri-cafe',
    shopName: 'Giri Café',
    price: 210,
    description: 'Espresso and steamed milk infused with buttery salted caramel syrup and caramel drizzle.',
    image: 'https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=800&auto=format&fit=crop&q=85&v=dish-cf-sc1',
    dietary: ['veg', 'chef-special'],
    prepTime: 7,
    available: true,
    customizations: [{ name: 'Extra Caramel Sauce', price: 20 }]
  },
  {
    id: 'dish-cf-sc2',
    name: 'Roasted Hazelnut Infused Espresso Latte',
    category: 'drinks',
    shopSlug: 'giri-cafe',
    shopName: 'Giri Café',
    price: 220,
    description: 'Rich espresso and steamed milk flavored with roasted nut hazelnut syrup.',
    image: 'https://images.unsplash.com/photo-1534778101976-62847782c213?w=800&auto=format&fit=crop&q=85&v=dish-cf-sc2',
    dietary: ['veg'],
    prepTime: 6,
    available: true,
    customizations: [{ name: 'Crushed Hazelnut Topping', price: 25 }]
  },
  {
    id: 'dish-cf-sc3',
    name: 'French Vanilla Bean Cafe Latte',
    category: 'drinks',
    shopSlug: 'giri-cafe',
    shopName: 'Giri Café',
    price: 200,
    description: 'Espresso latte sweetened with natural Madagascar vanilla bean syrup.',
    image: 'https://images.unsplash.com/photo-1572442388796-11668a67e53d?w=800&auto=format&fit=crop&q=85&v=dish-cf-sc3',
    dietary: ['veg'],
    prepTime: 6,
    available: true,
    customizations: [{ name: 'Extra Syrup Shot', price: 20 }]
  },
  {
    id: 'dish-cf-sc4',
    name: 'Irish Cream Flavored Hot Espresso',
    category: 'drinks',
    shopSlug: 'giri-cafe',
    shopName: 'Giri Café',
    price: 230,
    description: 'Creamy non-alcoholic Irish cream syrup infused in hot espresso latte.',
    image: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=800&auto=format&fit=crop&q=85&v=dish-cf-sc4',
    dietary: ['veg'],
    prepTime: 6,
    available: true,
    customizations: [{ name: 'Whipped Cream Top', price: 25 }]
  },
  {
    id: 'dish-cf-sc5',
    name: 'Spiced Cinnamon Bark Hot Latte',
    category: 'drinks',
    shopSlug: 'giri-cafe',
    shopName: 'Giri Café',
    price: 195,
    description: 'Fresh espresso and milk infused with Ceylon cinnamon syrup and nutmeg dusting.',
    image: 'https://images.unsplash.com/photo-1510591509098-f4fdc6d0ff04?w=800&auto=format&fit=crop&q=85&v=dish-cf-sc5',
    dietary: ['veg'],
    prepTime: 6,
    available: true,
    customizations: [{ name: 'Honey Sweetener', price: 15 }]
  },
  {
    id: 'dish-cf-sc6',
    name: 'Giri Signature Gold Dust Cappuccino',
    category: 'drinks',
    shopSlug: 'giri-cafe',
    shopName: 'Giri Café',
    price: 250,
    description: 'House special triple shot cappuccino dusted with edible 24K gold flakes & cocoa.',
    image: 'https://images.unsplash.com/photo-1572442388796-11668a67e53d?w=800&auto=format&fit=crop&q=85&v=dish-cf-sc6',
    dietary: ['veg', 'chef-special'],
    prepTime: 8,
    available: true,
    customizations: [{ name: 'Extra Gold Flake Dust', price: 0 }]
  },

  // 3. COLD COFFEE
  {
    id: 'dish-cf-cc1',
    name: 'Classic Chilled Thick Cold Coffee',
    category: 'drinks',
    shopSlug: 'giri-cafe',
    shopName: 'Giri Café',
    price: 180,
    description: 'Blended espresso, chilled milk, vanilla ice cream, and chocolate drizzle.',
    image: 'https://images.unsplash.com/photo-1517701604599-bb29b565090c?w=800&auto=format&fit=crop&q=85&v=dish-cf-cc1',
    dietary: ['veg', 'chef-special'],
    prepTime: 6,
    available: true,
    customizations: [{ name: 'Add Ice Cream Scoop', price: 35 }]
  },
  {
    id: 'dish-cf-cc2',
    name: 'Chilled Espresso Iced Americano',
    category: 'drinks',
    shopSlug: 'giri-cafe',
    shopName: 'Giri Café',
    price: 150,
    description: 'Double espresso poured over ice cubes and cold spring water.',
    image: 'https://images.unsplash.com/photo-1517701604599-bb29b565090c?w=800&auto=format&fit=crop&q=85&v=dish-cf-cc2',
    dietary: ['veg'],
    prepTime: 4,
    available: true,
    customizations: [{ name: 'Lemon Slice Twist', price: 10 }]
  },
  {
    id: 'dish-cf-cc3',
    name: 'Refreshing Cold Milk Iced Latte',
    category: 'drinks',
    shopSlug: 'giri-cafe',
    shopName: 'Giri Café',
    price: 185,
    description: 'Espresso layered over cold whole milk and ice cubes.',
    image: 'https://images.unsplash.com/photo-1517701604599-bb29b565090c?w=800&auto=format&fit=crop&q=85&v=dish-cf-cc3',
    dietary: ['veg'],
    prepTime: 5,
    available: true,
    customizations: [{ name: 'Vanilla Syrup Shot', price: 20 }]
  },
  {
    id: 'dish-cf-cc4',
    name: 'Iced Dark Chocolate Espresso Mocha',
    category: 'drinks',
    shopSlug: 'giri-cafe',
    shopName: 'Giri Café',
    price: 210,
    description: 'Espresso, dark chocolate syrup, chilled milk poured over ice.',
    image: 'https://images.unsplash.com/photo-1517701604599-bb29b565090c?w=800&auto=format&fit=crop&q=85&v=dish-cf-cc4',
    dietary: ['veg'],
    prepTime: 6,
    available: true,
    customizations: [{ name: 'Extra Chocolate Drizzle', price: 15 }]
  },
  {
    id: 'dish-cf-cc5',
    name: 'Creamy Blended Espresso Frappe',
    category: 'drinks',
    shopSlug: 'giri-cafe',
    shopName: 'Giri Café',
    price: 220,
    description: 'Blended ice espresso shake topped with thick whipped cream.',
    image: 'https://images.unsplash.com/photo-1517701604599-bb29b565090c?w=800&auto=format&fit=crop&q=85&v=dish-cf-cc5',
    dietary: ['veg'],
    prepTime: 7,
    available: true,
    customizations: [{ name: 'Chocolate Chips Top', price: 20 }]
  },
  {
    id: 'dish-cf-cc6',
    name: 'Blended Salted Caramel Crunch Frappe',
    category: 'drinks',
    shopSlug: 'giri-cafe',
    shopName: 'Giri Café',
    price: 240,
    description: 'Caramel coffee frappe blended with crushed butterscotch and whipped cream.',
    image: 'https://images.unsplash.com/photo-1517701604599-bb29b565090c?w=800&auto=format&fit=crop&q=85&v=dish-cf-cc6',
    dietary: ['veg', 'chef-special'],
    prepTime: 7,
    available: true,
    customizations: [{ name: 'Extra Caramel Drizzle', price: 20 }]
  },

  // 4. TEA
  {
    id: 'dish-cf-te1',
    name: 'Kulhad Spiced Ginger Masala Chai',
    category: 'drinks',
    shopSlug: 'giri-cafe',
    shopName: 'Giri Café',
    price: 80,
    description: 'Fresh ginger, cardamom, clove infused milk tea served in traditional clay pot.',
    image: 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?w=800&auto=format&fit=crop&q=85&v=dish-cf-te1',
    dietary: ['veg'],
    prepTime: 5,
    available: true,
    customizations: [{ name: 'Less Sugar', price: 0 }]
  },
  {
    id: 'dish-cf-te2',
    name: 'Fresh Crushed Ginger Milk Tea',
    category: 'drinks',
    shopSlug: 'giri-cafe',
    shopName: 'Giri Café',
    price: 75,
    description: 'Hot boiled Assam tea simmered with fresh crushed ginger root.',
    image: 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?w=800&auto=format&fit=crop&q=85&v=dish-cf-te2',
    dietary: ['veg'],
    prepTime: 5,
    available: true,
    customizations: [{ name: 'Extra Ginger Punch', price: 0 }]
  },
  {
    id: 'dish-cf-te3',
    name: 'Aromatic Elaichi Milk Tea',
    category: 'drinks',
    shopSlug: 'giri-cafe',
    shopName: 'Giri Café',
    price: 75,
    description: 'Hot black tea brewed with green cardamom pods and whole milk.',
    image: 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?w=800&auto=format&fit=crop&q=85&v=dish-cf-te3',
    dietary: ['veg'],
    prepTime: 5,
    available: true,
    customizations: [{ name: 'Jaggery Sweetener Option', price: 10 }]
  },
  {
    id: 'dish-cf-te4',
    name: 'Fresh Squeezed Lemon Honey Black Tea',
    category: 'drinks',
    shopSlug: 'giri-cafe',
    shopName: 'Giri Café',
    price: 90,
    description: 'Steeped Darjeeling black tea served hot with lemon juice and natural honey.',
    image: 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?w=800&auto=format&fit=crop&q=85&v=dish-cf-te4',
    dietary: ['veg'],
    prepTime: 4,
    available: true,
    customizations: [{ name: 'Mint Leaf Infusion', price: 10 }]
  },
  {
    id: 'dish-cf-te5',
    name: 'Himalayan Organic Whole Leaf Green Tea',
    category: 'drinks',
    shopSlug: 'giri-cafe',
    shopName: 'Giri Café',
    price: 100,
    description: 'Antioxidant rich whole green tea leaves steeped to perfection.',
    image: 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?w=800&auto=format&fit=crop&q=85&v=dish-cf-te5',
    dietary: ['veg'],
    prepTime: 4,
    available: true,
    customizations: [{ name: 'Side Honey Pot', price: 15 }]
  },
  {
    id: 'dish-cf-te6',
    name: 'Premium Assam Orthodox Black Tea',
    category: 'drinks',
    shopSlug: 'giri-cafe',
    shopName: 'Giri Café',
    price: 85,
    description: 'Strong full-bodied Assam black tea served with lemon or milk on side.',
    image: 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?w=800&auto=format&fit=crop&q=85&v=dish-cf-te6',
    dietary: ['veg'],
    prepTime: 4,
    available: true,
    customizations: [{ name: 'Side Warm Milk', price: 10 }]
  },

  // 5. SPECIAL TEA
  {
    id: 'dish-cf-st1',
    name: 'Saffron Almond Scented Kashmiri Kahwa',
    category: 'drinks',
    shopSlug: 'giri-cafe',
    shopName: 'Giri Café',
    price: 140,
    description: 'Traditional green tea brewed with saffron strands, cinnamon, cardamom, and crushed almonds.',
    image: 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?w=800&auto=format&fit=crop&q=85&v=dish-cf-st1',
    dietary: ['veg', 'chef-special'],
    prepTime: 6,
    available: true,
    customizations: [{ name: 'Extra Almond Flakes', price: 20 }]
  },
  {
    id: 'dish-cf-st2',
    name: 'Golden Turmeric Immunity Herbal Tea',
    category: 'drinks',
    shopSlug: 'giri-cafe',
    shopName: 'Giri Café',
    price: 120,
    description: 'Warming infusion of raw turmeric, black pepper, ginger, lemongrass, and honey.',
    image: 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?w=800&auto=format&fit=crop&q=85&v=dish-cf-st2',
    dietary: ['veg'],
    prepTime: 5,
    available: true,
    customizations: [{ name: 'Extra Honey', price: 15 }]
  },
  {
    id: 'dish-cf-st3',
    name: 'Wild Forest Honey Lemon Green Tea',
    category: 'drinks',
    shopSlug: 'giri-cafe',
    shopName: 'Giri Café',
    price: 110,
    description: 'Organic green tea sweetened with organic forest honey and fresh lemon juice.',
    image: 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?w=800&auto=format&fit=crop&q=85&v=dish-cf-st3',
    dietary: ['veg'],
    prepTime: 4,
    available: true,
    customizations: [{ name: 'Ginger Slice Extra', price: 10 }]
  },
  {
    id: 'dish-cf-st4',
    name: 'Fresh Garden Spearmint Infused Tea',
    category: 'drinks',
    shopSlug: 'giri-cafe',
    shopName: 'Giri Café',
    price: 105,
    description: 'Refreshing hot tea brewed with hand-picked spearmint leaves.',
    image: 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?w=800&auto=format&fit=crop&q=85&v=dish-cf-st4',
    dietary: ['veg'],
    prepTime: 4,
    available: true,
    customizations: [{ name: 'Lemon Slice', price: 5 }]
  },
  {
    id: 'dish-cf-st5',
    name: 'Dark Chocolate Cocoa Infused Chai',
    category: 'drinks',
    shopSlug: 'giri-cafe',
    shopName: 'Giri Café',
    price: 130,
    description: 'Indulgent fusion of spiced Indian masala tea and dark cocoa powder.',
    image: 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?w=800&auto=format&fit=crop&q=85&v=dish-cf-st5',
    dietary: ['veg'],
    prepTime: 6,
    available: true,
    customizations: [{ name: 'Marshmallow Topping', price: 25 }]
  },

  // 6. MILKSHAKES
  {
    id: 'dish-cf-ms1',
    name: 'Classic French Vanilla Ice Cream Shake',
    category: 'drinks',
    shopSlug: 'giri-cafe',
    shopName: 'Giri Café',
    price: 190,
    description: 'Thick blend of vanilla bean ice cream and whole chilled milk topped with whipped cream.',
    image: 'https://images.unsplash.com/photo-1572490122747-3968b75cc699?w=800&auto=format&fit=crop&q=85&v=dish-cf-ms1',
    dietary: ['veg'],
    prepTime: 5,
    available: true,
    customizations: [{ name: 'Sprinkles Topping', price: 15 }]
  },
  {
    id: 'dish-cf-ms2',
    name: 'Thick Belgian Chocolate Fudge Shake',
    category: 'drinks',
    shopSlug: 'giri-cafe',
    shopName: 'Giri Café',
    price: 210,
    description: 'Decadent chocolate ice cream blended with dark chocolate sauce and chocolate chips.',
    image: 'https://images.unsplash.com/photo-1572490122747-3968b75cc699?w=800&auto=format&fit=crop&q=85&v=dish-cf-ms2',
    dietary: ['veg', 'chef-special'],
    prepTime: 6,
    available: true,
    customizations: [{ name: 'Extra Chocolate Chips', price: 20 }]
  },
  {
    id: 'dish-cf-ms3',
    name: 'Fresh Strawberry Cream Milkshake',
    category: 'drinks',
    shopSlug: 'giri-cafe',
    shopName: 'Giri Café',
    price: 200,
    description: 'Strawberry ice cream blended with real strawberry compote and milk.',
    image: 'https://images.unsplash.com/photo-1572490122747-3968b75cc699?w=800&auto=format&fit=crop&q=85&v=dish-cf-ms3',
    dietary: ['veg'],
    prepTime: 5,
    available: true,
    customizations: [{ name: 'Fresh Strawberry Garnish', price: 25 }]
  },
  {
    id: 'dish-cf-ms4',
    name: 'Alphonso Mango Thick Milkshake',
    category: 'drinks',
    shopSlug: 'giri-cafe',
    shopName: 'Giri Café',
    price: 210,
    description: 'Thick rich shake prepared with pure Alphonso mango pulp and vanilla ice cream.',
    image: 'https://images.unsplash.com/photo-1572490122747-3968b75cc699?w=800&auto=format&fit=crop&q=85&v=dish-cf-ms4',
    dietary: ['veg'],
    prepTime: 5,
    available: true,
    customizations: [{ name: 'Tutti Frutti Topping', price: 15 }]
  },
  {
    id: 'dish-cf-ms5',
    name: 'Crunchy Crushed Oreo Cookie Shake',
    category: 'drinks',
    shopSlug: 'giri-cafe',
    shopName: 'Giri Café',
    price: 230,
    description: 'Creamy milk shake blended with Oreo chocolate cookies and chocolate syrup.',
    image: 'https://images.unsplash.com/photo-1572490122747-3968b75cc699?w=800&auto=format&fit=crop&q=85&v=dish-cf-ms5',
    dietary: ['veg', 'chef-special'],
    prepTime: 6,
    available: true,
    customizations: [{ name: 'Whole Oreo Cookie Top', price: 15 }]
  },
  {
    id: 'dish-cf-ms6',
    name: 'Crispy Wafer Chocolate KitKat Shake',
    category: 'drinks',
    shopSlug: 'giri-cafe',
    shopName: 'Giri Café',
    price: 240,
    description: 'Rich chocolate milkshake blended with crunchy KitKat wafer bars.',
    image: 'https://images.unsplash.com/photo-1572490122747-3968b75cc699?w=800&auto=format&fit=crop&q=85&v=dish-cf-ms6',
    dietary: ['veg'],
    prepTime: 6,
    available: true,
    customizations: [{ name: 'KitKat Finger Garnish', price: 25 }]
  },

  // 7. MOJITOS & COOLERS
  {
    id: 'dish-cf-mj1',
    name: 'Classic Mint Lime Sparkling Virgin Mojito',
    category: 'drinks',
    shopSlug: 'giri-cafe',
    shopName: 'Giri Café',
    price: 170,
    description: 'Muddled fresh spearmint, lime wedges, sugar, topped with sparkling soda water.',
    image: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?w=800&auto=format&fit=crop&q=85&v=dish-cf-mj1',
    dietary: ['veg', 'chef-special'],
    prepTime: 5,
    available: true,
    customizations: [{ name: 'Extra Mint Crush', price: 15 }]
  },
  {
    id: 'dish-cf-mj2',
    name: 'Double Spearmint Lime Fizz Mojito',
    category: 'drinks',
    shopSlug: 'giri-cafe',
    shopName: 'Giri Café',
    price: 180,
    description: 'Refreshing double mint infusion with lime juice and lemon-lime fizzy soda.',
    image: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?w=800&auto=format&fit=crop&q=85&v=dish-cf-mj2',
    dietary: ['veg'],
    prepTime: 5,
    available: true,
    customizations: [{ name: 'Sweetener Choice (Sugar Free)', price: 0 }]
  },
  {
    id: 'dish-cf-mj3',
    name: 'Electric Blue Curaçao Sparkling Mocktail',
    category: 'drinks',
    shopSlug: 'giri-cafe',
    shopName: 'Giri Café',
    price: 190,
    description: 'Vibrant blue curaçao flavor mixed with lemon juice, mint, and chilled Sprite.',
    image: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?w=800&auto=format&fit=crop&q=85&v=dish-cf-mj3',
    dietary: ['veg'],
    prepTime: 5,
    available: true,
    customizations: [{ name: 'Maraschino Cherry Top', price: 20 }]
  },
  {
    id: 'dish-cf-mj4',
    name: 'Tangy Crisp Green Apple Soda Cooler',
    category: 'drinks',
    shopSlug: 'giri-cafe',
    shopName: 'Giri Café',
    price: 175,
    description: 'Crisp green apple syrup mixed with mint leaves, lemon juice, and soda.',
    image: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?w=800&auto=format&fit=crop&q=85&v=dish-cf-mj4',
    dietary: ['veg'],
    prepTime: 5,
    available: true,
    customizations: [{ name: 'Green Apple Slice', price: 10 }]
  },
  {
    id: 'dish-cf-mj5',
    name: 'Fresh Strawberry Mint Soda Cooler',
    category: 'drinks',
    shopSlug: 'giri-cafe',
    shopName: 'Giri Café',
    price: 185,
    description: 'Real strawberry crush muddled with fresh mint, lemon, and chilled soda.',
    image: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?w=800&auto=format&fit=crop&q=85&v=dish-cf-mj5',
    dietary: ['veg'],
    prepTime: 5,
    available: true,
    customizations: [{ name: 'Strawberry Chunks', price: 20 }]
  },
  {
    id: 'dish-cf-mj6',
    name: 'Chilled Fresh Lemon Spearmint Cooler',
    category: 'drinks',
    shopSlug: 'giri-cafe',
    shopName: 'Giri Café',
    price: 160,
    description: 'Zesty fresh lemon juice, crushed mint, rock salt, and chilled soda.',
    image: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?w=800&auto=format&fit=crop&q=85&v=dish-cf-mj6',
    dietary: ['veg'],
    prepTime: 4,
    available: true,
    customizations: [{ name: 'Black Salt Twist', price: 0 }]
  },

  // 8. FRESH JUICES
  {
    id: 'dish-cf-fj1',
    name: 'Cold Pressed Fresh Valencia Orange Juice',
    category: 'drinks',
    shopSlug: 'giri-cafe',
    shopName: 'Giri Café',
    price: 150,
    description: '100% fresh cold-pressed orange juice without added sugar or water.',
    image: 'https://images.unsplash.com/photo-1613478223719-2ab802602423?w=800&auto=format&fit=crop&q=85&v=dish-cf-fj1',
    dietary: ['veg', 'chef-special'],
    prepTime: 5,
    available: true,
    customizations: [{ name: 'No Ice Option', price: 0 }]
  },
  {
    id: 'dish-cf-fj2',
    name: 'Freshly Squeezed Chilled Watermelon Juice',
    category: 'drinks',
    shopSlug: 'giri-cafe',
    shopName: 'Giri Café',
    price: 130,
    description: 'Pure refreshing watermelon juice with a touch of mint & lime.',
    image: 'https://images.unsplash.com/photo-1589733955941-5eeaf752f6dd?w=800&auto=format&fit=crop&q=85&v=dish-cf-fj2',
    dietary: ['veg'],
    prepTime: 5,
    available: true,
    customizations: [{ name: 'Black Salt Seasoning', price: 0 }]
  },
  {
    id: 'dish-cf-fj3',
    name: 'Tropical Sweet Queen Pineapple Juice',
    category: 'drinks',
    shopSlug: 'giri-cafe',
    shopName: 'Giri Café',
    price: 140,
    description: 'Freshly extracted sweet pineapple juice with black salt.',
    image: 'https://images.unsplash.com/photo-1613478223719-2ab802602423?w=800&auto=format&fit=crop&q=85&v=dish-cf-fj3',
    dietary: ['veg'],
    prepTime: 5,
    available: true,
    customizations: [{ name: 'Mint Infusion', price: 10 }]
  },
  {
    id: 'dish-cf-fj4',
    name: 'Pure Fresh Himalayan Red Apple Juice',
    category: 'drinks',
    shopSlug: 'giri-cafe',
    shopName: 'Giri Café',
    price: 160,
    description: 'Fresh cold pressed juice made from crisp Himalayan red apples.',
    image: 'https://images.unsplash.com/photo-1613478223719-2ab802602423?w=800&auto=format&fit=crop&q=85&v=dish-cf-fj4',
    dietary: ['veg'],
    prepTime: 5,
    available: true,
    customizations: [{ name: 'Cinnamon Pinch', price: 5 }]
  },
  {
    id: 'dish-cf-fj5',
    name: 'Fresh Kashmiri Pomegranate Juice',
    category: 'drinks',
    shopSlug: 'giri-cafe',
    shopName: 'Giri Café',
    price: 170,
    description: 'Rich antioxidant fresh pomegranate seed juice.',
    image: 'https://images.unsplash.com/photo-1613478223719-2ab802602423?w=800&auto=format&fit=crop&q=85&v=dish-cf-fj5',
    dietary: ['veg', 'chef-special'],
    prepTime: 6,
    available: true,
    customizations: [{ name: 'Chat Masala Salt', price: 0 }]
  },
  {
    id: 'dish-cf-fj6',
    name: 'Fresh Organic Red Carrot Detox Juice',
    category: 'drinks',
    shopSlug: 'giri-cafe',
    shopName: 'Giri Café',
    price: 140,
    description: 'Healthy fresh carrot juice blended with ginger and lemon.',
    image: 'https://images.unsplash.com/photo-1613478223719-2ab802602423?w=800&auto=format&fit=crop&q=85&v=dish-cf-fj6',
    dietary: ['veg'],
    prepTime: 5,
    available: true,
    customizations: [{ name: 'Add Beetroot Blend', price: 20 }]
  },

  // 9. SMOOTHIES
  {
    id: 'dish-cf-sm1',
    name: 'Thick Alphonso Mango Greek Yogurt Smoothie',
    category: 'drinks',
    shopSlug: 'giri-cafe',
    shopName: 'Giri Café',
    price: 230,
    description: 'Blended Alphonso mango pulp, thick Greek yogurt, honey, and chia seeds.',
    image: 'https://images.unsplash.com/photo-1553530666-ba11a7da3888?w=800&auto=format&fit=crop&q=85&v=dish-cf-sm1',
    dietary: ['veg', 'chef-special'],
    prepTime: 6,
    available: true,
    customizations: [{ name: 'Extra Chia Topping', price: 15 }]
  },
  {
    id: 'dish-cf-sm2',
    name: 'Fresh Berry Greek Yogurt Smoothie',
    category: 'drinks',
    shopSlug: 'giri-cafe',
    shopName: 'Giri Café',
    price: 240,
    description: 'Blend of strawberries, blueberries, yogurt, and honey.',
    image: 'https://images.unsplash.com/photo-1553530666-ba11a7da3888?w=800&auto=format&fit=crop&q=85&v=dish-cf-sm2',
    dietary: ['veg'],
    prepTime: 6,
    available: true,
    customizations: [{ name: 'Protein Powder Scoop', price: 50 }]
  },
  {
    id: 'dish-cf-sm3',
    name: 'Honey Oat Creamy Banana Smoothie',
    category: 'drinks',
    shopSlug: 'giri-cafe',
    shopName: 'Giri Café',
    price: 210,
    description: 'Ripe bananas blended with toasted oats, milk, honey, and peanut butter.',
    image: 'https://images.unsplash.com/photo-1553530666-ba11a7da3888?w=800&auto=format&fit=crop&q=85&v=dish-cf-sm3',
    dietary: ['veg'],
    prepTime: 5,
    available: true,
    customizations: [{ name: 'Extra Peanut Butter', price: 25 }]
  },
  {
    id: 'dish-cf-sm4',
    name: 'Wild Triple Berry Acai Smoothie',
    category: 'drinks',
    shopSlug: 'giri-cafe',
    shopName: 'Giri Café',
    price: 260,
    description: 'Acai berry puree blended with blackberry, raspberry, strawberry, and almond milk.',
    image: 'https://images.unsplash.com/photo-1553530666-ba11a7da3888?w=800&auto=format&fit=crop&q=85&v=dish-cf-sm4',
    dietary: ['veg', 'chef-special'],
    prepTime: 7,
    available: true,
    customizations: [{ name: 'Granola Topping', price: 30 }]
  },
  {
    id: 'dish-cf-sm5',
    name: 'Dark Cocoa Banana Protein Smoothie',
    category: 'drinks',
    shopSlug: 'giri-cafe',
    shopName: 'Giri Café',
    price: 250,
    description: 'Dark cocoa powder, banana, whey protein, and almond milk smoothie.',
    image: 'https://images.unsplash.com/photo-1553530666-ba11a7da3888?w=800&auto=format&fit=crop&q=85&v=dish-cf-sm5',
    dietary: ['veg'],
    prepTime: 6,
    available: true,
    customizations: [{ name: 'Flax Seeds Sprinkle', price: 15 }]
  },

  // 10. BREAKFAST
  {
    id: 'dish-cf-bf1',
    name: 'Crispy Ghee Roast Masala Dosa',
    category: 'tiffins',
    shopSlug: 'giri-cafe',
    shopName: 'Giri Café',
    price: 160,
    description: 'Golden fermented rice crepe roasted in ghee, filled with potato masala, served with coconut chutney & sambar.',
    image: 'https://images.unsplash.com/photo-1668236543090-82eba5ee5976?w=800&auto=format&fit=crop&q=85&v=dish-cf-bf1',
    dietary: ['veg'],
    prepTime: 10,
    available: true,
    customizations: [{ name: 'Extra Butter Portion', price: 20 }]
  },
  {
    id: 'dish-cf-bf2',
    name: 'Steamed Rice Idli Sambar (4pcs)',
    category: 'tiffins',
    shopSlug: 'giri-cafe',
    shopName: 'Giri Café',
    price: 120,
    description: 'Soft steamed rice cakes served with hot lentil sambar & coconut chutney.',
    image: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?w=800&auto=format&fit=crop&q=85&v=dish-cf-bf2',
    dietary: ['veg'],
    prepTime: 6,
    available: true,
    customizations: [{ name: 'Podi Ghee Drizzle', price: 25 }]
  },
  {
    id: 'dish-cf-bf3',
    name: 'Crispy Medu Vada (2pcs)',
    category: 'tiffins',
    shopSlug: 'giri-cafe',
    shopName: 'Giri Café',
    price: 110,
    description: 'Fried crisp lentil donuts served with sambar & ginger chutney.',
    image: 'https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?w=800&auto=format&fit=crop&q=85&v=dish-cf-bf3',
    dietary: ['veg'],
    prepTime: 8,
    available: true,
    customizations: [{ name: 'Extra Sambar Bowl', price: 20 }]
  },
  {
    id: 'dish-cf-bf4',
    name: 'Fluffy Hot Poori with Potato Masala (3pcs)',
    category: 'tiffins',
    shopSlug: 'giri-cafe',
    shopName: 'Giri Café',
    price: 140,
    description: 'Deep-fried puffed wheat bread served with spiced potato curry.',
    image: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?w=800&auto=format&fit=crop&q=85&v=dish-cf-bf4',
    dietary: ['veg'],
    prepTime: 10,
    available: true,
    customizations: [{ name: 'Extra Poori (1pc)', price: 30 }]
  },
  {
    id: 'dish-cf-bf5',
    name: 'Roasted Rava Ginger Cashew Upma',
    category: 'tiffins',
    shopSlug: 'giri-cafe',
    shopName: 'Giri Café',
    price: 110,
    description: 'Tempered roasted semolina savory porridge with mustard, ginger, green chilies, and cashews.',
    image: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?w=800&auto=format&fit=crop&q=85&v=dish-cf-bf5',
    dietary: ['veg'],
    prepTime: 8,
    available: true,
    customizations: [{ name: 'Desi Ghee Drizzle', price: 15 }]
  },
  {
    id: 'dish-cf-bf6',
    name: 'Desi Ghee Cashew Ven Pongal',
    category: 'tiffins',
    shopSlug: 'giri-cafe',
    shopName: 'Giri Café',
    price: 130,
    description: 'Rice and moong dal porridge seasoned with pepper, cumin, ginger, and ghee roasted cashews.',
    image: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?w=800&auto=format&fit=crop&q=85&v=dish-cf-bf6',
    dietary: ['veg'],
    prepTime: 8,
    available: true,
    customizations: [{ name: 'Extra Coconut Chutney', price: 15 }]
  },
  {
    id: 'dish-cf-bf7',
    name: 'Fresh Garden Veggie Mayo Toast Sandwich',
    category: 'sandwiches',
    shopSlug: 'giri-cafe',
    shopName: 'Giri Café',
    price: 150,
    description: 'Toasted white bread layered with cucumber, tomato, onion, capsicum, and mayonnaise.',
    image: 'https://images.unsplash.com/photo-1528735602780-2552fd46c7af?w=800&auto=format&fit=crop&q=85&v=dish-cf-bf7',
    dietary: ['veg'],
    prepTime: 8,
    available: true,
    customizations: [{ name: 'Add Cheese Slice', price: 25 }]
  },

  // 11. SANDWICHES
  {
    id: 'dish-cf-sw1',
    name: 'Classic Cucumber Tomato Veggie Sandwich',
    category: 'sandwiches',
    shopSlug: 'giri-cafe',
    shopName: 'Giri Café',
    price: 140,
    description: 'Fresh sliced bread filled with mint chutney, cucumbers, tomatoes, and chat masala.',
    image: 'https://images.unsplash.com/photo-1528735602780-2552fd46c7af?w=800&auto=format&fit=crop&q=85&v=dish-cf-sw1',
    dietary: ['veg'],
    prepTime: 6,
    available: true,
    customizations: [{ name: 'Brown Bread Option', price: 10 }]
  },
  {
    id: 'dish-cf-sw2',
    name: 'Double Cheddar Cheese Slice Sandwich',
    category: 'sandwiches',
    shopSlug: 'giri-cafe',
    shopName: 'Giri Café',
    price: 160,
    description: 'Toasted butter bread stuffed with melted cheddar cheese slices and herbs.',
    image: 'https://images.unsplash.com/photo-1528735602780-2552fd46c7af?w=800&auto=format&fit=crop&q=85&v=dish-cf-sw2',
    dietary: ['veg'],
    prepTime: 6,
    available: true,
    customizations: [{ name: 'Extra Cheese Slice', price: 30 }]
  },
  {
    id: 'dish-cf-sw3',
    name: 'Spiced Paneer Tikka Mayo Grilled Sandwich',
    category: 'sandwiches',
    shopSlug: 'giri-cafe',
    shopName: 'Giri Café',
    price: 190,
    description: 'Grilled paneer cubes marinated in tikka spices layered with green chutney and cheese.',
    image: 'https://images.unsplash.com/photo-1528735602780-2552fd46c7af?w=800&auto=format&fit=crop&q=85&v=dish-cf-sw3',
    dietary: ['veg', 'chef-special'],
    prepTime: 10,
    available: true,
    customizations: [{ name: 'Peri Peri Seasoning', price: 15 }]
  },
  {
    id: 'dish-cf-sw4',
    name: 'Smoked Chicken Breast Herb Mayo Sandwich',
    category: 'sandwiches',
    shopSlug: 'giri-cafe',
    shopName: 'Giri Café',
    price: 210,
    description: 'Shredded smoked chicken breast tossed with garlic herb mayo, lettuce, and tomatoes.',
    image: 'https://images.unsplash.com/photo-1528735602780-2552fd46c7af?w=800&auto=format&fit=crop&q=85&v=dish-cf-sw4',
    dietary: ['non-veg'],
    prepTime: 10,
    available: true,
    customizations: [{ name: 'Add Fried Egg', price: 25 }]
  },
  {
    id: 'dish-cf-sw5',
    name: 'Triple Layered Chicken Bacon Egg Club Sandwich',
    category: 'sandwiches',
    shopSlug: 'giri-cafe',
    shopName: 'Giri Café',
    price: 240,
    description: 'Three-tiered club sandwich loaded with grilled chicken, fried egg, lettuce, cheese & mayo.',
    image: 'https://images.unsplash.com/photo-1528735602780-2552fd46c7af?w=800&auto=format&fit=crop&q=85&v=dish-cf-sw5',
    dietary: ['non-veg', 'chef-special'],
    prepTime: 12,
    available: true,
    customizations: [{ name: 'Side French Fries Dip', price: 40 }]
  },
  {
    id: 'dish-cf-sw6',
    name: 'Golden Melted Mozzarella Grilled Cheese',
    category: 'sandwiches',
    shopSlug: 'giri-cafe',
    shopName: 'Giri Café',
    price: 180,
    description: 'Artisan sourdough bread stuffed with melted mozzarella, cheddar, and garlic butter.',
    image: 'https://images.unsplash.com/photo-1528735602780-2552fd46c7af?w=800&auto=format&fit=crop&q=85&v=dish-cf-sw6',
    dietary: ['veg'],
    prepTime: 8,
    available: true,
    customizations: [{ name: 'Jalapeño Slices', price: 20 }]
  },

  // 12. BURGERS
  {
    id: 'dish-cf-bg1',
    name: 'Crispy Veg Patty Herb Mayo Burger',
    category: 'fast-food',
    shopSlug: 'giri-cafe',
    shopName: 'Giri Café',
    price: 160,
    description: 'Crispy potato vegetable patty, lettuce, tomato, onion, and mayonnaise inside soft bun.',
    image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=800&auto=format&fit=crop&q=85&v=dish-cf-bg1',
    dietary: ['veg'],
    prepTime: 10,
    available: true,
    customizations: [{ name: 'Add Cheese Slice', price: 25 }]
  },
  {
    id: 'dish-cf-bg2',
    name: 'Spicy Grilled Cottage Cheese Burger',
    category: 'fast-food',
    shopSlug: 'giri-cafe',
    shopName: 'Giri Café',
    price: 190,
    description: 'Thick marinated grilled paneer slab with mint mayo, onions, and crispy lettuce.',
    image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=800&auto=format&fit=crop&q=85&v=dish-cf-bg2',
    dietary: ['veg', 'chef-special'],
    prepTime: 12,
    available: true,
    customizations: [{ name: 'Double Paneer Patty', price: 60 }]
  },
  {
    id: 'dish-cf-bg3',
    name: 'Juicy Fried Chicken Patty Burger',
    category: 'fast-food',
    shopSlug: 'giri-cafe',
    shopName: 'Giri Café',
    price: 210,
    description: 'Golden fried chicken breast fillet with thousand island sauce, pickles, and lettuce.',
    image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=800&auto=format&fit=crop&q=85&v=dish-cf-bg3',
    dietary: ['non-veg'],
    prepTime: 12,
    available: true,
    customizations: [{ name: 'Spicy Peri Peri Dip', price: 20 }]
  },
  {
    id: 'dish-cf-bg4',
    name: 'Classic Double Cheese Crisp Burger',
    category: 'fast-food',
    shopSlug: 'giri-cafe',
    shopName: 'Giri Café',
    price: 200,
    description: 'Double cheese slices over fried veggie patty with cocktail burger sauce.',
    image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=800&auto=format&fit=crop&q=85&v=dish-cf-bg4',
    dietary: ['veg'],
    prepTime: 10,
    available: true,
    customizations: [{ name: 'Side Small Fries', price: 45 }]
  },
  {
    id: 'dish-cf-bg5',
    name: 'Smoked BBQ Chicken Bacon Burger',
    category: 'fast-food',
    shopSlug: 'giri-cafe',
    shopName: 'Giri Café',
    price: 240,
    description: 'Flame grilled chicken patty glazed in BBQ sauce with caramelized onions and cheddar cheese.',
    image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=800&auto=format&fit=crop&q=85&v=dish-cf-bg5',
    dietary: ['non-veg', 'chef-special'],
    prepTime: 14,
    available: true,
    customizations: [{ name: 'Extra BBQ Glaze', price: 20 }]
  },

  // 13. PIZZA
  {
    id: 'dish-cf-pz1',
    name: 'Classic Italian Mozzarella Fresh Basil Pizza',
    category: 'fast-food',
    shopSlug: 'giri-cafe',
    shopName: 'Giri Café',
    price: 280,
    description: 'Hand-tossed crust topped with San Marzano tomato sauce, mozzarella cheese, and basil leaves.',
    image: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=800&auto=format&fit=crop&q=85&v=dish-cf-pz1',
    dietary: ['veg'],
    prepTime: 15,
    available: true,
    customizations: [{ name: 'Extra Cheese Burst Crust', price: 60 }]
  },
  {
    id: 'dish-cf-pz2',
    name: 'Loaded Veggie Mushroom Olive Farmhouse Pizza',
    category: 'fast-food',
    shopSlug: 'giri-cafe',
    shopName: 'Giri Café',
    price: 340,
    description: 'Loaded with capsicum, onion, tomato, button mushrooms, black olives, and mozzarella.',
    image: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=800&auto=format&fit=crop&q=85&v=dish-cf-pz2',
    dietary: ['veg'],
    prepTime: 16,
    available: true,
    customizations: [{ name: 'Jalapeño & Corn Topping', price: 30 }]
  },
  {
    id: 'dish-cf-pz3',
    name: 'Spicy Tandoori Paneer Tikka Capsicum Pizza',
    category: 'fast-food',
    shopSlug: 'giri-cafe',
    shopName: 'Giri Café',
    price: 360,
    description: 'Tandoori paneer tikka chunks, red paprika, bell peppers, coriander, and mozzarella.',
    image: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=800&auto=format&fit=crop&q=85&v=dish-cf-pz3',
    dietary: ['veg', 'chef-special'],
    prepTime: 16,
    available: true,
    customizations: [{ name: 'Thin Crust Option', price: 0 }]
  },
  {
    id: 'dish-cf-pz4',
    name: 'Charcoal Grilled Chicken Tikka Onion Pizza',
    category: 'fast-food',
    shopSlug: 'giri-cafe',
    shopName: 'Giri Café',
    price: 390,
    description: 'Smokey chicken tikka pieces, crisp onions, green chilies, and melted mozzarella.',
    image: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=800&auto=format&fit=crop&q=85&v=dish-cf-pz4',
    dietary: ['non-veg', 'chef-special'],
    prepTime: 16,
    available: true,
    customizations: [{ name: 'Extra Chicken Topping', price: 70 }]
  },
  {
    id: 'dish-cf-pz5',
    name: 'Smoked BBQ Chicken Corn Jalapeño Pizza',
    category: 'fast-food',
    shopSlug: 'giri-cafe',
    shopName: 'Giri Café',
    price: 410,
    description: 'BBQ sauce base with grilled chicken, sweet corn, spicy jalapeños, and mozzarella.',
    image: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=800&auto=format&fit=crop&q=85&v=dish-cf-pz5',
    dietary: ['non-veg'],
    prepTime: 16,
    available: true,
    customizations: [{ name: 'Garlic Butter Crust Dip', price: 30 }]
  },

  // 14. PASTA
  {
    id: 'dish-cf-ps1',
    name: 'Creamy Garlic Butter Parmesan Alfredo Penne',
    category: 'italian',
    shopSlug: 'giri-cafe',
    shopName: 'Giri Café',
    price: 320,
    description: 'Penne pasta tossed in rich heavy cream sauce with fresh garlic, butter, and parmesan cheese.',
    image: 'https://images.unsplash.com/photo-1621996346565-e3d5d6281270?w=800&auto=format&fit=crop&q=85&v=dish-cf-ps1',
    dietary: ['veg', 'chef-special'],
    prepTime: 14,
    available: true,
    customizations: [{ name: 'Add Garlic Bread Toast (2pcs)', price: 40 }]
  },
  {
    id: 'dish-cf-ps2',
    name: 'Spicy Tomato Garlic Chili Arrabbiata Penne',
    category: 'italian',
    shopSlug: 'giri-cafe',
    shopName: 'Giri Café',
    price: 290,
    description: 'Penne pasta cooked in tangy red tomato sauce enriched with red chili flakes, garlic & basil.',
    image: 'https://images.unsplash.com/photo-1621996346565-e3d5d6281270?w=800&auto=format&fit=crop&q=85&v=dish-cf-ps2',
    dietary: ['veg', 'spicy'],
    prepTime: 12,
    available: true,
    customizations: [{ name: 'Extra Parmesan Cheese', price: 30 }]
  },
  {
    id: 'dish-cf-ps3',
    name: 'Fresh Basil Pine Nut Cream Pesto Fusilli',
    category: 'italian',
    shopSlug: 'giri-cafe',
    shopName: 'Giri Café',
    price: 340,
    description: 'Fusilli pasta tossed in vibrant house-made basil pesto sauce, olive oil, and parmesan.',
    image: 'https://images.unsplash.com/photo-1621996346565-e3d5d6281270?w=800&auto=format&fit=crop&q=85&v=dish-cf-ps3',
    dietary: ['veg'],
    prepTime: 14,
    available: true,
    customizations: [{ name: 'Add Black Olives', price: 20 }]
  },
  {
    id: 'dish-cf-ps4',
    name: 'Wild Button Mushroom White Wine Sauce Pasta',
    category: 'italian',
    shopSlug: 'giri-cafe',
    shopName: 'Giri Café',
    price: 330,
    description: 'Sautéed mushrooms, herbs, garlic, and cream sauce tossed with penne pasta.',
    image: 'https://images.unsplash.com/photo-1621996346565-e3d5d6281270?w=800&auto=format&fit=crop&q=85&v=dish-cf-ps4',
    dietary: ['veg'],
    prepTime: 14,
    available: true,
    customizations: [{ name: 'Extra Mushroom Portions', price: 35 }]
  },
  {
    id: 'dish-cf-ps5',
    name: 'Grilled Chicken Alfredo Cream Pasta',
    category: 'italian',
    shopSlug: 'giri-cafe',
    shopName: 'Giri Café',
    price: 370,
    description: 'Juicy grilled chicken strips tossed with rich parmesan cream Alfredo sauce and penne.',
    image: 'https://images.unsplash.com/photo-1621996346565-e3d5d6281270?w=800&auto=format&fit=crop&q=85&v=dish-cf-ps5',
    dietary: ['non-veg', 'chef-special'],
    prepTime: 15,
    available: true,
    customizations: [{ name: 'Extra Grilled Chicken', price: 60 }]
  },

  // 15. CAFE SNACKS
  {
    id: 'dish-cf-sn1',
    name: 'Classic Golden Salted Potato Fries',
    category: 'fast-food',
    shopSlug: 'giri-cafe',
    shopName: 'Giri Café',
    price: 130,
    description: 'Crispy golden potato french fries seasoned with sea salt, served with tomato ketchup.',
    image: 'https://images.unsplash.com/photo-1576107232684-1279f3908594?w=800&auto=format&fit=crop&q=85&v=dish-cf-sn1',
    dietary: ['veg'],
    prepTime: 8,
    available: true,
    customizations: [{ name: 'Mayo Dip Cup', price: 20 }]
  },
  {
    id: 'dish-cf-sn2',
    name: 'Spicy African Peri Peri Seasoned Fries',
    category: 'fast-food',
    shopSlug: 'giri-cafe',
    shopName: 'Giri Café',
    price: 150,
    description: 'Crispy potato fries dusted with fiery African peri peri spice mix.',
    image: 'https://images.unsplash.com/photo-1576107232684-1279f3908594?w=800&auto=format&fit=crop&q=85&v=dish-cf-sn2',
    dietary: ['veg', 'spicy'],
    prepTime: 8,
    available: true,
    customizations: [{ name: 'Cheese Dip Cup', price: 30 }]
  },
  {
    id: 'dish-cf-sn3',
    name: 'Loaded Melted Cheddar Cheese Sauce Fries',
    category: 'fast-food',
    shopSlug: 'giri-cafe',
    shopName: 'Giri Café',
    price: 180,
    description: 'Fries smothered in warm liquid cheddar cheese sauce and jalapeño slices.',
    image: 'https://images.unsplash.com/photo-1576107232684-1279f3908594?w=800&auto=format&fit=crop&q=85&v=dish-cf-sn3',
    dietary: ['veg', 'chef-special'],
    prepTime: 10,
    available: true,
    customizations: [{ name: 'Crispy Bacon Bits', price: 40 }]
  },
  {
    id: 'dish-cf-sn4',
    name: 'Herb Butter Baked French Garlic Bread',
    category: 'starters',
    shopSlug: 'giri-cafe',
    shopName: 'Giri Café',
    price: 140,
    description: 'Crispy oven-baked baguette slices topped with garlic herb butter & oregano.',
    image: 'https://images.unsplash.com/photo-1573140247632-f8fd74997d5c?w=800&auto=format&fit=crop&q=85&v=dish-cf-sn4',
    dietary: ['veg'],
    prepTime: 8,
    available: true,
    customizations: [{ name: 'Add Melted Cheese', price: 30 }]
  },
  {
    id: 'dish-cf-sn5',
    name: 'Crispy Tortilla Chips with Cheese Dip & Salsa',
    category: 'starters',
    shopSlug: 'giri-cafe',
    shopName: 'Giri Café',
    price: 190,
    description: 'Crunchy corn tortilla chips served with warm cheese sauce and fresh tomato salsa.',
    image: 'https://images.unsplash.com/photo-1513456852971-30c0b8199d4d?w=800&auto=format&fit=crop&q=85&v=dish-cf-sn5',
    dietary: ['veg'],
    prepTime: 6,
    available: true,
    customizations: [{ name: 'Extra Guacamole Bowl', price: 45 }]
  },
  {
    id: 'dish-cf-sn6',
    name: 'Seasoned Crispy Fried Potato Wedges',
    category: 'fast-food',
    shopSlug: 'giri-cafe',
    shopName: 'Giri Café',
    price: 160,
    description: 'Thick cut potato wedges seasoned with paprika, garlic, and rosemary.',
    image: 'https://images.unsplash.com/photo-1576107232684-1279f3908594?w=800&auto=format&fit=crop&q=85&v=dish-cf-sn6',
    dietary: ['veg'],
    prepTime: 9,
    available: true,
    customizations: [{ name: 'Sour Cream Dip', price: 25 }]
  },

  // 16. BAKERY
  {
    id: 'dish-cf-bk1',
    name: 'Belgian Dark Chocolate Truffle Layer Cake Slice',
    category: 'bakery',
    shopSlug: 'giri-cafe',
    shopName: 'Giri Café',
    price: 170,
    description: 'Rich dark chocolate sponge cake filled and glazed with dark Belgian chocolate ganache.',
    image: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=800&auto=format&fit=crop&q=85&v=dish-cf-bk1',
    dietary: ['veg', 'chef-special'],
    prepTime: 3,
    available: true,
    customizations: [{ name: 'Warm Up Service', price: 0 }]
  },
  {
    id: 'dish-cf-bk2',
    name: 'Cream Cheese Frosting Red Velvet Cake Slice',
    category: 'bakery',
    shopSlug: 'giri-cafe',
    shopName: 'Giri Café',
    price: 180,
    description: 'Moist red velvet sponge cake layered with silky cream cheese frosting.',
    image: 'https://images.unsplash.com/photo-1586788680404-329d2b450537?w=800&auto=format&fit=crop&q=85&v=dish-cf-bk2',
    dietary: ['veg'],
    prepTime: 3,
    available: true,
    customizations: [{ name: 'Extra Cream Cheese', price: 20 }]
  },
  {
    id: 'dish-cf-bk3',
    name: 'Classic Cherry Whipped Cream Black Forest Slice',
    category: 'bakery',
    shopSlug: 'giri-cafe',
    shopName: 'Giri Café',
    price: 160,
    description: 'Chocolate sponge cake soaked in cherry syrup, layered with whipped cream and cherries.',
    image: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=800&auto=format&fit=crop&q=85&v=dish-cf-bk3',
    dietary: ['veg'],
    prepTime: 3,
    available: true,
    customizations: [{ name: 'Maraschino Cherry Top', price: 15 }]
  },
  {
    id: 'dish-cf-bk4',
    name: 'Layered Fudgy Dark Chocolate Pastry',
    category: 'bakery',
    shopSlug: 'giri-cafe',
    shopName: 'Giri Café',
    price: 140,
    description: 'Single portion moist chocolate pastry coated in smooth cocoa glaze.',
    image: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=800&auto=format&fit=crop&q=85&v=dish-cf-bk4',
    dietary: ['veg'],
    prepTime: 2,
    available: true,
    customizations: [{ name: 'Chocolate Curl Dust', price: 10 }]
  },
  {
    id: 'dish-cf-bk5',
    name: 'Glazed Chocolate Sprinkles Donut',
    category: 'bakery',
    shopSlug: 'giri-cafe',
    shopName: 'Giri Café',
    price: 110,
    description: 'Soft ring donut dipped in dark chocolate glaze and colorful sprinkles.',
    image: 'https://images.unsplash.com/photo-1527515637462-cff94eecc1ac?w=800&auto=format&fit=crop&q=85&v=dish-cf-bk5',
    dietary: ['veg'],
    prepTime: 2,
    available: true,
    customizations: [{ name: 'Pack of 2 Offer', price: 90 }]
  },
  {
    id: 'dish-cf-bk6',
    name: 'Fresh Baked Choco-Chip Berry Muffin',
    category: 'bakery',
    shopSlug: 'giri-cafe',
    shopName: 'Giri Café',
    price: 120,
    description: 'Fluffy baked muffin stuffed with dark chocolate chips and blueberry preserves.',
    image: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=800&auto=format&fit=crop&q=85&v=dish-cf-bk6',
    dietary: ['veg'],
    prepTime: 2,
    available: true,
    customizations: [{ name: 'Butter Spread', price: 10 }]
  },

  // 17. COOKIES & BISCUITS
  {
    id: 'dish-cf-ck1',
    name: 'Fresh Baked Giant Choco-Chip Cookie',
    category: 'bakery',
    shopSlug: 'giri-cafe',
    shopName: 'Giri Café',
    price: 90,
    description: 'Chewy buttery chocolate chip cookie with gooey melted dark chocolate chunks.',
    image: 'https://images.unsplash.com/photo-1499636136210-6f4ee915583e?w=800&auto=format&fit=crop&q=85&v=dish-cf-ck1',
    dietary: ['veg', 'chef-special'],
    prepTime: 2,
    available: true,
    customizations: [{ name: 'Warm Milk Glass Combo', price: 45 }]
  },
  {
    id: 'dish-cf-ck2',
    name: 'Danish Rich Butter Shortbread Cookies (3pcs)',
    category: 'bakery',
    shopSlug: 'giri-cafe',
    shopName: 'Giri Café',
    price: 80,
    description: 'Melt-in-mouth traditional Danish butter biscuits.',
    image: 'https://images.unsplash.com/photo-1499636136210-6f4ee915583e?w=800&auto=format&fit=crop&q=85&v=dish-cf-ck2',
    dietary: ['veg'],
    prepTime: 2,
    available: true,
    customizations: [{ name: 'Pack of 6 Option', price: 70 }]
  },
  {
    id: 'dish-cf-ck3',
    name: 'Healthy Honey Raisin Oat Cookies (3pcs)',
    category: 'bakery',
    shopSlug: 'giri-cafe',
    shopName: 'Giri Café',
    price: 85,
    description: 'Wholesome rolled oat cookies baked with honey, cinnamon, and raisins.',
    image: 'https://images.unsplash.com/photo-1499636136210-6f4ee915583e?w=800&auto=format&fit=crop&q=85&v=dish-cf-ck3',
    dietary: ['veg'],
    prepTime: 2,
    available: true,
    customizations: [{ name: 'Jaggery Sweetened Option', price: 0 }]
  },
  {
    id: 'dish-cf-ck4',
    name: 'Roasted Almond Crunch Biscuits (3pcs)',
    category: 'bakery',
    shopSlug: 'giri-cafe',
    shopName: 'Giri Café',
    price: 95,
    description: 'Crunchy butter cookies packed with roasted almond flakes.',
    image: 'https://images.unsplash.com/photo-1499636136210-6f4ee915583e?w=800&auto=format&fit=crop&q=85&v=dish-cf-ck4',
    dietary: ['veg'],
    prepTime: 2,
    available: true,
    customizations: [{ name: 'Extra Almond Flakes', price: 15 }]
  },
  {
    id: 'dish-cf-ck5',
    name: 'Crisp Toasted Coconut Macaroon Cookies (3pcs)',
    category: 'bakery',
    shopSlug: 'giri-cafe',
    shopName: 'Giri Café',
    price: 85,
    description: 'Golden baked coconut macaroon cookies with sweet toasted coconut flakes.',
    image: 'https://images.unsplash.com/photo-1499636136210-6f4ee915583e?w=800&auto=format&fit=crop&q=85&v=dish-cf-ck5',
    dietary: ['veg'],
    prepTime: 2,
    available: true,
    customizations: [{ name: 'Chocolate Dip Coating', price: 20 }]
  },

  // 18. DESSERTS
  {
    id: 'dish-cf-ds1',
    name: 'Warm Fudgy Walnut Chocolate Brownie',
    category: 'desserts',
    shopSlug: 'giri-cafe',
    shopName: 'Giri Café',
    price: 150,
    description: 'Dense fudgy chocolate brownie loaded with roasted walnuts & chocolate sauce.',
    image: 'https://images.unsplash.com/photo-1606313564200-e75d5e30476c?w=800&auto=format&fit=crop&q=85&v=dish-cf-ds1',
    dietary: ['veg', 'chef-special'],
    prepTime: 4,
    available: true,
    customizations: [{ name: 'Warm Up Service', price: 0 }]
  },
  {
    id: 'dish-cf-ds2',
    name: 'Sizzling Brownie with Vanilla Ice Cream',
    category: 'desserts',
    shopSlug: 'giri-cafe',
    shopName: 'Giri Café',
    price: 210,
    description: 'Warm brownie served on sizzling iron plate topped with vanilla scoop & hot fudge.',
    image: 'https://images.unsplash.com/photo-1606313564200-e75d5e30476c?w=800&auto=format&fit=crop&q=85&v=dish-cf-ds2',
    dietary: ['veg', 'chef-special'],
    prepTime: 6,
    available: true,
    customizations: [{ name: 'Extra Hot Fudge Drizzle', price: 25 }]
  },
  {
    id: 'dish-cf-ds3',
    name: 'New York Baked Blueberry Cheesecake Slice',
    category: 'desserts',
    shopSlug: 'giri-cafe',
    shopName: 'Giri Café',
    price: 240,
    description: 'Classic rich baked cheesecake on graham cracker crust topped with wild blueberry compote.',
    image: 'https://images.unsplash.com/photo-1533134242443-d4fd215305ad?w=800&auto=format&fit=crop&q=85&v=dish-cf-ds3',
    dietary: ['veg', 'chef-special'],
    prepTime: 3,
    available: true,
    customizations: [{ name: 'Extra Blueberry Sauce', price: 30 }]
  },
  {
    id: 'dish-cf-ds4',
    name: 'Classic Italian Espresso Mascarpone Tiramisu',
    category: 'desserts',
    shopSlug: 'giri-cafe',
    shopName: 'Giri Café',
    price: 230,
    description: 'Ladyfinger biscuits soaked in espresso & dark rum syrup, layered with mascarpone cream & cocoa.',
    image: 'https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=800&auto=format&fit=crop&q=85&v=dish-cf-ds4',
    dietary: ['veg', 'chef-special'],
    prepTime: 3,
    available: true,
    customizations: [{ name: 'Cocoa Powder Dust Extra', price: 0 }]
  },
  {
    id: 'dish-cf-ds5',
    name: 'Silky Smooth Belgian Dark Chocolate Mousse',
    category: 'desserts',
    shopSlug: 'giri-cafe',
    shopName: 'Giri Café',
    price: 180,
    description: 'Airy whipped dark chocolate mousse served in dessert glass topped with chocolate curls.',
    image: 'https://images.unsplash.com/photo-1541781774459-bb2af2f05b55?w=800&auto=format&fit=crop&q=85&v=dish-cf-ds5',
    dietary: ['veg'],
    prepTime: 3,
    available: true,
    customizations: [{ name: 'Whipped Cream Top', price: 20 }]
  },
  {
    id: 'dish-cf-ds6',
    name: 'Chilled Creamy Fresh Mix Fruit Custard',
    category: 'desserts',
    shopSlug: 'giri-cafe',
    shopName: 'Giri Café',
    price: 140,
    description: 'Vanilla milk custard loaded with fresh chopped apples, grapes, bananas, and pomegranates.',
    image: 'https://images.unsplash.com/photo-1587314168485-3236d6710814?w=800&auto=format&fit=crop&q=85&v=dish-cf-ds6',
    dietary: ['veg'],
    prepTime: 3,
    available: true,
    customizations: [{ name: 'Tutti Frutti Garnish', price: 15 }]
  },

  // 19. ICE CREAM
  {
    id: 'dish-cf-ic1',
    name: 'Pure Bourbon Vanilla Bean Ice Cream Scoop',
    category: 'desserts',
    shopSlug: 'giri-cafe',
    shopName: 'Giri Café',
    price: 90,
    description: 'Smooth rich ice cream prepared with pure Madagascar vanilla bean specs.',
    image: 'https://images.unsplash.com/photo-1570197788417-0e82375c9371?w=800&auto=format&fit=crop&q=85&v=dish-cf-ic1',
    dietary: ['veg'],
    prepTime: 2,
    available: true,
    customizations: [{ name: 'Double Scoop Combo', price: 70 }]
  },
  {
    id: 'dish-cf-ic2',
    name: 'Rich Belgian Dark Chocolate Ice Cream Scoop',
    category: 'desserts',
    shopSlug: 'giri-cafe',
    shopName: 'Giri Café',
    price: 100,
    description: 'Deep intense dark chocolate ice cream scoop with chocolate flakes.',
    image: 'https://images.unsplash.com/photo-1570197788417-0e82375c9371?w=800&auto=format&fit=crop&q=85&v=dish-cf-ic2',
    dietary: ['veg'],
    prepTime: 2,
    available: true,
    customizations: [{ name: 'Hot Fudge Sauce Drizzle', price: 20 }]
  },
  {
    id: 'dish-cf-ic3',
    name: 'Creamy Fresh Strawberry Scoop Ice Cream',
    category: 'desserts',
    shopSlug: 'giri-cafe',
    shopName: 'Giri Café',
    price: 95,
    description: 'Refreshing fruit ice cream made with real strawberry chunks.',
    image: 'https://images.unsplash.com/photo-1570197788417-0e82375c9371?w=800&auto=format&fit=crop&q=85&v=dish-cf-ic3',
    dietary: ['veg'],
    prepTime: 2,
    available: true,
    customizations: [{ name: 'Strawberry Syrup Drizzle', price: 15 }]
  },
  {
    id: 'dish-cf-ic4',
    name: 'Crunchy Nutty Butterscotch Ice Cream Scoop',
    category: 'desserts',
    shopSlug: 'giri-cafe',
    shopName: 'Giri Café',
    price: 100,
    description: 'Golden caramel ice cream packed with crispy butterscotch praline nuts.',
    image: 'https://images.unsplash.com/photo-1570197788417-0e82375c9371?w=800&auto=format&fit=crop&q=85&v=dish-cf-ic4',
    dietary: ['veg'],
    prepTime: 2,
    available: true,
    customizations: [{ name: 'Caramel Drizzle', price: 15 }]
  },
  {
    id: 'dish-cf-ic5',
    name: 'Alphonso Mango Fruit Scoop Ice Cream',
    category: 'desserts',
    shopSlug: 'giri-cafe',
    shopName: 'Giri Café',
    price: 105,
    description: 'Tropical rich mango ice cream prepared with pure Alphonso pulp.',
    image: 'https://images.unsplash.com/photo-1570197788417-0e82375c9371?w=800&auto=format&fit=crop&q=85&v=dish-cf-ic5',
    dietary: ['veg'],
    prepTime: 2,
    available: true,
    customizations: [{ name: 'Mango Sauce Drizzle', price: 15 }]
  },
  {
    id: 'dish-cf-ic6',
    name: 'Double Scoop Hot Fudge Chocolate Sundae',
    category: 'desserts',
    shopSlug: 'giri-cafe',
    shopName: 'Giri Café',
    price: 180,
    description: 'Two scoops of vanilla & chocolate ice cream topped with hot fudge, roasted peanuts, and cherry.',
    image: 'https://images.unsplash.com/photo-1570197788417-0e82375c9371?w=800&auto=format&fit=crop&q=85&v=dish-cf-ic6',
    dietary: ['veg', 'chef-special'],
    prepTime: 4,
    available: true,
    customizations: [{ name: 'Extra Hot Fudge', price: 25 }]
  },

  // 20. CAFE COMBOS
  {
    id: 'dish-cf-cb1',
    name: 'Cappuccino & Veg Club Toast Sandwich Combo',
    category: 'combos',
    shopSlug: 'giri-cafe',
    shopName: 'Giri Café',
    price: 270,
    description: '1 Hot Frothy Cappuccino + 1 Fresh Grilled Veggie Toast Sandwich.',
    image: 'https://images.unsplash.com/photo-1528735602780-2552fd46c7af?w=800&auto=format&fit=crop&q=85&v=dish-cf-cb1',
    dietary: ['veg', 'chef-special'],
    prepTime: 10,
    available: true,
    customizations: [{ name: 'Upgrade to Cold Coffee', price: 30 }]
  },
  {
    id: 'dish-cf-cb2',
    name: 'Hot Cafe Latte & Warm Chocolate Brownie Combo',
    category: 'combos',
    shopSlug: 'giri-cafe',
    shopName: 'Giri Café',
    price: 280,
    description: '1 Hot Creamy Cafe Latte + 1 Warm Fudgy Walnut Brownie slice.',
    image: 'https://images.unsplash.com/photo-1606313564200-e75d5e30476c?w=800&auto=format&fit=crop&q=85&v=dish-cf-cb2',
    dietary: ['veg', 'chef-special'],
    prepTime: 8,
    available: true,
    customizations: [{ name: 'Add Vanilla Scoop to Brownie', price: 40 }]
  },
  {
    id: 'dish-cf-cb3',
    name: 'Masala Chai & Choco-Chip Cookies Pair',
    category: 'combos',
    shopSlug: 'giri-cafe',
    shopName: 'Giri Café',
    price: 150,
    description: '1 Kulhad Spiced Masala Chai + 2 Fresh Baked Giant Choco-Chip Cookies.',
    image: 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?w=800&auto=format&fit=crop&q=85&v=dish-cf-cb3',
    dietary: ['veg'],
    prepTime: 6,
    available: true,
    customizations: [{ name: 'Extra Chai Cup', price: 50 }]
  },
  {
    id: 'dish-cf-cb4',
    name: 'Classic Cheese Burger with Fries & Dip Combo',
    category: 'combos',
    shopSlug: 'giri-cafe',
    shopName: 'Giri Café',
    price: 310,
    description: '1 Double Cheese Burger + 1 Regular Salted French Fries + 1 Mayo Dip.',
    image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=800&auto=format&fit=crop&q=85&v=dish-cf-cb4',
    dietary: ['veg'],
    prepTime: 12,
    available: true,
    customizations: [{ name: 'Add Coke Drink', price: 45 }]
  },
  {
    id: 'dish-cf-cb5',
    name: 'Personal Margherita Pizza & Virgin Mojito Combo',
    category: 'combos',
    shopSlug: 'giri-cafe',
    shopName: 'Giri Café',
    price: 390,
    description: '1 Personal 7" Margherita Basil Pizza + 1 Chilled Sparkling Virgin Mojito.',
    image: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=800&auto=format&fit=crop&q=85&v=dish-cf-cb5',
    dietary: ['veg', 'chef-special'],
    prepTime: 15,
    available: true,
    customizations: [{ name: 'Upgrade to Farmhouse Pizza', price: 50 }]
  }
`;

const cafeCode = `export const GIRI_CAFE_DISHES: MenuItem[] = [\n${completeCafeCatalog}\n];\n`;

const cfIndex = dishesContent.indexOf("export const GIRI_CAFE_DISHES");
if (cfIndex !== -1) {
  const endIndex = dishesContent.indexOf("const RAW_INITIAL_DISHES");
  dishesContent = dishesContent.substring(0, cfIndex) + cafeCode + dishesContent.substring(endIndex);
} else {
  dishesContent = dishesContent.replace(
    "const RAW_INITIAL_DISHES: MenuItem[] = [",
    `${cafeCode}\nconst RAW_INITIAL_DISHES: MenuItem[] = [\n  ...GIRI_CAFE_DISHES,`
  );
}

dishesContent = dishesContent.replace(
  /const versionKey = 'giri_dishes_[^']+';/,
  "const versionKey = 'giri_dishes_v36_cafe_all_20_categories_populated';"
);

fs.writeFileSync(dishesPath, dishesContent, 'utf8');
console.log('Successfully updated dishes.ts with 100+ authentic dishes for Giri Café!');
