const fs = require('fs');

const dishesPath = 'c:/Users/lenovo/OneDrive/Desktop/resturant/frontend/data/dishes.ts';
let dishesContent = fs.readFileSync(dishesPath, 'utf8');

const completeSeafoodCatalog = `
  // ==========================================
  // GIRI SEAFOOD & LOUNGE COMPLETE 110+ DISHES
  // ==========================================

  // 1. FISH SPECIALS
  {
    id: 'dish-sf-ff1',
    name: 'Tawa Crispy Spiced King Fish Fry',
    category: 'starters',
    shopSlug: 'giri-seafood',
    shopName: 'Giri Seafood & Lounge',
    price: 440,
    description: 'King fish slices marinated in red chili, ginger-garlic, lemon, and tawa fried crisp.',
    image: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=800&auto=format&fit=crop&q=85&v=dish-sf-ff1',
    dietary: ['non-veg', 'spicy'],
    prepTime: 15,
    available: true,
    customizations: [{ name: 'Lemon Slice Extra', price: 0 }]
  },
  {
    id: 'dish-sf-ff2',
    name: 'Charcoal Grilled Ajwaini Fish Tikka',
    category: 'starters',
    shopSlug: 'giri-seafood',
    shopName: 'Giri Seafood & Lounge',
    price: 480,
    description: 'Boneless fish tikka chunks infused with carom seeds (ajwain), yellow chili, and mustard oil.',
    image: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=800&auto=format&fit=crop&q=85&v=dish-sf-ff2',
    dietary: ['non-veg', 'chef-special'],
    prepTime: 15,
    available: true,
    customizations: [{ name: 'Tartar Dip Tub', price: 25 }]
  },
  {
    id: 'dish-sf-ff3',
    name: 'Mediterranean Herb Grilled Seabass',
    category: 'mains',
    shopSlug: 'giri-seafood',
    shopName: 'Giri Seafood & Lounge',
    price: 650,
    description: 'Fresh seabass fillet rubbed with garlic, oregano, olive oil, and charred lemon slices.',
    image: 'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?w=800&auto=format&fit=crop&q=85&v=dish-sf-ff3',
    dietary: ['non-veg'],
    prepTime: 18,
    available: true,
    customizations: [{ name: 'Side Roasted Potatoes', price: 40 }]
  },
  {
    id: 'dish-sf-ff4',
    name: 'Whole Tandoori Grilled Pomfret',
    category: 'mains',
    shopSlug: 'giri-seafood',
    shopName: 'Giri Seafood & Lounge',
    price: 620,
    description: 'Whole fresh pomfret fish marinated in coastal spices and roasted golden in clay tandoor.',
    image: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=800&auto=format&fit=crop&q=85&v=dish-sf-ff4',
    dietary: ['non-veg', 'chef-special'],
    prepTime: 20,
    available: true,
    customizations: [{ name: 'Garlic Butter Dip', price: 30 }]
  },
  {
    id: 'dish-sf-ff5',
    name: 'Golden Battered Crispy Fish Fingers',
    category: 'starters',
    shopSlug: 'giri-seafood',
    shopName: 'Giri Seafood & Lounge',
    price: 360,
    description: 'Crispy breaded fish goujons served with tangy tartar dip.',
    image: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=800&auto=format&fit=crop&q=85&v=dish-sf-ff5',
    dietary: ['non-veg'],
    prepTime: 12,
    available: true,
    customizations: [{ name: 'Cocktail Sauce Dip', price: 20 }]
  },
  {
    id: 'dish-sf-ff6',
    name: 'Pan Seared Lemon Pepper Fish Fillet',
    category: 'mains',
    shopSlug: 'giri-seafood',
    shopName: 'Giri Seafood & Lounge',
    price: 490,
    description: 'White fish fillet seared in lemon butter sauce and cracked black pepper.',
    image: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=800&auto=format&fit=crop&q=85&v=dish-sf-ff6',
    dietary: ['non-veg'],
    prepTime: 14,
    available: true,
    customizations: [{ name: 'Extra Lemon Glaze', price: 15 }]
  },

  // 2. PRAWNS SPECIALS
  {
    id: 'dish-sf-pr1',
    name: 'Spicy Andhra Royyala Prawn Fry',
    category: 'starters',
    shopSlug: 'giri-seafood',
    shopName: 'Giri Seafood & Lounge',
    price: 460,
    description: 'Fresh prawns pan-fried in onion-tomato masala, curry leaves, and coconut reduction.',
    image: 'https://images.unsplash.com/photo-1565680018434-b513d5e5fd47?w=800&auto=format&fit=crop&q=85&v=dish-sf-pr1',
    dietary: ['non-veg', 'spicy', 'chef-special'],
    prepTime: 14,
    available: true,
    customizations: [{ name: 'Extra Prawns (3pcs)', price: 90 }]
  },
  {
    id: 'dish-sf-pr2',
    name: 'Sautéed Garlic Butter Tiger Prawns',
    category: 'starters',
    shopSlug: 'giri-seafood',
    shopName: 'Giri Seafood & Lounge',
    price: 490,
    description: 'Succulent tiger prawns tossed in minced garlic, parsley, and french butter.',
    image: 'https://images.unsplash.com/photo-1565680018434-b513d5e5fd47?w=800&auto=format&fit=crop&q=85&v=dish-sf-pr2',
    dietary: ['non-veg', 'chef-special'],
    prepTime: 14,
    available: true,
    customizations: [{ name: 'Garlic Toast Toast', price: 30 }]
  },
  {
    id: 'dish-sf-pr3',
    name: 'Creamy Garlic Butter Jumbo Prawns',
    category: 'mains',
    shopSlug: 'giri-seafood',
    shopName: 'Giri Seafood & Lounge',
    price: 520,
    description: 'Jumbo prawns pan-seared in rich garlic cream sauce and herbs.',
    image: 'https://images.unsplash.com/photo-1565680018434-b513d5e5fd47?w=800&auto=format&fit=crop&q=85&v=dish-sf-pr3',
    dietary: ['non-veg'],
    prepTime: 15,
    available: true,
    customizations: [{ name: 'Extra Garlic Dip', price: 25 }]
  },
  {
    id: 'dish-sf-pr4',
    name: 'Indo-Chinese Spicy Garlic Chilli Prawns',
    category: 'starters',
    shopSlug: 'giri-seafood',
    shopName: 'Giri Seafood & Lounge',
    price: 480,
    description: 'Crispy prawns tossed with red chili paste, soy sauce, garlic, and spring onions.',
    image: 'https://images.unsplash.com/photo-1565680018434-b513d5e5fd47?w=800&auto=format&fit=crop&q=85&v=dish-sf-pr4',
    dietary: ['non-veg', 'spicy'],
    prepTime: 14,
    available: true,
    customizations: [{ name: 'Schezwan Style', price: 15 }]
  },
  {
    id: 'dish-sf-pr5',
    name: 'Tandoori Roasted Spiced Prawn Tikka',
    category: 'starters',
    shopSlug: 'giri-seafood',
    shopName: 'Giri Seafood & Lounge',
    price: 510,
    description: 'Prawns marinated in hung curd, Kashmiri chili, and carom seeds, roasted on tandoor skewers.',
    image: 'https://images.unsplash.com/photo-1565680018434-b513d5e5fd47?w=800&auto=format&fit=crop&q=85&v=dish-sf-pr5',
    dietary: ['non-veg'],
    prepTime: 15,
    available: true,
    customizations: [{ name: 'Mint Chutney', price: 15 }]
  },
  {
    id: 'dish-sf-pr6',
    name: 'Royal Tandoori King Prawns',
    category: 'mains',
    shopSlug: 'giri-seafood',
    shopName: 'Giri Seafood & Lounge',
    price: 540,
    description: 'Whole jumbo prawns grilled with royal makhani spice marinade.',
    image: 'https://images.unsplash.com/photo-1565680018434-b513d5e5fd47?w=800&auto=format&fit=crop&q=85&v=dish-sf-pr6',
    dietary: ['non-veg', 'chef-special'],
    prepTime: 16,
    available: true,
    customizations: [{ name: 'Butter Drizzle', price: 20 }]
  },

  // 3. CRAB SPECIALS
  {
    id: 'dish-sf-cr1',
    name: 'Chettinad Spicy Mud Crab Masala',
    category: 'mains',
    shopSlug: 'giri-seafood',
    shopName: 'Giri Seafood & Lounge',
    price: 580,
    description: 'Fresh mud crab cooked in thick Tamil Nadu Chettinad spice roasted coconut gravy.',
    image: 'https://images.unsplash.com/photo-1559742811-822863c46f43?w=800&auto=format&fit=crop&q=85&v=dish-sf-cr1',
    dietary: ['non-veg', 'spicy', 'chef-special'],
    prepTime: 20,
    available: true,
    customizations: [{ name: 'Extra Crab Gravy', price: 40 }]
  },
  {
    id: 'dish-sf-cr2',
    name: 'Crushed Black Pepper Crab Chukka Fry',
    category: 'starters',
    shopSlug: 'giri-seafood',
    shopName: 'Giri Seafood & Lounge',
    price: 590,
    description: 'Whole soft shell crab wok fried with black pepper, curry leaves, and shallots.',
    image: 'https://images.unsplash.com/photo-1559742811-822863c46f43?w=800&auto=format&fit=crop&q=85&v=dish-sf-cr2',
    dietary: ['non-veg', 'spicy'],
    prepTime: 18,
    available: true,
    customizations: [{ name: 'Extra Black Pepper', price: 15 }]
  },
  {
    id: 'dish-sf-cr3',
    name: 'Malabar Spiced Roasted Crab',
    category: 'mains',
    shopSlug: 'giri-seafood',
    shopName: 'Giri Seafood & Lounge',
    price: 610,
    description: 'Kerala style roasted crab cooked in coconut oil, fennel, and fried onions.',
    image: 'https://images.unsplash.com/photo-1559742811-822863c46f43?w=800&auto=format&fit=crop&q=85&v=dish-sf-cr3',
    dietary: ['non-veg'],
    prepTime: 20,
    available: true,
    customizations: [{ name: 'Side Appam (2pcs)', price: 50 }]
  },
  {
    id: 'dish-sf-cr4',
    name: 'Coastal Coconut Tamarind Crab Curry',
    category: 'mains',
    shopSlug: 'giri-seafood',
    shopName: 'Giri Seafood & Lounge',
    price: 570,
    description: 'Crab simmered in coconut milk, raw mango, and tamarind curry sauce.',
    image: 'https://images.unsplash.com/photo-1559742811-822863c46f43?w=800&auto=format&fit=crop&q=85&v=dish-sf-cr4',
    dietary: ['non-veg'],
    prepTime: 20,
    available: true,
    customizations: [{ name: 'Steamed Rice Portion', price: 40 }]
  },
  {
    id: 'dish-sf-cr5',
    name: 'Butter Garlic Roasted Sea Crab',
    category: 'starters',
    shopSlug: 'giri-seafood',
    shopName: 'Giri Seafood & Lounge',
    price: 630,
    description: 'Fresh sea crab roasted with garlic butter, white wine reduction, and herbs.',
    image: 'https://images.unsplash.com/photo-1559742811-822863c46f43?w=800&auto=format&fit=crop&q=85&v=dish-sf-cr5',
    dietary: ['non-veg', 'chef-special'],
    prepTime: 20,
    available: true,
    customizations: [{ name: 'Garlic Bread Pair', price: 40 }]
  },

  // 4. SQUID & CALAMARI
  {
    id: 'dish-sf-sq1',
    name: 'Crispy Golden Fried Calamari Rings',
    category: 'starters',
    shopSlug: 'giri-seafood',
    shopName: 'Giri Seafood & Lounge',
    price: 390,
    description: 'Tender squid rings dipped in seasoned batter and fried crisp, served with garlic mayo.',
    image: 'https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?w=800&auto=format&fit=crop&q=85&v=dish-sf-sq1',
    dietary: ['non-veg'],
    prepTime: 12,
    available: true,
    customizations: [{ name: 'Spicy Dip', price: 20 }]
  },
  {
    id: 'dish-sf-sq2',
    name: 'Salt & Pepper Crispy Calamari',
    category: 'starters',
    shopSlug: 'giri-seafood',
    shopName: 'Giri Seafood & Lounge',
    price: 410,
    description: 'Wok tossed calamari seasoned with crushed sea salt, szechuan pepper, and scallions.',
    image: 'https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?w=800&auto=format&fit=crop&q=85&v=dish-sf-sq2',
    dietary: ['non-veg', 'spicy'],
    prepTime: 12,
    available: true,
    customizations: [{ name: 'Extra Pepper Dip', price: 15 }]
  },
  {
    id: 'dish-sf-sq3',
    name: 'Black Pepper Tossed Squid Roast',
    category: 'starters',
    shopSlug: 'giri-seafood',
    shopName: 'Giri Seafood & Lounge',
    price: 420,
    description: 'Squid rings pan-roasted with curry leaves, cracked black pepper, and onions.',
    image: 'https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?w=800&auto=format&fit=crop&q=85&v=dish-sf-sq3',
    dietary: ['non-veg', 'spicy'],
    prepTime: 14,
    available: true,
    customizations: [{ name: 'Lemon Squeeze', price: 0 }]
  },
  {
    id: 'dish-sf-sq4',
    name: 'Spicy Garlic Chilli Squid Dry',
    category: 'starters',
    shopSlug: 'giri-seafood',
    shopName: 'Giri Seafood & Lounge',
    price: 400,
    description: 'Tender squid tossed in spicy garlic red chili sauce and green capsicum.',
    image: 'https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?w=800&auto=format&fit=crop&q=85&v=dish-sf-sq4',
    dietary: ['non-veg', 'spicy'],
    prepTime: 12,
    available: true,
    customizations: [{ name: 'Schezwan Mayo', price: 20 }]
  },
  {
    id: 'dish-sf-sq5',
    name: 'Charcoal Grilled Lemon Herb Whole Squid',
    category: 'mains',
    shopSlug: 'giri-seafood',
    shopName: 'Giri Seafood & Lounge',
    price: 460,
    description: 'Whole squid marinated in lemon juice, olive oil, garlic, grilled over charcoal flame.',
    image: 'https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?w=800&auto=format&fit=crop&q=85&v=dish-sf-sq5',
    dietary: ['non-veg', 'chef-special'],
    prepTime: 15,
    available: true,
    customizations: [{ name: 'Side Green Salad', price: 30 }]
  },

  // 5. LOBSTER SPECIALS
  {
    id: 'dish-sf-lb1',
    name: 'Charcoal Fire Grilled Whole Lobster',
    category: 'mains',
    shopSlug: 'giri-seafood',
    shopName: 'Giri Seafood & Lounge',
    price: 1250,
    description: 'Fresh whole lobster split and grilled on charcoal with garlic butter herb glaze.',
    image: 'https://images.unsplash.com/photo-1553240799-36bbf332a5c3?w=800&auto=format&fit=crop&q=85&v=dish-sf-lb1',
    dietary: ['non-veg', 'chef-special'],
    prepTime: 25,
    available: true,
    customizations: [{ name: 'Extra Garlic Butter Dip', price: 40 }]
  },
  {
    id: 'dish-sf-lb2',
    name: 'Creamy Garlic Butter Glazed Lobster',
    category: 'mains',
    shopSlug: 'giri-seafood',
    shopName: 'Giri Seafood & Lounge',
    price: 1350,
    description: 'Whole lobster tail cooked in rich garlic cream butter reduction sauce.',
    image: 'https://images.unsplash.com/photo-1553240799-36bbf332a5c3?w=800&auto=format&fit=crop&q=85&v=dish-sf-lb2',
    dietary: ['non-veg', 'chef-special'],
    prepTime: 25,
    available: true,
    customizations: [{ name: 'Side Herb Rice', price: 50 }]
  },
  {
    id: 'dish-sf-lb3',
    name: 'Royal Baked Cheese Lobster Thermidor',
    category: 'mains',
    shopSlug: 'giri-seafood',
    shopName: 'Giri Seafood & Lounge',
    price: 1450,
    description: 'Lobster meat cooked in white wine mustard cream sauce, stuffed in shell, baked with Gruyère cheese.',
    image: 'https://images.unsplash.com/photo-1553240799-36bbf332a5c3?w=800&auto=format&fit=crop&q=85&v=dish-sf-lb3',
    dietary: ['non-veg', 'chef-special'],
    prepTime: 25,
    available: true,
    customizations: [{ name: 'Extra Melted Cheese', price: 50 }]
  },
  {
    id: 'dish-sf-lb4',
    name: 'Coastal Spicy Chili Garlic Roasted Lobster',
    category: 'mains',
    shopSlug: 'giri-seafood',
    shopName: 'Giri Seafood & Lounge',
    price: 1300,
    description: 'Fresh lobster roasted with red chili paste, tamarind, and fried garlic.',
    image: 'https://images.unsplash.com/photo-1553240799-36bbf332a5c3?w=800&auto=format&fit=crop&q=85&v=dish-sf-lb4',
    dietary: ['non-veg', 'spicy'],
    prepTime: 25,
    available: true,
    customizations: [{ name: 'Side Garlic Bread', price: 40 }]
  },

  // 6. SEAFOOD STARTERS
  {
    id: 'dish-sf-st1',
    name: 'Spicy Coastal Mixed Seafood 65',
    category: 'starters',
    shopSlug: 'giri-seafood',
    shopName: 'Giri Seafood & Lounge',
    price: 420,
    description: 'Crispy fried fish nuggets and prawns tossed in South Indian 65 chili garlic sauce.',
    image: 'https://images.unsplash.com/photo-1610057099443-fde8c4d50f91?w=800&auto=format&fit=crop&q=85&v=dish-sf-st1',
    dietary: ['non-veg', 'spicy'],
    prepTime: 14,
    available: true,
    customizations: [{ name: 'Extra Curry Leaf Tempering', price: 15 }]
  },
  {
    id: 'dish-sf-st2',
    name: 'Crunchy Sesame Battered Fish Strips',
    category: 'starters',
    shopSlug: 'giri-seafood',
    shopName: 'Giri Seafood & Lounge',
    price: 380,
    description: 'White fish strips coated in sesame seeds and fried till crispy, served with sweet chili sauce.',
    image: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=800&auto=format&fit=crop&q=85&v=dish-sf-st2',
    dietary: ['non-veg'],
    prepTime: 12,
    available: true,
    customizations: [{ name: 'Chili Dip', price: 15 }]
  },
  {
    id: 'dish-sf-st3',
    name: 'Bite-Sized Crunchy Prawn Popcorn',
    category: 'starters',
    shopSlug: 'giri-seafood',
    shopName: 'Giri Seafood & Lounge',
    price: 390,
    description: 'Mini prawns coated in spiced flour and fried crunchy, served with chipotle mayo.',
    image: 'https://images.unsplash.com/photo-1565680018434-b513d5e5fd47?w=800&auto=format&fit=crop&q=85&v=dish-sf-st3',
    dietary: ['non-veg'],
    prepTime: 12,
    available: true,
    customizations: [{ name: 'Chipotle Dip Tub', price: 20 }]
  },
  {
    id: 'dish-sf-st4',
    name: 'Char-Grilled Mixed Seafood Kebab',
    category: 'starters',
    shopSlug: 'giri-seafood',
    shopName: 'Giri Seafood & Lounge',
    price: 450,
    description: 'Skewered fish and prawns marinated in yellow chili and tandoori herbs.',
    image: 'https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?w=800&auto=format&fit=crop&q=85&v=dish-sf-st4',
    dietary: ['non-veg', 'chef-special'],
    prepTime: 15,
    available: true,
    customizations: [{ name: 'Mint Sauce', price: 15 }]
  },
  {
    id: 'dish-sf-st5',
    name: 'Carom Seed Spiced Punjabi Fish Amritsari',
    category: 'starters',
    shopSlug: 'giri-seafood',
    shopName: 'Giri Seafood & Lounge',
    price: 420,
    description: 'Gram flour and ajwain battered fish fillets fried golden, served with mint chutney.',
    image: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=800&auto=format&fit=crop&q=85&v=dish-sf-st5',
    dietary: ['non-veg'],
    prepTime: 14,
    available: true,
    customizations: [{ name: 'Chaat Masala Sprinkle', price: 0 }]
  },

  // 7. SEAFOOD GRILL
  {
    id: 'dish-sf-gr1',
    name: 'Wood-Fired Norwegian Salmon Steak',
    category: 'mains',
    shopSlug: 'giri-seafood',
    shopName: 'Giri Seafood & Lounge',
    price: 680,
    description: 'Wild Norwegian salmon grilled skin-crisp with dill butter, sea salt, and capers.',
    image: 'https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=800&auto=format&fit=crop&q=85&v=dish-sf-gr1',
    dietary: ['non-veg', 'chef-special'],
    prepTime: 18,
    available: true,
    customizations: [{ name: 'Extra Capers & Lemon', price: 25 }]
  },
  {
    id: 'dish-sf-gr2',
    name: 'Herb Marinated Grilled Jumbo Prawns',
    category: 'starters',
    shopSlug: 'giri-seafood',
    shopName: 'Giri Seafood & Lounge',
    price: 540,
    description: 'Jumbo prawns grilled with rosemary, olive oil, sea salt, and lemon glaze.',
    image: 'https://images.unsplash.com/photo-1565680018434-b513d5e5fd47?w=800&auto=format&fit=crop&q=85&v=dish-sf-gr2',
    dietary: ['non-veg'],
    prepTime: 16,
    available: true,
    customizations: [{ name: 'Garlic Butter Dip', price: 30 }]
  },
  {
    id: 'dish-sf-gr3',
    name: 'Smoked Paprika Grilled Squid Skewers',
    category: 'starters',
    shopSlug: 'giri-seafood',
    shopName: 'Giri Seafood & Lounge',
    price: 440,
    description: 'Tender squid skewers grilled with smoked paprika, olive oil, and garlic.',
    image: 'https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?w=800&auto=format&fit=crop&q=85&v=dish-sf-gr3',
    dietary: ['non-veg'],
    prepTime: 14,
    available: true,
    customizations: [{ name: 'Lemon Wedge', price: 0 }]
  },
  {
    id: 'dish-sf-gr4',
    name: 'Flame Kissed Garlic Butter Crab',
    category: 'mains',
    shopSlug: 'giri-seafood',
    shopName: 'Giri Seafood & Lounge',
    price: 620,
    description: 'Whole blue sea crab charred over flame and finished in garlic parsley butter.',
    image: 'https://images.unsplash.com/photo-1559742811-822863c46f43?w=800&auto=format&fit=crop&q=85&v=dish-sf-gr4',
    dietary: ['non-veg', 'chef-special'],
    prepTime: 20,
    available: true,
    customizations: [{ name: 'Extra Butter Sauce', price: 35 }]
  },
  {
    id: 'dish-sf-gr5',
    name: 'Grand Oceanic Mixed Seafood Grill Platter',
    category: 'mains',
    shopSlug: 'giri-seafood',
    shopName: 'Giri Seafood & Lounge',
    price: 980,
    description: 'Assorted grilled salmon steak, jumbo prawns, calamari rings, and grilled fish fillets.',
    image: 'https://images.unsplash.com/photo-1553240799-36bbf332a5c3?w=800&auto=format&fit=crop&q=85&v=dish-sf-gr5',
    dietary: ['non-veg', 'chef-special'],
    prepTime: 22,
    available: true,
    customizations: [{ name: 'Side Garlic Bread (4pcs)', price: 60 }]
  },

  // 8. SEAFOOD TANDOOR
  {
    id: 'dish-sf-td1',
    name: 'Bhatti Roasted Tandoori Tiger Prawns',
    category: 'starters',
    shopSlug: 'giri-seafood',
    shopName: 'Giri Seafood & Lounge',
    price: 520,
    description: 'Tiger prawns coated in red tandoori marinade and cooked over hot charcoal coals.',
    image: 'https://images.unsplash.com/photo-1565680018434-b513d5e5fd47?w=800&auto=format&fit=crop&q=85&v=dish-sf-td1',
    dietary: ['non-veg', 'spicy'],
    prepTime: 15,
    available: true,
    customizations: [{ name: 'Mint Chutney', price: 15 }]
  },
  {
    id: 'dish-sf-td2',
    name: 'Ajwaini Tandoori Red Snapper',
    category: 'mains',
    shopSlug: 'giri-seafood',
    shopName: 'Giri Seafood & Lounge',
    price: 580,
    description: 'Red snapper fillet marinated in yogurt, ajwain seeds, turmeric, and tandoor roasted.',
    image: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=800&auto=format&fit=crop&q=85&v=dish-sf-td2',
    dietary: ['non-veg'],
    prepTime: 18,
    available: true,
    customizations: [{ name: 'Extra Lemon Wedges', price: 0 }]
  },
  {
    id: 'dish-sf-td3',
    name: 'Claypot Tandoori Spiced Mud Crab',
    category: 'mains',
    shopSlug: 'giri-seafood',
    shopName: 'Giri Seafood & Lounge',
    price: 640,
    description: 'Fresh mud crab basted in red chili ginger marinade and roasted in tandoori oven.',
    image: 'https://images.unsplash.com/photo-1559742811-822863c46f43?w=800&auto=format&fit=crop&q=85&v=dish-sf-td3',
    dietary: ['non-veg', 'chef-special'],
    prepTime: 20,
    available: true,
    customizations: [{ name: 'Side Naan', price: 50 }]
  },
  {
    id: 'dish-sf-td4',
    name: 'Assorted Fish & Prawn Tikka Platter',
    category: 'starters',
    shopSlug: 'giri-seafood',
    shopName: 'Giri Seafood & Lounge',
    price: 590,
    description: 'Combination of tandoori fish tikka, malai fish tikka, and tandoori prawns.',
    image: 'https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?w=800&auto=format&fit=crop&q=85&v=dish-sf-td4',
    dietary: ['non-veg', 'chef-special'],
    prepTime: 18,
    available: true,
    customizations: [{ name: 'Extra Mint Dip', price: 20 }]
  },

  // 9. COASTAL SPECIALS
  {
    id: 'dish-sf-cs1',
    name: 'Andhra Spicy Chepala Pulusu Fish Curry',
    category: 'mains',
    shopSlug: 'giri-seafood',
    shopName: 'Giri Seafood & Lounge',
    price: 450,
    description: 'Traditional Andhra fish curry cooked with raw mango, tamarind juice, and red chilies.',
    image: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=800&auto=format&fit=crop&q=85&v=dish-sf-cs1',
    dietary: ['non-veg', 'spicy', 'chef-special'],
    prepTime: 18,
    available: true,
    customizations: [{ name: 'Steamed Rice Side', price: 40 }]
  },
  {
    id: 'dish-sf-cs2',
    name: 'Malabar Meen Curry in Coconut Milk',
    category: 'mains',
    shopSlug: 'giri-seafood',
    shopName: 'Giri Seafood & Lounge',
    price: 470,
    description: 'Kerala style fish curry simmered in coconut milk, kudampuli tamarind, and curry leaves.',
    image: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=800&auto=format&fit=crop&q=85&v=dish-sf-cs2',
    dietary: ['non-veg', 'chef-special'],
    prepTime: 18,
    available: true,
    customizations: [{ name: 'Appam Side (2pcs)', price: 50 }]
  },
  {
    id: 'dish-sf-cs3',
    name: 'Authentic Goan Kokum Coconut Fish Curry',
    category: 'mains',
    shopSlug: 'giri-seafood',
    shopName: 'Giri Seafood & Lounge',
    price: 480,
    description: 'Tangy Goan fish curry prepared with red chili paste, kokum, coriander, and fresh coconut.',
    image: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=800&auto=format&fit=crop&q=85&v=dish-sf-cs3',
    dietary: ['non-veg'],
    prepTime: 18,
    available: true,
    customizations: [{ name: 'Poi Bread Side', price: 40 }]
  },
  {
    id: 'dish-sf-cs4',
    name: 'Mangalorean Anjal Fish Ghee Roast Curry',
    category: 'mains',
    shopSlug: 'giri-seafood',
    shopName: 'Giri Seafood & Lounge',
    price: 510,
    description: 'King fish steaks roasted in pure desi ghee and fiery Byadgi chili spices.',
    image: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=800&auto=format&fit=crop&q=85&v=dish-sf-cs4',
    dietary: ['non-veg', 'spicy'],
    prepTime: 20,
    available: true,
    customizations: [{ name: 'Neer Dosa Side (3pcs)', price: 60 }]
  },
  {
    id: 'dish-sf-cs5',
    name: 'Kerala Style Coconut Prawn Curry',
    category: 'mains',
    shopSlug: 'giri-seafood',
    shopName: 'Giri Seafood & Lounge',
    price: 490,
    description: 'Prawns cooked in smooth coconut tamarind gravy with raw mango slices.',
    image: 'https://images.unsplash.com/photo-1565680018434-b513d5e5fd47?w=800&auto=format&fit=crop&q=85&v=dish-sf-cs5',
    dietary: ['non-veg'],
    prepTime: 16,
    available: true,
    customizations: [{ name: 'Extra Prawn Gravy', price: 35 }]
  },

  // 10. SEAFOOD CURRIES
  {
    id: 'dish-sf-sc1',
    name: 'Homestyle Tangy Coastal Fish Curry',
    category: 'mains',
    shopSlug: 'giri-seafood',
    shopName: 'Giri Seafood & Lounge',
    price: 430,
    description: 'Traditional home-style fish curry cooked with onions, tomatoes, tamarind, and fresh cilantro.',
    image: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=800&auto=format&fit=crop&q=85&v=dish-sf-sc1',
    dietary: ['non-veg'],
    prepTime: 16,
    available: true,
    customizations: [{ name: 'Steamed Basmati Rice', price: 40 }]
  },
  {
    id: 'dish-sf-sc2',
    name: 'Spiced Tomato Onion Prawn Gravy',
    category: 'mains',
    shopSlug: 'giri-seafood',
    shopName: 'Giri Seafood & Lounge',
    price: 470,
    description: 'Juicy prawns simmered in thick onion-tomato gravy with garam masala.',
    image: 'https://images.unsplash.com/photo-1565680018434-b513d5e5fd47?w=800&auto=format&fit=crop&q=85&v=dish-sf-sc2',
    dietary: ['non-veg'],
    prepTime: 16,
    available: true,
    customizations: [{ name: 'Butter Naan Side', price: 60 }]
  },
  {
    id: 'dish-sf-sc3',
    name: 'Traditional Roasted Spice Crab Gravy',
    category: 'mains',
    shopSlug: 'giri-seafood',
    shopName: 'Giri Seafood & Lounge',
    price: 560,
    description: 'Fresh crab cooked in whole ground spices and coconut paste.',
    image: 'https://images.unsplash.com/photo-1559742811-822863c46f43?w=800&auto=format&fit=crop&q=85&v=dish-sf-sc3',
    dietary: ['non-veg', 'spicy'],
    prepTime: 20,
    available: true,
    customizations: [{ name: 'Extra Crab Pieces', price: 100 }]
  },
  {
    id: 'dish-sf-sc4',
    name: 'Creamy White Coconut Milk Fish Curry',
    category: 'mains',
    shopSlug: 'giri-seafood',
    shopName: 'Giri Seafood & Lounge',
    price: 460,
    description: 'Mildly spiced white fish curry prepared with fresh coconut milk and ginger.',
    image: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=800&auto=format&fit=crop&q=85&v=dish-sf-sc4',
    dietary: ['non-veg'],
    prepTime: 16,
    available: true,
    customizations: [{ name: 'Green Chili Infusion', price: 0 }]
  },
  {
    id: 'dish-sf-sc5',
    name: 'Mixed Seafood Malabar Spiced Curry',
    category: 'mains',
    shopSlug: 'giri-seafood',
    shopName: 'Giri Seafood & Lounge',
    price: 580,
    description: 'Combination of fish, prawns, and calamari cooked in fragrant Malabar curry gravy.',
    image: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=800&auto=format&fit=crop&q=85&v=dish-sf-sc5',
    dietary: ['non-veg', 'chef-special'],
    prepTime: 20,
    available: true,
    customizations: [{ name: 'Extra Seafood Portions', price: 80 }]
  },

  // 11. SEAFOOD RICE & BIRYANI
  {
    id: 'dish-sf-rb1',
    name: 'Hyderabadi Dum Fish Tikka Biryani',
    category: 'biryani',
    shopSlug: 'giri-seafood',
    shopName: 'Giri Seafood & Lounge',
    price: 460,
    description: 'Charcoal grilled fish tikka layered with saffron basmati rice and cooked on slow dum, served with salan & raita.',
    image: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=800&auto=format&fit=crop&q=85&v=dish-sf-rb1',
    dietary: ['non-veg', 'chef-special'],
    prepTime: 20,
    available: true,
    customizations: [{ name: 'Extra Salan Bowl', price: 30 }]
  },
  {
    id: 'dish-sf-rb2',
    name: 'Coastal King Prawn Basmati Dum Biryani',
    category: 'biryani',
    shopSlug: 'giri-seafood',
    shopName: 'Giri Seafood & Lounge',
    price: 490,
    description: 'Jumbo prawns marinated in coastal spices and dum cooked with fragrant basmati rice.',
    image: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=800&auto=format&fit=crop&q=85&v=dish-sf-rb2',
    dietary: ['non-veg', 'chef-special'],
    prepTime: 20,
    available: true,
    customizations: [{ name: 'Extra Prawns (3pcs)', price: 100 }]
  },
  {
    id: 'dish-sf-rb3',
    name: 'Royal Mixed Seafood Saffron Biryani',
    category: 'biryani',
    shopSlug: 'giri-seafood',
    shopName: 'Giri Seafood & Lounge',
    price: 540,
    description: 'Fish fillet, tiger prawns, and calamari cooked on dum with zafrani basmati rice.',
    image: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=800&auto=format&fit=crop&q=85&v=dish-sf-rb3',
    dietary: ['non-veg', 'chef-special'],
    prepTime: 22,
    available: true,
    customizations: [{ name: 'Extra Raita Tub', price: 20 }]
  },
  {
    id: 'dish-sf-rb4',
    name: 'Spicy Andhra Style Prawn Basmati Pulao',
    category: 'rice-meals',
    shopSlug: 'giri-seafood',
    shopName: 'Giri Seafood & Lounge',
    price: 440,
    description: 'Prawns cooked with chittimutyalu basmati rice, green chili paste, and mint.',
    image: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=800&auto=format&fit=crop&q=85&v=dish-sf-rb4',
    dietary: ['non-veg', 'spicy'],
    prepTime: 18,
    available: true,
    customizations: [{ name: 'Ghee Drizzle', price: 20 }]
  },
  {
    id: 'dish-sf-rb5',
    name: 'Indo-Chinese Wok Seafood Fried Rice',
    category: 'rice-meals',
    shopSlug: 'giri-seafood',
    shopName: 'Giri Seafood & Lounge',
    price: 360,
    description: 'Wok tossed basmati rice with prawns, egg, spring onions, and soy sauce.',
    image: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=800&auto=format&fit=crop&q=85&v=dish-sf-rb5',
    dietary: ['non-veg'],
    prepTime: 14,
    available: true,
    customizations: [{ name: 'Schezwan Style', price: 20 }]
  },

  // 12. SEAFOOD NOODLES
  {
    id: 'dish-sf-nd1',
    name: 'Wok-Tossed Tiger Prawn Hakka Noodles',
    category: 'chinese',
    shopSlug: 'giri-seafood',
    shopName: 'Giri Seafood & Lounge',
    price: 370,
    description: 'Hakka noodles tossed in high flame wok with tiger prawns, bell peppers, and cabbage.',
    image: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=800&auto=format&fit=crop&q=85&v=dish-sf-nd1',
    dietary: ['non-veg'],
    prepTime: 12,
    available: true,
    customizations: [{ name: 'Extra Prawns (3pcs)', price: 80 }]
  },
  {
    id: 'dish-sf-nd2',
    name: 'Classic Mixed Seafood Hakka Noodles',
    category: 'chinese',
    shopSlug: 'giri-seafood',
    shopName: 'Giri Seafood & Lounge',
    price: 390,
    description: 'Noodles tossed with fish, prawns, calamari, garlic, and dark soy sauce.',
    image: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=800&auto=format&fit=crop&q=85&v=dish-sf-nd2',
    dietary: ['non-veg'],
    prepTime: 14,
    available: true,
    customizations: [{ name: 'Extra Chili Sauce', price: 0 }]
  },
  {
    id: 'dish-sf-nd3',
    name: 'Spicy Chilli Garlic Prawn Noodles',
    category: 'chinese',
    shopSlug: 'giri-seafood',
    shopName: 'Giri Seafood & Lounge',
    price: 380,
    description: 'Spicy noodles wok tossed with minced garlic, crushed red chilies, and juicy prawns.',
    image: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=800&auto=format&fit=crop&q=85&v=dish-sf-nd3',
    dietary: ['non-veg', 'spicy'],
    prepTime: 14,
    available: true,
    customizations: [{ name: 'Add Fried Egg', price: 25 }]
  },
  {
    id: 'dish-sf-nd4',
    name: 'Fiery Schezwan Mixed Seafood Noodles',
    category: 'chinese',
    shopSlug: 'giri-seafood',
    shopName: 'Giri Seafood & Lounge',
    price: 400,
    description: 'Noodles tossed in house-made spicy Schezwan pepper sauce with mixed seafood.',
    image: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=800&auto=format&fit=crop&q=85&v=dish-sf-nd4',
    dietary: ['non-veg', 'spicy'],
    prepTime: 14,
    available: true,
    customizations: [{ name: 'Extra Schezwan Sauce', price: 20 }]
  },

  // 13. LOUNGE STARTERS
  {
    id: 'dish-sf-ls1',
    name: 'Loaded Melted Cheese Jalapeño Nachos',
    category: 'starters',
    shopSlug: 'giri-seafood',
    shopName: 'Giri Seafood & Lounge',
    price: 240,
    description: 'Tortilla chips smothered in melted cheese sauce, jalapeños, olives, and fresh salsa.',
    image: 'https://images.unsplash.com/photo-1513456852971-30c0b8199d4d?w=800&auto=format&fit=crop&q=85&v=dish-sf-ls1',
    dietary: ['veg'],
    prepTime: 10,
    available: true,
    customizations: [{ name: 'Guacamole Side Dip', price: 40 }]
  },
  {
    id: 'dish-sf-ls2',
    name: 'Crispy Golden Mozzarella Cheese Balls',
    category: 'starters',
    shopSlug: 'giri-seafood',
    shopName: 'Giri Seafood & Lounge',
    price: 220,
    description: 'Deep-fried gooey mozzarella cheese balls served with spicy marinara dip.',
    image: 'https://images.unsplash.com/photo-1541529086526-db283c563270?w=800&auto=format&fit=crop&q=85&v=dish-sf-ls2',
    dietary: ['veg'],
    prepTime: 10,
    available: true,
    customizations: [{ name: 'Marinara Sauce Extra', price: 20 }]
  },
  {
    id: 'dish-sf-ls3',
    name: 'Classic Salted Crispy Potato Fries',
    category: 'fast-food',
    shopSlug: 'giri-seafood',
    shopName: 'Giri Seafood & Lounge',
    price: 140,
    description: 'Crispy potato french fries seasoned with sea salt.',
    image: 'https://images.unsplash.com/photo-1576107232684-1279f3908594?w=800&auto=format&fit=crop&q=85&v=dish-sf-ls3',
    dietary: ['veg'],
    prepTime: 8,
    available: true,
    customizations: [{ name: 'Mayo Dip', price: 20 }]
  },
  {
    id: 'dish-sf-ls4',
    name: 'Spicy African Peri Peri Seasoned Fries',
    category: 'fast-food',
    shopSlug: 'giri-seafood',
    shopName: 'Giri Seafood & Lounge',
    price: 160,
    description: 'Crispy fries dusted with spicy peri peri seasoning.',
    image: 'https://images.unsplash.com/photo-1576107232684-1279f3908594?w=800&auto=format&fit=crop&q=85&v=dish-sf-ls4',
    dietary: ['veg', 'spicy'],
    prepTime: 8,
    available: true,
    customizations: [{ name: 'Cheese Dip', price: 30 }]
  },
  {
    id: 'dish-sf-ls5',
    name: 'Crispy Garlic Herb Potato Wedges',
    category: 'fast-food',
    shopSlug: 'giri-seafood',
    shopName: 'Giri Seafood & Lounge',
    price: 170,
    description: 'Thick potato wedges roasted with garlic, parsley, and olive oil.',
    image: 'https://images.unsplash.com/photo-1576107232684-1279f3908594?w=800&auto=format&fit=crop&q=85&v=dish-sf-ls5',
    dietary: ['veg'],
    prepTime: 10,
    available: true,
    customizations: [{ name: 'Sour Cream Dip', price: 25 }]
  },

  // 14. LOUNGE CHICKEN
  {
    id: 'dish-sf-lc1',
    name: 'Crispy Fried Spicy Buffalo Chicken Wings',
    category: 'starters',
    shopSlug: 'giri-seafood',
    shopName: 'Giri Seafood & Lounge',
    price: 320,
    description: 'Deep-fried chicken wings coated in fiery red buffalo sauce, served with blue cheese dip.',
    image: 'https://images.unsplash.com/photo-1567620832903-9fc6debc209f?w=800&auto=format&fit=crop&q=85&v=dish-sf-lc1',
    dietary: ['non-veg', 'spicy'],
    prepTime: 14,
    available: true,
    customizations: [{ name: 'Extra Buffalo Sauce', price: 20 }]
  },
  {
    id: 'dish-sf-lc2',
    name: 'Smoked Honey Glazed BBQ Wings',
    category: 'starters',
    shopSlug: 'giri-seafood',
    shopName: 'Giri Seafood & Lounge',
    price: 340,
    description: 'Grilled chicken wings glazed in sweet smoked hickory BBQ sauce.',
    image: 'https://images.unsplash.com/photo-1567620832903-9fc6debc209f?w=800&auto=format&fit=crop&q=85&v=dish-sf-lc2',
    dietary: ['non-veg', 'chef-special'],
    prepTime: 14,
    available: true,
    customizations: [{ name: 'Sesame Seed Garnish', price: 0 }]
  },
  {
    id: 'dish-sf-lc3',
    name: 'Golden Crunchy Tender Chicken Strips',
    category: 'starters',
    shopSlug: 'giri-seafood',
    shopName: 'Giri Seafood & Lounge',
    price: 290,
    description: 'Boneless chicken tenders crumbed and fried crisp, served with honey mustard.',
    image: 'https://images.unsplash.com/photo-1567620832903-9fc6debc209f?w=800&auto=format&fit=crop&q=85&v=dish-sf-lc3',
    dietary: ['non-veg'],
    prepTime: 12,
    available: true,
    customizations: [{ name: 'Honey Mustard Dip', price: 20 }]
  },
  {
    id: 'dish-sf-lc4',
    name: 'Bite-Sized Crispy Chicken Popcorn',
    category: 'starters',
    shopSlug: 'giri-seafood',
    shopName: 'Giri Seafood & Lounge',
    price: 270,
    description: 'Bite-sized seasoned chicken popcorn fried golden crisp.',
    image: 'https://images.unsplash.com/photo-1567620832903-9fc6debc209f?w=800&auto=format&fit=crop&q=85&v=dish-sf-lc4',
    dietary: ['non-veg'],
    prepTime: 10,
    available: true,
    customizations: [{ name: 'Spicy Mayo Dip', price: 20 }]
  },
  {
    id: 'dish-sf-lc5',
    name: 'Flame Grilled Teriyaki Chicken Skewers',
    category: 'starters',
    shopSlug: 'giri-seafood',
    shopName: 'Giri Seafood & Lounge',
    price: 310,
    description: 'Chicken thigh skewers glazed in Japanese sweet teriyaki glaze.',
    image: 'https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?w=800&auto=format&fit=crop&q=85&v=dish-sf-lc5',
    dietary: ['non-veg'],
    prepTime: 14,
    available: true,
    customizations: [{ name: 'Spring Onion Garnish', price: 0 }]
  },

  // 15. LOUNGE VEG
  {
    id: 'dish-sf-lv1',
    name: 'Charcoal Roasted Tandoori Paneer Tikka',
    category: 'starters',
    shopSlug: 'giri-seafood',
    shopName: 'Giri Seafood & Lounge',
    price: 310,
    description: 'Fresh cottage cheese blocks skewered with bell peppers and tandoor roasted.',
    image: 'https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?w=800&auto=format&fit=crop&q=85&v=dish-sf-lv1',
    dietary: ['veg'],
    prepTime: 14,
    available: true,
    customizations: [{ name: 'Mint Chutney', price: 15 }]
  },
  {
    id: 'dish-sf-lv2',
    name: 'Spicy Indo-Chinese Crispy Pepper Corn',
    category: 'starters',
    shopSlug: 'giri-seafood',
    shopName: 'Giri Seafood & Lounge',
    price: 230,
    description: 'Crispy sweet corn kernels tossed with black pepper, spring onions, and garlic.',
    image: 'https://images.unsplash.com/photo-1551782450-a2132b4ba21d?w=800&auto=format&fit=crop&q=85&v=dish-sf-lv2',
    dietary: ['veg'],
    prepTime: 10,
    available: true,
    customizations: [{ name: 'Lemon Squeeze', price: 0 }]
  },
  {
    id: 'dish-sf-lv3',
    name: 'Crunchy Vegetable Spring Rolls with Sweet Chilli',
    category: 'starters',
    shopSlug: 'giri-seafood',
    shopName: 'Giri Seafood & Lounge',
    price: 220,
    description: 'Crispy rolls filled with shredded cabbage, carrots, bell peppers, served with sweet chili sauce.',
    image: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=800&auto=format&fit=crop&q=85&v=dish-sf-lv3',
    dietary: ['veg'],
    prepTime: 12,
    available: true,
    customizations: [{ name: 'Sweet Chili Dip', price: 15 }]
  },
  {
    id: 'dish-sf-lv4',
    name: 'Sautéed Button Mushroom Pepper Chukka',
    category: 'starters',
    shopSlug: 'giri-seafood',
    shopName: 'Giri Seafood & Lounge',
    price: 260,
    description: 'Whole button mushrooms tossed with crushed black pepper, onions, and curry leaves.',
    image: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=800&auto=format&fit=crop&q=85&v=dish-sf-lv4',
    dietary: ['veg', 'spicy'],
    prepTime: 12,
    available: true,
    customizations: [{ name: 'Garlic Butter Toss', price: 20 }]
  },
  {
    id: 'dish-sf-lv5',
    name: 'Double Layered Loaded Cheese Nachos',
    category: 'starters',
    shopSlug: 'giri-seafood',
    shopName: 'Giri Seafood & Lounge',
    price: 260,
    description: 'Double layered corn chips topped with warm cheese sauce, refried beans, and salsa.',
    image: 'https://images.unsplash.com/photo-1513456852971-30c0b8199d4d?w=800&auto=format&fit=crop&q=85&v=dish-sf-lv5',
    dietary: ['veg'],
    prepTime: 12,
    available: true,
    customizations: [{ name: 'Extra Cheese Sauce', price: 30 }]
  },

  // 16. SEAFOOD PLATTERS
  {
    id: 'dish-sf-pl1',
    name: 'Royal Tawa & Grilled Fish Combination Platter',
    category: 'mains',
    shopSlug: 'giri-seafood',
    shopName: 'Giri Seafood & Lounge',
    price: 780,
    description: 'Assortment of King fish fry, fish tikka, and lemon pepper grilled fish.',
    image: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=800&auto=format&fit=crop&q=85&v=dish-sf-pl1',
    dietary: ['non-veg', 'chef-special'],
    prepTime: 20,
    available: true,
    customizations: [{ name: 'Tartar & Mint Dip Pair', price: 30 }]
  },
  {
    id: 'dish-sf-pl2',
    name: 'Sizzling Garlic, Chilli & Tandoori Prawn Platter',
    category: 'mains',
    shopSlug: 'giri-seafood',
    shopName: 'Giri Seafood & Lounge',
    price: 890,
    description: 'Platter of garlic butter prawns, chilli prawns, and tandoori tiger prawns.',
    image: 'https://images.unsplash.com/photo-1565680018434-b513d5e5fd47?w=800&auto=format&fit=crop&q=85&v=dish-sf-pl2',
    dietary: ['non-veg', 'chef-special'],
    prepTime: 20,
    available: true,
    customizations: [{ name: 'Extra Garlic Butter', price: 35 }]
  },
  {
    id: 'dish-sf-pl3',
    name: 'Coastal Roast & Garlic Butter Crab Platter',
    category: 'mains',
    shopSlug: 'giri-seafood',
    shopName: 'Giri Seafood & Lounge',
    price: 950,
    description: 'Combination of Chettinad crab roast and garlic butter sea crab.',
    image: 'https://images.unsplash.com/photo-1559742811-822863c46f43?w=800&auto=format&fit=crop&q=85&v=dish-sf-pl3',
    dietary: ['non-veg', 'chef-special'],
    prepTime: 22,
    available: true,
    customizations: [{ name: 'Crab Crackers Service', price: 0 }]
  },
  {
    id: 'dish-sf-pl4',
    name: 'Traditional Kerala & Goan Seafood Platter',
    category: 'mains',
    shopSlug: 'giri-seafood',
    shopName: 'Giri Seafood & Lounge',
    price: 880,
    description: 'Assorted coastal fish fry, prawns chukka, calamari, served with appam.',
    image: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=800&auto=format&fit=crop&q=85&v=dish-sf-pl4',
    dietary: ['non-veg', 'chef-special'],
    prepTime: 20,
    available: true,
    customizations: [{ name: 'Extra Appam (2pcs)', price: 50 }]
  },
  {
    id: 'dish-sf-pl5',
    name: 'Grand Lobster, Prawn, Fish & Squid Platter',
    category: 'mains',
    shopSlug: 'giri-seafood',
    shopName: 'Giri Seafood & Lounge',
    price: 1650,
    description: 'Ultimate seafood luxury platter: Whole grilled lobster, jumbo tiger prawns, fish fillets, and calamari rings.',
    image: 'https://images.unsplash.com/photo-1553240799-36bbf332a5c3?w=800&auto=format&fit=crop&q=85&v=dish-sf-pl5',
    dietary: ['non-veg', 'chef-special'],
    prepTime: 25,
    available: true,
    customizations: [{ name: 'Side Garlic Bread & Butter Dip', price: 60 }]
  },

  // 17. FAMILY PLATTERS
  {
    id: 'dish-sf-fp1',
    name: 'Grand Family Mixed Seafood Grill Feast',
    category: 'mains',
    shopSlug: 'giri-seafood',
    shopName: 'Giri Seafood & Lounge',
    price: 1890,
    description: 'Generous platter serving 4-5 people: Grilled fish, tandoori prawns, fried calamari, crab masala, and seafood rice.',
    image: 'https://images.unsplash.com/photo-1553240799-36bbf332a5c3?w=800&auto=format&fit=crop&q=85&v=dish-sf-fp1',
    dietary: ['non-veg', 'chef-special'],
    prepTime: 25,
    available: true,
    customizations: [{ name: 'Extra Rice Portion', price: 50 }]
  },
  {
    id: 'dish-sf-fp2',
    name: 'Seafood & Tandoori Chicken Combination Platter',
    category: 'mains',
    shopSlug: 'giri-seafood',
    shopName: 'Giri Seafood & Lounge',
    price: 1690,
    description: 'Family feast with fish tikka, tandoori prawns, tandoori chicken legs, and seekh kebabs.',
    image: 'https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?w=800&auto=format&fit=crop&q=85&v=dish-sf-fp2',
    dietary: ['non-veg', 'chef-special'],
    prepTime: 25,
    available: true,
    customizations: [{ name: 'Naan Basket (4pcs)', price: 120 }]
  },
  {
    id: 'dish-sf-fp3',
    name: 'Complete Coastal Seafood Curries & Rice Feast',
    category: 'mains',
    shopSlug: 'giri-seafood',
    shopName: 'Giri Seafood & Lounge',
    price: 1790,
    description: 'Family curry combo: Malabar fish curry, prawn curry, crab roast, steamed basmati rice & appams.',
    image: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=800&auto=format&fit=crop&q=85&v=dish-sf-fp3',
    dietary: ['non-veg', 'chef-special'],
    prepTime: 25,
    available: true,
    customizations: [{ name: 'Extra Appam Basket', price: 80 }]
  },
  {
    id: 'dish-sf-fp4',
    name: '24K Royal Crown Seafood & Lobster Feast',
    category: 'mains',
    shopSlug: 'giri-seafood',
    shopName: 'Giri Seafood & Lounge',
    price: 2490,
    description: 'Royal feast for 4-6 guests: 2 Whole Grilled Lobsters, King Prawns, Salmon steaks, Crab Thermidor, and Mocktail Pitcher.',
    image: 'https://images.unsplash.com/photo-1553240799-36bbf332a5c3?w=800&auto=format&fit=crop&q=85&v=dish-sf-fp4',
    dietary: ['non-veg', 'chef-special'],
    prepTime: 30,
    available: true,
    customizations: [{ name: 'Complimentary Mocktail Pitcher', price: 0 }]
  },

  // 18. MOCKTAILS
  {
    id: 'dish-sf-mk1',
    name: 'Classic Spearmint Lime Sparkling Virgin Mojito',
    category: 'drinks',
    shopSlug: 'giri-seafood',
    shopName: 'Giri Seafood & Lounge',
    price: 180,
    description: 'Fresh spearmint leaves muddled with lime juice, sugar, and sparkling soda.',
    image: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?w=800&auto=format&fit=crop&q=85&v=dish-sf-mk1',
    dietary: ['veg', 'chef-special'],
    prepTime: 5,
    available: true,
    customizations: [{ name: 'Extra Mint Crush', price: 15 }]
  },
  {
    id: 'dish-sf-mk2',
    name: 'Electric Blue Curaçao Soda Mocktail',
    category: 'drinks',
    shopSlug: 'giri-seafood',
    shopName: 'Giri Seafood & Lounge',
    price: 190,
    description: 'Vibrant blue curaçao syrup mixed with lemon juice, mint, and Sprite.',
    image: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?w=800&auto=format&fit=crop&q=85&v=dish-sf-mk2',
    dietary: ['veg'],
    prepTime: 5,
    available: true,
    customizations: [{ name: 'Cherry Top', price: 15 }]
  },
  {
    id: 'dish-sf-mk3',
    name: 'Tangy Green Apple Mint Mojito',
    category: 'drinks',
    shopSlug: 'giri-seafood',
    shopName: 'Giri Seafood & Lounge',
    price: 195,
    description: 'Crisp green apple syrup, mint, lime, and crushed ice soda.',
    image: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?w=800&auto=format&fit=crop&q=85&v=dish-sf-mk3',
    dietary: ['veg'],
    prepTime: 5,
    available: true,
    customizations: [{ name: 'Green Apple Slice', price: 10 }]
  },
  {
    id: 'dish-sf-mk4',
    name: 'Fresh Berry Mint Soda Mojito',
    category: 'drinks',
    shopSlug: 'giri-seafood',
    shopName: 'Giri Seafood & Lounge',
    price: 200,
    description: 'Real strawberry crush muddled with fresh mint, lime, and soda.',
    image: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?w=800&auto=format&fit=crop&q=85&v=dish-sf-mk4',
    dietary: ['veg'],
    prepTime: 5,
    available: true,
    customizations: [{ name: 'Fresh Strawberry Garnish', price: 20 }]
  },
  {
    id: 'dish-sf-mk5',
    name: 'Tropical Passion Fruit Sparkling Cooler',
    category: 'drinks',
    shopSlug: 'giri-seafood',
    shopName: 'Giri Seafood & Lounge',
    price: 210,
    description: 'Exotic passion fruit pulp blended with lemon juice, mint, and sparkling soda.',
    image: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?w=800&auto=format&fit=crop&q=85&v=dish-sf-mk5',
    dietary: ['veg', 'chef-special'],
    prepTime: 5,
    available: true,
    customizations: [{ name: 'Chia Seeds Top', price: 15 }]
  },

  // 19. FRESH JUICES
  {
    id: 'dish-sf-fj1',
    name: 'Chilled Fresh Watermelon Juice',
    category: 'drinks',
    shopSlug: 'giri-seafood',
    shopName: 'Giri Seafood & Lounge',
    price: 140,
    description: 'Fresh extracted watermelon juice with mint and black salt.',
    image: 'https://images.unsplash.com/photo-1589733955941-5eeaf752f6dd?w=800&auto=format&fit=crop&q=85&v=dish-sf-fj1',
    dietary: ['veg'],
    prepTime: 5,
    available: true,
    customizations: [{ name: 'No Added Sugar', price: 0 }]
  },
  {
    id: 'dish-sf-fj2',
    name: 'Sweet Queen Pineapple Juice',
    category: 'drinks',
    shopSlug: 'giri-seafood',
    shopName: 'Giri Seafood & Lounge',
    price: 150,
    description: 'Fresh pineapple juice pressed with rock salt.',
    image: 'https://images.unsplash.com/photo-1613478223719-2ab802602423?w=800&auto=format&fit=crop&q=85&v=dish-sf-fj2',
    dietary: ['veg'],
    prepTime: 5,
    available: true,
    customizations: [{ name: 'Mint Infusion', price: 10 }]
  },
  {
    id: 'dish-sf-fj3',
    name: 'Cold Pressed Valencia Orange Juice',
    category: 'drinks',
    shopSlug: 'giri-seafood',
    shopName: 'Giri Seafood & Lounge',
    price: 160,
    description: 'Pure cold-pressed fresh orange juice.',
    image: 'https://images.unsplash.com/photo-1613478223719-2ab802602423?w=800&auto=format&fit=crop&q=85&v=dish-sf-fj3',
    dietary: ['veg', 'chef-special'],
    prepTime: 5,
    available: true,
    customizations: [{ name: 'No Ice Option', price: 0 }]
  },
  {
    id: 'dish-sf-fj4',
    name: 'Fresh Kashmiri Pomegranate Juice',
    category: 'drinks',
    shopSlug: 'giri-seafood',
    shopName: 'Giri Seafood & Lounge',
    price: 180,
    description: 'Rich fresh pomegranate seed juice.',
    image: 'https://images.unsplash.com/photo-1613478223719-2ab802602423?w=800&auto=format&fit=crop&q=85&v=dish-sf-fj4',
    dietary: ['veg'],
    prepTime: 6,
    available: true,
    customizations: [{ name: 'Chat Masala Salt', price: 0 }]
  },
  {
    id: 'dish-sf-fj5',
    name: 'Freshly Squeezed Sweet Lime (Mosambi) Juice',
    category: 'drinks',
    shopSlug: 'giri-seafood',
    shopName: 'Giri Seafood & Lounge',
    price: 140,
    description: 'Chilled fresh sweet lime juice with black salt.',
    image: 'https://images.unsplash.com/photo-1613478223719-2ab802602423?w=800&auto=format&fit=crop&q=85&v=dish-sf-fj5',
    dietary: ['veg'],
    prepTime: 5,
    available: true,
    customizations: [{ name: 'Extra Black Salt', price: 0 }]
  },

  // 20. LOUNGE BEVERAGES
  {
    id: 'dish-sf-bv1',
    name: 'Chilled Lemon Peach Iced Tea',
    category: 'drinks',
    shopSlug: 'giri-seafood',
    shopName: 'Giri Seafood & Lounge',
    price: 140,
    description: 'Brewed black tea infused with peach syrup, lemon, and ice.',
    image: 'https://images.unsplash.com/photo-1517701604599-bb29b565090c?w=800&auto=format&fit=crop&q=85&v=dish-sf-bv1',
    dietary: ['veg'],
    prepTime: 4,
    available: true,
    customizations: [{ name: 'Mint Slice', price: 5 }]
  },
  {
    id: 'dish-sf-bv2',
    name: 'Thick Creamy Chilled Cold Coffee',
    category: 'drinks',
    shopSlug: 'giri-seafood',
    shopName: 'Giri Seafood & Lounge',
    price: 180,
    description: 'Espresso blended with cold milk, vanilla ice cream, and chocolate drizzle.',
    image: 'https://images.unsplash.com/photo-1517701604599-bb29b565090c?w=800&auto=format&fit=crop&q=85&v=dish-sf-bv2',
    dietary: ['veg'],
    prepTime: 5,
    available: true,
    customizations: [{ name: 'Extra Ice Cream Scoop', price: 35 }]
  },
  {
    id: 'dish-sf-bv3',
    name: 'Sparkling Sweet & Salt Fresh Lime Soda',
    category: 'drinks',
    shopSlug: 'giri-seafood',
    shopName: 'Giri Seafood & Lounge',
    price: 90,
    description: 'Refreshing chilled soda water mixed with lemon juice, sugar, and rock salt.',
    image: 'https://images.unsplash.com/photo-1517701604599-bb29b565090c?w=800&auto=format&fit=crop&q=85&v=dish-sf-bv3',
    dietary: ['veg'],
    prepTime: 4,
    available: true,
    customizations: [{ name: 'Sweet Only Option', price: 0 }]
  },
  {
    id: 'dish-sf-bv4',
    name: 'Refreshing Crushed Ginger Lemonade',
    category: 'drinks',
    shopSlug: 'giri-seafood',
    shopName: 'Giri Seafood & Lounge',
    price: 110,
    description: 'Chilled lemonade infused with crushed fresh ginger root and mint.',
    image: 'https://images.unsplash.com/photo-1517701604599-bb29b565090c?w=800&auto=format&fit=crop&q=85&v=dish-sf-bv4',
    dietary: ['veg'],
    prepTime: 4,
    available: true,
    customizations: [{ name: 'Extra Ginger Punch', price: 0 }]
  },
  {
    id: 'dish-sf-bv5',
    name: 'Spearmint Cucumber Chilled Cooler',
    category: 'drinks',
    shopSlug: 'giri-seafood',
    shopName: 'Giri Seafood & Lounge',
    price: 130,
    description: 'Hydrating blend of fresh cucumber juice, spearmint, lemon, and soda.',
    image: 'https://images.unsplash.com/photo-1517701604599-bb29b565090c?w=800&auto=format&fit=crop&q=85&v=dish-sf-bv5',
    dietary: ['veg'],
    prepTime: 4,
    available: true,
    customizations: [{ name: 'Cucumber Slice Garnish', price: 0 }]
  },

  // 21. DESSERTS
  {
    id: 'dish-sf-ds1',
    name: 'Baked New York Blueberry Cheesecake',
    category: 'desserts',
    shopSlug: 'giri-seafood',
    shopName: 'Giri Seafood & Lounge',
    price: 240,
    description: 'Classic rich baked cheesecake topped with wild blueberry compote.',
    image: 'https://images.unsplash.com/photo-1533134242443-d4fd215305ad?w=800&auto=format&fit=crop&q=85&v=dish-sf-ds1',
    dietary: ['veg', 'chef-special'],
    prepTime: 3,
    available: true,
    customizations: [{ name: 'Extra Blueberry Sauce', price: 30 }]
  },
  {
    id: 'dish-sf-ds2',
    name: 'Warm Fudgy Walnut Chocolate Brownie',
    category: 'desserts',
    shopSlug: 'giri-seafood',
    shopName: 'Giri Seafood & Lounge',
    price: 160,
    description: 'Warm chocolate brownie stuffed with roasted walnuts and hot fudge sauce.',
    image: 'https://images.unsplash.com/photo-1606313564200-e75d5e30476c?w=800&auto=format&fit=crop&q=85&v=dish-sf-ds2',
    dietary: ['veg'],
    prepTime: 4,
    available: true,
    customizations: [{ name: 'Vanilla Ice Cream Top', price: 40 }]
  },
  {
    id: 'dish-sf-ds3',
    name: 'Italian Espresso Mascarpone Tiramisu',
    category: 'desserts',
    shopSlug: 'giri-seafood',
    shopName: 'Giri Seafood & Lounge',
    price: 230,
    description: 'Ladyfinger biscuits soaked in espresso syrup, layered with mascarpone cream.',
    image: 'https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=800&auto=format&fit=crop&q=85&v=dish-sf-ds3',
    dietary: ['veg', 'chef-special'],
    prepTime: 3,
    available: true,
    customizations: [{ name: 'Cocoa Powder Dust Extra', price: 0 }]
  },
  {
    id: 'dish-sf-ds4',
    name: 'Belgian Dark Chocolate Mousse',
    category: 'desserts',
    shopSlug: 'giri-seafood',
    shopName: 'Giri Seafood & Lounge',
    price: 180,
    description: 'Silky smooth dark chocolate mousse topped with whipped cream.',
    image: 'https://images.unsplash.com/photo-1541781774459-bb29b565090c?w=800&auto=format&fit=crop&q=85&v=dish-sf-ds4',
    dietary: ['veg'],
    prepTime: 3,
    available: true,
    customizations: [{ name: 'Chocolate Shavings', price: 15 }]
  },
  {
    id: 'dish-sf-ds5',
    name: 'Classic Baked Vanilla Caramel Flan Custard',
    category: 'desserts',
    shopSlug: 'giri-seafood',
    shopName: 'Giri Seafood & Lounge',
    price: 150,
    description: 'Smooth baked egg custard with dark amber caramel sauce glaze.',
    image: 'https://images.unsplash.com/photo-1587314168485-3236d6710814?w=800&auto=format&fit=crop&q=85&v=dish-sf-ds5',
    dietary: ['veg'],
    prepTime: 3,
    available: true,
    customizations: [{ name: 'Extra Caramel Glaze', price: 20 }]
  },

  // 22. ICE CREAMS
  {
    id: 'dish-sf-ic1',
    name: 'French Vanilla Bean Ice Cream Scoop',
    category: 'desserts',
    shopSlug: 'giri-seafood',
    shopName: 'Giri Seafood & Lounge',
    price: 90,
    description: 'Pure vanilla bean ice cream scoop.',
    image: 'https://images.unsplash.com/photo-1570197788417-0e82375c9371?w=800&auto=format&fit=crop&q=85&v=dish-sf-ic1',
    dietary: ['veg'],
    prepTime: 2,
    available: true,
    customizations: [{ name: 'Hot Fudge Drizzle', price: 20 }]
  },
  {
    id: 'dish-sf-ic2',
    name: 'Belgian Dark Chocolate Ice Cream Scoop',
    category: 'desserts',
    shopSlug: 'giri-seafood',
    shopName: 'Giri Seafood & Lounge',
    price: 100,
    description: 'Intense Belgian dark chocolate ice cream scoop.',
    image: 'https://images.unsplash.com/photo-1570197788417-0e82375c9371?w=800&auto=format&fit=crop&q=85&v=dish-sf-ic2',
    dietary: ['veg'],
    prepTime: 2,
    available: true,
    customizations: [{ name: 'Choco Chips', price: 15 }]
  },
  {
    id: 'dish-sf-ic3',
    name: 'Crunchy Butterscotch Praline Ice Cream Scoop',
    category: 'desserts',
    shopSlug: 'giri-seafood',
    shopName: 'Giri Seafood & Lounge',
    price: 100,
    description: 'Caramel ice cream with crunchy butterscotch bits.',
    image: 'https://images.unsplash.com/photo-1570197788417-0e82375c9371?w=800&auto=format&fit=crop&q=85&v=dish-sf-ic3',
    dietary: ['veg'],
    prepTime: 2,
    available: true,
    customizations: [{ name: 'Caramel Sauce Drizzle', price: 15 }]
  },
  {
    id: 'dish-sf-ic4',
    name: 'Fresh Strawberry Cream Ice Cream Scoop',
    category: 'desserts',
    shopSlug: 'giri-seafood',
    shopName: 'Giri Seafood & Lounge',
    price: 95,
    description: 'Strawberry ice cream made with real strawberry crush.',
    image: 'https://images.unsplash.com/photo-1570197788417-0e82375c9371?w=800&auto=format&fit=crop&q=85&v=dish-sf-ic4',
    dietary: ['veg'],
    prepTime: 2,
    available: true,
    customizations: [{ name: 'Strawberry Drizzle', price: 15 }]
  },
  {
    id: 'dish-sf-ic5',
    name: 'Alphonso Mango Fruit Scoop Ice Cream',
    category: 'desserts',
    shopSlug: 'giri-seafood',
    shopName: 'Giri Seafood & Lounge',
    price: 105,
    description: 'Pure Alphonso mango ice cream scoop.',
    image: 'https://images.unsplash.com/photo-1570197788417-0e82375c9371?w=800&auto=format&fit=crop&q=85&v=dish-sf-ic5',
    dietary: ['veg'],
    prepTime: 2,
    available: true,
    customizations: [{ name: 'Mango Sauce', price: 15 }]
  },
  {
    id: 'dish-sf-ic6',
    name: 'Sizzling Brownie Hot Fudge Sundae',
    category: 'desserts',
    shopSlug: 'giri-seafood',
    shopName: 'Giri Seafood & Lounge',
    price: 210,
    description: 'Warm brownie topped with vanilla ice cream, hot fudge sauce, and roasted nuts.',
    image: 'https://images.unsplash.com/photo-1570197788417-0e82375c9371?w=800&auto=format&fit=crop&q=85&v=dish-sf-ic6',
    dietary: ['veg', 'chef-special'],
    prepTime: 5,
    available: true,
    customizations: [{ name: 'Extra Hot Fudge', price: 25 }]
  }
`;

const seafoodCode = `export const GIRI_SEAFOOD_DISHES: MenuItem[] = [\n${completeSeafoodCatalog}\n];\n`;

const sfIndex = dishesContent.indexOf("export const GIRI_SEAFOOD_DISHES");
if (sfIndex !== -1) {
  const endIndex = dishesContent.indexOf("const RAW_INITIAL_DISHES");
  dishesContent = dishesContent.substring(0, sfIndex) + seafoodCode + dishesContent.substring(endIndex);
} else {
  dishesContent = dishesContent.replace(
    "const RAW_INITIAL_DISHES: MenuItem[] = [",
    `${seafoodCode}\nconst RAW_INITIAL_DISHES: MenuItem[] = [\n  ...GIRI_SEAFOOD_DISHES,`
  );
}

dishesContent = dishesContent.replace(
  /const versionKey = 'giri_dishes_[^']+';/,
  "const versionKey = 'giri_dishes_v37_seafood_all_22_categories_populated';"
);

fs.writeFileSync(dishesPath, dishesContent, 'utf8');
console.log('Successfully updated dishes.ts with 110+ authentic dishes for Giri Seafood & Lounge!');
